### ISSUE TITLE
KeyError: b'Buffers:'

### ISSUE THREAD

**Issue by Pawamoy** [giampaolo/psutil#1010]
- OS: Ubuntu 14.04
- Python: 3.5.3
- psutil: 5.2.1

```
Traceback (most recent call last):
  ...
  File "/webapps/genida/repository/genida/app/dashboard/charts.py", line 14, in machine_usage_chart
    ram = psutil.virtual_memory().percent
  File "/webapps/genida/virtualenv/lib/python3.5/site-packages/psutil/__init__.py", line 1985, in virtual_memory
    ret = _psplatform.virtual_memory()
  File "/webapps/genida/virtualenv/lib/python3.5/site-packages/psutil/_pslinux.py", line 399, in virtual_memory
    buffers = mems[b'Buffers:']
KeyError: b'Buffers:'
```

```
$ cat /proc/meminfo 
MemTotal:        1048576 kB
MemFree:          834036 kB
SwapTotal:             0 kB
SwapFree:              0 kB
```

**Comment by giampaolo** [comment]
Can you paste the output of `cat /proc/meminfo`?
