### ISSUE TITLE
net_connections() are broken after 4.3.1 in Windows XP

### ISSUE THREAD

**Issue by alxchk** [giampaolo/psutil#1027]
Last working release is 4.3.1

```
>>> psutil.net_connections()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\psutil\__init__.py", line 1935, in net_connections
    return _psplatform.net_connections(kind)
  File "C:\Python27\lib\site-packages\psutil\_pswindows.py", line 273, in net_connections
    rawlist = cext.net_connections(_pid, families, types)
WindowsError: [Error 50] The request is not supported
>>>
```

**Comment by giampaolo** [comment]
I see. Well, win XP is no longer supported and I don't want to invest time into fixing this bug, sorry.
I suppose latest release will have other issues as well.
As per psutil doc 3.4.2 is the latest binary version working with XP and current "may" work on win XP if compiled from sources:
https://pythonhosted.org/psutil/#q-a
