### ISSUE TITLE
cmdline() on Windows may raise OSError with unicode command args

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#1028]
From https://ci.appveyor.com/project/giampaolo/psutil/build/1138/job/8ra97nqi1s3je8d6:

```
======================================================================
ERROR: psutil.tests.test_process.TestInvalidUnicode.test_proc_cmdline
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\projects\psutil\psutil\tests\test_process.py", line 2080, in test_proc_cmdline
    p.cmdline()
  File "c:\projects\psutil\psutil\__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "c:\projects\psutil\psutil\_pswindows.py", line 620, in wrapper
    return fun(self, *args, **kwargs)
  File "c:\projects\psutil\psutil\_pswindows.py", line 690, in cmdline
    ret = cext.proc_cmdline(self.pid)
OSError: [WinError 299] Only part of a ReadProcessMemory or WriteProcessMemory request was completed
----------------------------------------------------------------------
Ran 408 tests in 9.873s
```

**Comment by giampaolo** [comment]
This is the same C code section as #875 so `cmdline()`, `cwd()` and `environ()`should all suffer the same issue. Closing this out as a duplicate.
