### ISSUE TITLE
FreeBSD / OSX: Process.connections('unix') on python 3 does not properly handle unicode

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#1029]
The bug was exercised by the new unittest added here: 161f4fb751c89a11a843871ccf949e092d68e782:

```
======================================================================
ERROR: test_unicode.TestFSAPIsWithInvalidPath.test_connections
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/psutil/psutil/tests/test_unicode.py", line 174, in test_connections
    conn = psutil.Process().connections(kind='unix')[0]
  File "/vagrant/psutil/psutil/__init__.py", line 1217, in connections
    return self._proc.connections(kind)
  File "/vagrant/psutil/psutil/_psbsd.py", line 493, in wrapper
    return fun(self, *args, **kwargs)
  File "/vagrant/psutil/psutil/_psbsd.py", line 721, in connections
    rawlist = cext.proc_connections(self.pid, families, types)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 24: invalid start byte
```

EDIT - also on OSX:

```
======================================================================
ERROR: test_unicode.TestFSAPIsWithInvalidPath.test_proc_connections
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/psutil/psutil/tests/test_unicode.py", line 161, in test_proc_connections
    conn = psutil.Process().connections(kind='unix')[0]
  File "/vagrant/psutil/psutil/__init__.py", line 1217, in connections
    return self._proc.connections(kind)
  File "/vagrant/psutil/psutil/_psosx.py", line 293, in wrapper
    return fun(self, *args, **kwargs)
  File "/vagrant/psutil/psutil/_psosx.py", line 457, in connections
    rawlist = cext.proc_connections(self.pid, families, types)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 72: invalid start byte
```

**Comment by giampaolo** [comment]
I will handle this in #1040 as a bigger task. Closing this out as duplicate.
