### ISSUE TITLE
Consolidate API types

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#1039]
From https://github.com/giampaolo/psutil/blob/master/psutil/tests/test_unicode.py:

```
On Python 3 the returned paths are supposed to match 100% (and this
is tested).
Not on Python 2 though, where we assume correct unicode path handling
is broken. In fact it is broken for most os.* functions, see:
http://bugs.python.org/issue18695
There really is no way for psutil to handle unicode correctly on
Python 2 unless we make such APIs return a unicode type in certain
circumstances.
I'd rather have unicode support broken on Python 2 than having APIs
returning variable str/unicode types, see:
https://github.com/giampaolo/psutil/issues/655#issuecomment-136131180

As such we also test that all APIs on Python 2 always return str and
never unicode (in test_contracts.py).
```

Basically we assume unicode support is broken on Python 2 and want to make sure unicode is never returned. I added some tests about this (see: https://github.com/giampaolo/psutil/commit/35ebdfb172f4d27678c6d33d1a6f74ca2771e303) already.
The only place were we may want to return unicode is `WindowsService.description()` so this serves as a reminder for that (needs investigation).

Also, I'm adding tests to make sure the same types (int, float, whatever..., see https://github.com/giampaolo/psutil/commit/d67154d8a067526eaff953ae95561380b8f9b62a, https://github.com/giampaolo/psutil/commit/5aa3af31aa35d904d358171ad1049b46205494cf and [test_contracts.py](https://github.com/giampaolo/psutil/blob/master/psutil/tests/test_contracts.py)) are returned across across platforms and I already bumped in a couple of errors on OSX but I expect there will be more.

**Comment by giampaolo** [comment]
OSX : https://travis-ci.org/giampaolo/psutil/jobs/227283028

**Comment by giampaolo** [comment]
Windows: https://ci.appveyor.com/project/giampaolo/psutil/build/1152/job/s9d2526hkj6ge7g4

```
======================================================================
FAIL: psutil.tests.test_unicode.TestNonFSAPIS.test_proc_environ
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\projects\psutil\psutil\tests\test_unicode.py", line 271, in test_proc_environ
    self.assertIsInstance(k, str)
AssertionError: u'APPVEYOR_REPO_COMMIT_AUTHOR' is not an instance of <type 'str'>
----------------------------------------------------------------------
```

**Comment by giampaolo** [comment]
Windows: 

=====================================================================
ERROR: psutil.tests.test_windows.RemoteProcessTestCase.test_environ_64
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\user\desktop\psutil\psutil\tests\test_windows.py", line 716, in test_environ_64
    e = p.environ()
  File "c:\users\user\desktop\psutil\psutil\__init__.py", line 872, in environ
    return self._proc.environ()
  File "c:\users\user\desktop\psutil\psutil\_pswindows.py", line 620, in wrapper
    return fun(self, *args, **kwargs)
  File "c:\users\user\desktop\psutil\psutil\_pswindows.py", line 698, in environ
    return parse_environ_block(cext.proc_environ(self.pid))
NotImplementedError: NtWow64QueryVirtualMemory64 missing

======================================================================
FAIL: psutil.tests.test_contracts.TestFetchAllProcesses.test_fetch_all
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\user\desktop\psutil\psutil\tests\test_contracts.py", line 338, in test_fetch_all
    meth(ret, p)
  File "c:\users\user\desktop\psutil\psutil\tests\test_contracts.py", line 458, in cpu_times
    self.assertIsInstance(n, float)
AssertionError: 0 is not an instance of <type 'float'>

======================================================================
FAIL: psutil.tests.test_contracts.TestSystem.test_net_if_stats
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\user\desktop\psutil\psutil\tests\test_contracts.py", line 223, in test_net_if_stats
    self.assertIsInstance(ifname, str)
AssertionError: u'Ethernet 3' is not an instance of <type 'str'>

======================================================================
FAIL: psutil.tests.test_system.TestSystemAPIs.test_net_if_stats
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\user\desktop\psutil\psutil\tests\test_system.py", line 642, in test_net_if_stats
    self.assertIsInstance(name, str)
AssertionError: u'Ethernet 3' is not an instance of <type 'str'>

======================================================================
FAIL: psutil.tests.test_unicode.TestNonFSAPIS.test_proc_environ
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\user\desktop\psutil\psutil\tests\test_unicode.py", line 270, in test_proc_environ
    self.assertIsInstance(k, str)
AssertionError: u'TMP' is not an instance of <type 'str'>

**Comment by giampaolo** [comment]
I will handle this in #1040 as a bigger task. Closing this out as duplicate.

**Comment by giampaolo** [comment]
Actually I will handle the `str` type issue in the other ticket and the rest here.

**Comment by giampaolo** [comment]
OK, this should be fixed by now.
