### ISSUE TITLE
disk and net io_counters() may raise TypeError

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#1062]
In case there are no disks or NICs installed on the system, see:
https://ci.appveyor.com/project/giampaolo/psutil/build/1238/job/b2wdni5v8lx7nxmm

```
======================================================================
ERROR: psutil.tests.test_misc.TestWrapNumbers.test_cache_clear_public_apis
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\projects\psutil\psutil\tests\test_misc.py", line 607, in test_cache_clear_public_apis
    psutil.disk_io_counters()
  File "c:\projects\psutil\psutil\__init__.py", line 2094, in disk_io_counters
    return nt(*[sum(x) for x in zip(*rawdict.values())])
TypeError: __new__() missing 6 required positional arguments: 'read_count', 'write_count', 'read_bytes', 'write_bytes', 'read_time', and 'write_time'
```

**Comment by giampaolo** [comment]
Fixed in 2d32a26a257c7ce17806f0ec150bcbba5f39f914.
