### ISSUE TITLE
OpenBSD: net_connections() leaks memory

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#1068]
```
======================================================================
FAIL: psutil.tests.test_memory_leaks.TestModuleFunctionsLeaks.test_net_connections
----------------------------------------------------------------------
Traceback (most recent call last):
  File "psutil/tests/test_memory_leaks.py", line 532, in test_net_connections
    self.execute(psutil.net_connections)
  File "psutil/tests/test_memory_leaks.py", line 159, in execute
    ncalls
AssertionError: +12.00K after 1000 calls, +32.00K after another 2751 calls
```

**Comment by giampaolo** [comment]
It turns out this is a false positive.

**Comment by giampaolo** [comment]
Turned out to be a false positive back in 2017, I just forgot to close the ticket.
