### ISSUE TITLE
ImportError: cannot import name AF_INET6

### ISSUE THREAD

**Issue by Pixmap** [giampaolo/psutil#1112]
I've tried to run tests, but I had such error.
I've tried on Mac 10.11.6 with python 2.7.13 and 3.6.2, but there were no difference.
Any ideas how to fix it?

```
$ make test
/Applications/Xcode6.2.app/Contents/Developer/usr/bin/make install
/Applications/Xcode6.2.app/Contents/Developer/usr/bin/make build
# make sure setuptools is installed (needed for 'develop' / edit mode)
python -c "import setuptools"
PYTHONWARNINGS=all python setup.py build
running build
running build_py
running build_ext
PYTHONWARNINGS=all python setup.py build_ext -i
running build_ext
copying build/lib.macosx-10.6-intel-2.7/psutil/_psutil_osx.so -> psutil
copying build/lib.macosx-10.6-intel-2.7/psutil/_psutil_posix.so -> psutil
rm -rf tmp
python -c "import psutil"  # make sure it actually worked
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "psutil/__init__.py", line 147, in <module>
    from . import _psosx as _psplatform
  File "psutil/_psosx.py", line 18, in <module>
    from ._common import AF_INET6
ImportError: cannot import name AF_INET6
make[2]: *** [build] Error 1
make[1]: *** [install] Error 2
make: *** [test] Error 2
```
```
$ make test PYTHON=python3.6
/Applications/Xcode6.2.app/Contents/Developer/usr/bin/make install
/Applications/Xcode6.2.app/Contents/Developer/usr/bin/make build
# make sure setuptools is installed (needed for 'develop' / edit mode)
python3.6 -c "import setuptools"
PYTHONWARNINGS=all python3.6 setup.py build
running build
running build_py
running build_ext
PYTHONWARNINGS=all python3.6 setup.py build_ext -i
running build_ext
copying build/lib.macosx-10.6-intel-3.6/psutil/_psutil_osx.cpython-36m-darwin.so -> psutil
copying build/lib.macosx-10.6-intel-3.6/psutil/_psutil_posix.cpython-36m-darwin.so -> psutil
rm -rf tmp
python3.6 -c "import psutil"  # make sure it actually worked
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/sergey/Work/TestPS/psutil/psutil/__init__.py", line 147, in <module>
    from . import _psosx as _psplatform
  File "/Users/sergey/Work/TestPS/psutil/psutil/_psosx.py", line 18, in <module>
    from ._common import AF_INET6
ImportError: cannot import name 'AF_INET6'
make[2]: *** [build] Error 1
make[1]: *** [install] Error 2
make: *** [test] Error 2
```

**Comment by giampaolo** [comment]
What psutil version is this?

**Comment by Pixmap** [comment]
I can't say which exactly version it was right now, but I think it was latest.
I've just clone it git clone git@github.com:giampaolo/psutil.git

**Comment by giampaolo** [comment]
It turns out this was in development branch. It's fixed now.
