### ISSUE TITLE
IOError: [Errno 24] Too many open files: '/proc/net/dev'

### ISSUE THREAD

**Issue by mrwunderbar666** [giampaolo/psutil#1117]
I am using psutil to monitor my network and cpu usage over a longer period of time.
After a few hours, the python scripts stops and I'll get this error message:

```
Traceback (most recent call last):

  File "mcp4922_vumonitor.py", line 153, in <module>
  File "mcp4922_vumonitor.py", line 126, in main
  File "mcp4922_vumonitor.py", line 111, in poll
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 2087, in net_io_counters
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 934, in net_io_counters
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 204, in open_text

IOError: [Errno 24] Too many open files: '/proc/net/dev'

```

What steps will reproduce the problem?  
1. long term network activity polling (code sample below)

What version of psutil are you using? What Python version?  
Python 2.7.9 ,  5.2.2

On what operating system? Is it 32bit or 64bit version?  
Raspbian GNU/Linux 8 (jessie)

Example Code:
```
import atexit
import time
import sys
import psutil

net_max = 15000000

def net_coeffiecient(bytes_received_after, bytes_received_before, bytes_send_after, bytes_send_before):
    net_current = ((bytes_received_after - bytes_received_before) + ( bytes_send_after - bytes_send_before))
    #print (net_current)
    x = (net_current / net_max) * 100
    #print("Current Network usage in percent is: {}" .format(x))
    if x > 100:
        return 100
    elif x < 0:
        return 0
    else:
        return x
    return x

def poll(interval):
    """Retrieve raw stats within an interval window."""
    net_before = psutil.net_io_counters()    
    # psutil.cpu_percent() includes a sleep for 1 second (interval)
    cpu_usage = psutil.cpu_percent(interval)
    net_after = psutil.net_io_counters()    
    net_usage = net_coeffiecient(net_after.bytes_recv, net_before.bytes_recv, net_after.bytes_sent, net_before.bytes_sent)
    return net_usage, cpu_usage

def main():
    """ Starting by defining some variables """
    try:
        interval = 0
        while True:
            net_poll, cpu_poll = poll(interval)
            interval = 1
            print(net_poll)
            print(cpu_poll
    except (KeyboardInterrupt, SystemExit):
        """ Cleaning Up """
        sys.exit(0)

if __name__ == '__main__':
    main()
```

**Comment by mrwunderbar666** [comment]
False issue.
I found the problem:

It was another library that caused the Error, it opened too many files.

So issue can be closed
