### ISSUE TITLE
RecursionError after exception in the psutil.Popen.__init__()

### ISSUE THREAD

**Issue by Cykooz** [giampaolo/psutil#1121]
Look at this code from constructor of psutil.Popen:
https://github.com/giampaolo/psutil/blob/fe0799f98e04b980c3f9aee0dd577567eb932e0b/psutil/__init__.py#L1384

If it raises exception, then `self.__subproc` will be absent in the instance of `psutil.Popen`. In this case follow code will causes an exception `RecursionError`.

https://github.com/giampaolo/psutil/blob/fe0799f98e04b980c3f9aee0dd577567eb932e0b/psutil/__init__.py#L1416

This bug can be fixed very simple - you will need to add a default value of __subproc at class level:

```python
class Popen(Process):
    __subproc = None

    def __init__(self, *args, **kwargs):
        self.__subproc = subprocess.Popen(*args, **kwargs)
        self._init(self.__subproc.pid, _ignore_nsp=True)
```

**Comment by giampaolo** [comment]
How can I reproduce this?

**Comment by Cykooz** [comment]
```python
from raven.base import DummyClient
import psutil

client = DummyClient()
client.is_enabled = lambda: True

try:
    proc = psutil.Popen('program_not_found')
except Exception as e:
    client.captureException()
```

**Comment by giampaolo** [comment]
Can't reproduce it. I get:

```
Traceback (most recent call last):
  File "foo.py", line 6, in <module>
    proc = psutil.Popen('program_not_found')
  File "/home/giampaolo/svn/psutil/psutil/__init__.py", line 1384, in __init__
    self.__subproc = subprocess.Popen(*args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by Cykooz** [comment]
I uses Python 3.6. Maybe the error only appears in Python 3.

**Comment by giampaolo** [comment]
I can't reproduce it. Please show me the full traceback. Actually can you do that (reproduce the issue) from the interactive python shell itself and paste the output?

**Comment by Cykooz** [comment]
https://gist.github.com/Cykooz/5a5a7d1c3d78017fcefb6769fde811b1

**Comment by giampaolo** [comment]
There's something weird. Before RecursionError I see `'Popen' object has no attribute '_pid'` but the traceback is truncated (perhaps due to `client.captureException()`?). Please just do:

```
>>> import psutil
>>> psutil.Popen('program_not_found')
```

Do you get an error like that?

**Comment by Cykooz** [comment]
The whole point is in using `raven` (it is a client for Sentry). Without it, the `RecursionError` error does not occur, because default `traceback` from Python does not look at the contents of objects inside the frame with an error.

**Comment by giampaolo** [comment]
So it does **not** occur if you remove `client.captureException()`?

**Comment by Cykooz** [comment]
Traceback is not truncated-it ends with RecursionError, because `raven` tries to get some information about the` Popen` instance (it calls method `repr()` for it), in which an exception occurs.

**Comment by Cykooz** [comment]
Yes, error does not occur if used default Python `traceback`.

**Comment by giampaolo** [comment]
If you define `__subproc` as a class attribute what error do you get? Can you see `AttributeError: 'Popen' object has no attribute '_pid'`? Actually I'm more interested in understanding where **that** comes from rather than RecursionError.

**Comment by Cykooz** [comment]
- `raven` gets Popen instance as `self` variable from code frame of `Popen.__init__()` .
- Next, `raven` calls something like `str(variable)`. This leads to calling this code: 

https://github.com/giampaolo/psutil/blob/fe0799f98e04b980c3f9aee0dd577567eb932e0b/psutil/__init__.py#L441-L454

- `pid = self.pid` leads to calling this code:
https://github.com/giampaolo/psutil/blob/fe0799f98e04b980c3f9aee0dd577567eb932e0b/psutil/__init__.py#L1411-L1419
- The first exception that will occur here is `AttributeError: 'Popen' object has no attribute '_pid'`
- Then the code `return object.__getattribute__(self.__subproc, name)` will be called. This again causes the call to `Popen .__ getattribute __ ()` but already in order to get the `__subproc`.

**Comment by giampaolo** [comment]
OK, good. What traceback do you get by defining `__subproc` as a class attribute?

**Comment by Cykooz** [comment]
https://gist.github.com/Cykooz/72ffb05e65112c06ea9b7e718d0d387f

As you can see, in this case python-shell did not fall and did not exit to the console.

**Comment by giampaolo** [comment]
Mmmm... probably better but still incorrect as the right exception should be `
FileNotFoundError` not `AttributeError`. I assume raven is doing something wrong here. I am tempted to assume it's raven bug, not psutil's.

**Comment by Cykooz** [comment]
Exception `FileNotFoundError` located at the start of the traceback. All other exception occur because `raven` calls `return repr(value)`, where `value` is instance of `Popen`. These exceptions do not matter, `raven` handles them correctly. As a result, `raven` will not be able to get information about the `Popen` instance, but this is not critical, because the instance has no useful information.

**Comment by Cykooz** [comment]
This is not bug of `raven`. `raven` only calls `repr(value)`, where `value` is instance of Popen. This results in the whole process of the python falling with the error `RecursionError`.

Your code expects that a `Popen` instance (or the `Popen` class itself) must contain the `__subproc` variable. But if you have an error in the constructor of `Popen`, then the instance is created without this variable. Therefore, further access to this instance results in a fatal error `RecursionError`.

**Comment by giampaolo** [comment]
I don't understand how can raven call `repr` against the `Popen` instance since the error occurs when you try to instantiate the instance (hence there's no real "instance" at that point). How did you figure out it's raven calling repr()? I see no `repr` reference in the traceback you pasted. Are you able to identify where in the raven code this is done?

**Comment by Cykooz** [comment]
In Python, instance is created by `__new__` method of class, not by `__init__` method. Therefore, instance already exists when exception occur in `__init__` method.

You can see `repr` at the end of the last traceback.
```
Traceback (most recent call last):
  File "/home/cykooz/buildout-eggs/raven-6.1.0-py2.py3-none-any.ovo/raven/utils/serializer/manager.py", line 76, in transform
    return repr(value)
  File "/home/cykooz/buildout-eggs/psutil-5.2.2-py3.6-linux-x86_64.egg/psutil/__init__.py", line 446, in __repr__
    return "<%s at %s>" % (self.__str__(), id(self))
  File "/home/cykooz/buildout-eggs/psutil-5.2.2-py3.6-linux-x86_64.egg/psutil/__init__.py", line 432, in __str__
    pid = self.pid
  File "/home/cykooz/buildout-eggs/psutil-5.2.2-py3.6-linux-x86_64.egg/psutil/__init__.py", line 1405, in __getattribute__
    % (self.__class__.__name__, name))
AttributeError: Popen instance has no attribute 'pid'
'83a1e04e00654a99800c2e9b25f0eccc'
```

**Comment by Cykooz** [comment]
Ok, you may fix it by other way - by correct of getting `self.__subproc` in the `Popen.__getattribute__()`.

```python
    def __getattribute__(self, name):
        try:
            return object.__getattribute__(self, name)
        except AttributeError:
            try:
                subproc = object.__getattribute__(self, '__subproc')
                return object.__getattribute__(subproc, name)
            except AttributeError:
                raise AttributeError("%s instance has no attribute '%s'"
                                     % (self.__class__.__name__, name))
```

**Comment by Cykooz** [comment]
Or you could use `__getattr__()` instead of `__getattribute__()`:
```python
    def __getattr__(self, name):
        subproc = object.__getattribute__(self, '__subproc')
        return getattr(subproc, name)
```

**Comment by Cykooz** [comment]
Using access to the attributes of an instance through a dot (like `self.__subproc`) inside of `__getattribute__() ` or `__getattr__()` methods is not a very good way.

**Comment by Cykooz** [comment]
Small fix for my last code example:
```python
    def __getattr__(self, name):
        subproc = object.__getattribute__(self, '_Popen__subproc')
        return getattr(subproc, name)
```
An identifier of class-private member is textually replaced with `_classname__varname` (https://docs.python.org/3/tutorial/classes.html#private-variables)
