### ISSUE TITLE
cpu_affinity() may raise OSError(EINVAL) on Linux

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#1140]
https://travis-ci.org/giampaolo/psutil/jobs/280295317

```
======================================================================
ERROR: psutil.tests.test_process.TestProcess.test_cpu_affinity
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/giampaolo/psutil/psutil/tests/test_process.py", line 874, in test_cpu_affinity
    p.cpu_affinity([n])
  File "/home/travis/build/giampaolo/psutil/psutil/__init__.py", line 871, in cpu_affinity
    self._proc.cpu_affinity_set(list(set(cpus)))
  File "/home/travis/build/giampaolo/psutil/psutil/_pslinux.py", line 1365, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/travis/build/giampaolo/psutil/psutil/_pslinux.py", line 1773, in cpu_affinity_set
    cext.proc_cpu_affinity_set(self.pid, cpus)
OSError: [Errno 22] Invalid argument
```

**Comment by giampaolo** [comment]
Closing as duplicated of #1126.
