### ISSUE TITLE
make test is broken on Windows

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#1172]
Same for `python -m psutil.tests`.

```
$ make test
...
cmd: C:\Python27\python.exe -Wa psutil\tests\__main__.py
Traceback (most recent call last):
  File "psutil\tests\__main__.py", line 96, in <module>
    main()
  File "psutil\tests\__main__.py", line 93, in main
    run_suite()
  File "c:\users\user\desktop\psutil\psutil\tests\__init__.py", line 773, in run_suite
    _setup_tests()
  File "c:\users\user\desktop\psutil\psutil\tests\__init__.py", line 757, in _setup_tests
    assert psutil._psplatform.cext.py_psutil_testing()
AssertionError
```

**Comment by giampaolo** [comment]
Fixed in https://github.com/giampaolo/psutil/commit/0662915f58949a4084f9fb0c278d143708cf3ede
