### ISSUE TITLE
psutil only returns uids of user-owned process on Solaris 10

### ISSUE THREAD

**Issue by gsauthof** [giampaolo/psutil#1193]
How to reproduce:

As normal user, chose a PID of another user:

    >>> p = psutil.Process(12345)
    >>> p.uids()
    Traceback (most recent call last):
      File "/path/to/venv/lib/python3.5/site-packages/psutil/_pssunos.py", line 346, in wrapper
        return fun(self, *args, **kwargs)
      File "/path/to/venv/lib/python3.5/site-packages/psutil/_pssunos.py", line 477, in uids
        real, effective, saved, _, _, _ = self._proc_cred()
      File "/path/to/venv/lib/python3.5/site-packages/psutil/_common.py", line 336, in wrapper
        return fun(self)
      File "/path/to/venv/lib/python3.5/site-packages/psutil/_pssunos.py", line 400, in _proc_cred
        return cext.proc_cred(self.pid, self._procfs_path)
    PermissionError: [Errno 13] Permission denied: '/proc/12345/cred'
     
    During handling of the above exception, another exception occurred:
     
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/path/to/venv/lib/python3.5/site-packages/psutil/_common.py", line 336, in wrapper
        return fun(self)
      File "/path/to/venv/lib/python3.5/site-packages/psutil/__init__.py", line 768, in uids
        return self._proc.uids()
      File "/path/to/venv/lib/python3.5/site-packages/psutil/_pssunos.py", line 362, in wrapper
        raise AccessDenied(self.pid, self._name)
    psutil.AccessDenied: psutil.AccessDenied (pid=12345)

The thing is that psutil tries to read the uids from `/proc/$pid/cred` that is always only user-readable on Solaris 10:

    $ ls /proc/12345/cred -l
    -r-------- 1 juser juser 52 2017-11-23 11:27 /proc/12345/cred

A better choice on Solaris 10 is to use `/proc/$pid/psinfo` since it [also contains the uids](https://docs.oracle.com/cd/E19253-01/816-5174/proc-4/index.html) (modulo the saved user id) - and is readable by everyone. Thus, if psutil really cares about the saved user id, it could also try `/proc/$pid/cred` first and then fall back to `/proc/$pid/psinfo`.

For our example:

    $ ls /proc/12345/psinfo -l
    -r--r--r-- 1 juser juser 336 2017-11-23 11:27 /proc/12345/psinfo

**Comment by giampaolo** [comment]
Can you provide a PR?
