### ISSUE TITLE
OSX: memory_maps() may raise EINVAL for zombie process

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#1209]
https://travis-ci.org/giampaolo/psutil/jobs/327852918

```
======================================================================
ERROR: psutil.tests.test_process.TestProcess.test_zombie_process
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/build/giampaolo/psutil/psutil/tests/test_process.py", line 1286, in test_zombie_process
    zproc.as_dict()
  File "/Users/travis/build/giampaolo/psutil/psutil/__init__.py", line 528, in as_dict
    ret = meth()
  File "/Users/travis/build/giampaolo/psutil/psutil/__init__.py", line 1113, in memory_maps
    it = self._proc.memory_maps()
  File "/Users/travis/build/giampaolo/psutil/psutil/_psosx.py", line 330, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/travis/build/giampaolo/psutil/psutil/_psosx.py", line 571, in memory_maps
    return cext.proc_memory_maps(self.pid)
OSError: [Errno 22] Invalid argument
```

Curiously not on Python 2 for some reason.

**Comment by giampaolo** [comment]
Reopening as per #1291.

**Comment by giampaolo** [comment]
Closing this out. Will continue in #1291 since it has more information.
