### ISSUE TITLE
psutil compatibility with linux subsystem for windows

### ISSUE THREAD

**Issue by hopp** [giampaolo/psutil#1218]
Running glances on ubuntu in linux subsystem for windows I get several errors.
Apparently there is no `/proc/vmstat`, no `/etc/mtab`.

glances is using psutil

```
~⟫ glances
/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py:515: RuntimeWarning: 'sin' and 'sout' swap memory stats couldn't be determined and were set to 0 ([Errno 2] No such file or directory: '/proc/vmstat')
  warnings.warn(msg, RuntimeWarning)
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.10', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 134, in main
    start(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 100, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 69, in __init__
    self.stats.update()
  File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 192, in update
    self._plugins[p].update()
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 882, in wrapper
    ret = fct(self, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 891, in wrapper
    ret = fct(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_fs.py", line 106, in update
    fs_stat = psutil.disk_partitions(all=False)
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 1979, in disk_partitions
    return _psplatform.disk_partitions(all)
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 1102, in disk_partitions
    partitions = cext.disk_partitions()
OSError: [Errno 2] No such file or directory: '/etc/mtab'
```
Installed psutil version
```
~⟫ pip show psutil
Name: psutil
Version: 5.4.3
Summary: Cross-platform lib for process and system monitoring in Python.
Home-page: https://github.com/giampaolo/psutil
Author: Giampaolo Rodola
Author-email: g.rodola@gmail.com
License: BSD
Location: /usr/local/lib/python2.7/dist-packages
Requires:
```
Installed glances version
```
~⟫ glances -V
Glances v2.10 with psutil v5.4.3
```

**Comment by giampaolo** [comment]
Sorry for the delay.

> Running glances on ubuntu in linux subsystem for windows I get several errors.

What kind of platform is that?

**Comment by hopp** [comment]
From late 2017 you are able to install linux directly on Windows 10 machine
(https://docs.microsoft.com/en-us/windows/wsl/install-win10)

The distro could be one apparently one of these:
>Ubuntu
>OpenSUSE
>SLES
>Kali Linux
>Debian GNU/Linux

I've got Ubuntu.

```
~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
~$ uname -a
Linux [my pc name] 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
```
I'm sorry I don't understand your question regarding platform 😅 .
Is there any command I could run to help you investigate ?

**Comment by giampaolo** [comment]
I've never played with that configuration so it's likely psutil won't work. I would welcome adding support for it though (PRs are welcome =)).

**Comment by giampaolo** [comment]
I opened a ticket for this: https://github.com/giampaolo/psutil/issues/1251

**Comment by hopp** [comment]
Thanks !
Sadly I'm not familiar with Python :(.
Right now it's not a big issue for me, so I'll wait for that ticket :)
