### ISSUE TITLE
Can't find '/sys/class/hwmon/hwmon1/device/name'

### ISSUE THREAD

**Issue by DariaD** [giampaolo/psutil#1245]
Good morning, 

I was using an utility which refer to psutil and suddenly got:
IOError: [Errno 2] No such file or directory: '/sys/class/hwmon/hwmon1/device/name'

I'm not sure what exactly going on and if it's really a psutil problem.
Really appreciate any help!
```
>>> import psutil
>>> psutil.sensors_temperatures()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/psutil/__init__.py", line 2195, in sensors_temperatures
    rawdict = _psplatform.sensors_temperatures()
  File "/usr/lib64/python2.7/site-packages/psutil/_pslinux.py", line 1154, in sensors_temperatures
    binary=False)
  File "/usr/lib64/python2.7/site-packages/psutil/_pslinux.py", line 295, in cat
    with open_binary(fname) if binary else open_text(fname) as f:
  File "/usr/lib64/python2.7/site-packages/psutil/_pslinux.py", line 201, in open_text
    return open(fname, "rt", **kwargs)
IOError: [Errno 2] No such file or directory: '/sys/class/hwmon/hwmon1/device/name'
```

I use Python 2 if it's mater.

**Comment by DariaD** [comment]
Also, use CentOS.

**Comment by DariaD** [comment]
Also, I use CentOS.

**Comment by giampaolo** [comment]
Can you please paste the output of `sensors` command? Not sure about CentOS but on Ubuntu you install it with `sudo apt install lm-sensors`.

**Comment by DariaD** [comment]
Dear Giampaolo,
thank you for your reply. 

I've got this:

```
i350bb-pci-0403
Adapter: PCI adapter
loc1:         +54.0°C  (high = +120.0°C, crit = +110.0°C)

power_meter-acpi-0
Adapter: ACPI interface
power1:        0.00 W  (interval = 300.00 s)

coretemp-isa-0000
Adapter: ISA adapter
Physical id 0:  +48.0°C  (high = +86.0°C, crit = +96.0°C)
Core 0:         +40.0°C  (high = +86.0°C, crit = +96.0°C)
Core 1:         +41.0°C  (high = +86.0°C, crit = +96.0°C)
Core 2:         +41.0°C  (high = +86.0°C, crit = +96.0°C)
Core 3:         +46.0°C  (high = +86.0°C, crit = +96.0°C)
Core 4:         +43.0°C  (high = +86.0°C, crit = +96.0°C)
Core 5:         +41.0°C  (high = +86.0°C, crit = +96.0°C)
Core 8:         +40.0°C  (high = +86.0°C, crit = +96.0°C)
Core 9:         +41.0°C  (high = +86.0°C, crit = +96.0°C)
Core 10:        +40.0°C  (high = +86.0°C, crit = +96.0°C)
Core 11:        +41.0°C  (high = +86.0°C, crit = +96.0°C)
Core 12:        +42.0°C  (high = +86.0°C, crit = +96.0°C)
Core 13:        +42.0°C  (high = +86.0°C, crit = +96.0°C)

coretemp-isa-0001
Adapter: ISA adapter
Physical id 1:  +76.0°C  (high = +86.0°C, crit = +96.0°C)
Core 0:         +72.0°C  (high = +86.0°C, crit = +96.0°C)
Core 1:         +72.0°C  (high = +86.0°C, crit = +96.0°C)
Core 2:         +72.0°C  (high = +86.0°C, crit = +96.0°C)
Core 3:         +70.0°C  (high = +86.0°C, crit = +96.0°C)
Core 4:         +71.0°C  (high = +86.0°C, crit = +96.0°C)
Core 5:         +70.0°C  (high = +86.0°C, crit = +96.0°C)
Core 8:         +72.0°C  (high = +86.0°C, crit = +96.0°C)
Core 9:         +71.0°C  (high = +86.0°C, crit = +96.0°C)
Core 10:        +70.0°C  (high = +86.0°C, crit = +96.0°C)
Core 11:        +71.0°C  (high = +86.0°C, crit = +96.0°C)
Core 12:        +67.0°C  (high = +86.0°C, crit = +96.0°C)
Core 13:        +68.0°C  (high = +86.0°C, crit = +96.0°C)

```

**Comment by giampaolo** [comment]
Can you please try to install latest GIT version of psutil and then run this script and paste the output?
https://github.com/giampaolo/psutil/blob/master/scripts/sensors.py

**Comment by DariaD** [comment]
P.S. for CentOS:
```
$ yum install lm_sensors
```

**Comment by DariaD** [comment]
Giampaolo,
The output is:
```
/usr/lib64/python2.7/site-packages/psutil-5.4.4-py2.7-linux-x86_64.egg/psutil/_pslinux.py:1153: RuntimeWarning: ignoring IOError(2, 'No such file or directory')
  warnings.warn("ignoring %r" % err, RuntimeWarning)
i350bb
    Temperatures:
        loc1                 54.0°C (high=120.0°C, critical=110.0°C)
coretemp
    Temperatures:
        Physical id 0        49.0°C (high=86.0°C, critical=96.0°C)
        Core 8               42.0°C (high=86.0°C, critical=96.0°C)
        Core 9               41.0°C (high=86.0°C, critical=96.0°C)
        Core 10              41.0°C (high=86.0°C, critical=96.0°C)
        Core 11              41.0°C (high=86.0°C, critical=96.0°C)
        Core 12              42.0°C (high=86.0°C, critical=96.0°C)
        Core 13              42.0°C (high=86.0°C, critical=96.0°C)
        Core 0               41.0°C (high=86.0°C, critical=96.0°C)
        Core 1               42.0°C (high=86.0°C, critical=96.0°C)
        Core 2               41.0°C (high=86.0°C, critical=96.0°C)
        Core 3               46.0°C (high=86.0°C, critical=96.0°C)
        Core 4               45.0°C (high=86.0°C, critical=96.0°C)
        Core 5               43.0°C (high=86.0°C, critical=96.0°C)
        Physical id 1        78.0°C (high=86.0°C, critical=96.0°C)
        Core 8               73.0°C (high=86.0°C, critical=96.0°C)
        Core 9               72.0°C (high=86.0°C, critical=96.0°C)
        Core 10              71.0°C (high=86.0°C, critical=96.0°C)
        Core 11              72.0°C (high=86.0°C, critical=96.0°C)
        Core 12              68.0°C (high=86.0°C, critical=96.0°C)
        Core 13              70.0°C (high=86.0°C, critical=96.0°C)
        Core 0               73.0°C (high=86.0°C, critical=96.0°C)
        Core 1               77.0°C (high=86.0°C, critical=96.0°C)
        Core 2               73.0°C (high=86.0°C, critical=96.0°C)
        Core 3               70.0°C (high=86.0°C, critical=96.0°C)
        Core 4               73.0°C (high=86.0°C, critical=96.0°C)
        Core 5               73.0°C (high=86.0°C, critical=96.0°C)
```

Thank you, now it works although there is a warning. For me it works! Thank you!

**Comment by DariaD** [comment]
Good morning, Giampaolo, 
Got a problem again. Probably it's related to [#1203](https://github.com/giampaolo/psutil/issues/1203).

`/usr/lib64/python2.7/site-packages/psutil-5.4.4-py2.7-linux-x86_64.egg/psutil/_pslinux.py:1153: RuntimeWarning: ignoring IOError(2, 'No such file or directory')
  warnings.warn("ignoring %r" % err, RuntimeWarning)`

And seems like power sensor is not available (or can't be found) but everything worked 2 days ago. 
I will appreciate any help.

Best, Daria
