### ISSUE TITLE
NoSuchProcess: No process found with pid 6396

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#132]
_From [siqis...@gmail.com](https://code.google.com/u/114295271333113127171/) on November 08, 2010 13:55:41_

```
What steps will reproduce the problem?  
1. I wrap the get_process_list() in a sleep loop
2. for process in psutil.get_process_list():
          if process.name.find("notepad") >=0:
              print process.name
                print >> resultFile, "win32", process.get_cpu_percent(), 
process.get_memory_percent()    
3 It throw error at the if process.name.find("notepad") >=0: sentence.

4 The error is 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 530, in __bootstrap_inner
    self.run()
  File "D:\tudworkspace\OpenTTDTesting\src\performance.py", line 15, in run
    pid = measureCPUandMem(resultFile, pid)
  File "D:\tudworkspace\OpenTTDTesting\src\performance.py", line 24, in 
measureCPUandMem
    if process.name.find("notepad") >=0:
  File "C:\Python27\lib\site-packages\psutil\__init__.py", line 205, in name
    self.deproxy()
  File "C:\Python27\lib\site-packages\psutil\__init__.py", line 180, in deproxy
    self._procinfo = 
ProcessInfo(*_platform_impl.get_process_info(self._procinfo.pid))
  File "C:\Python27\lib\site-packages\psutil\_psmswindows.py", line 66, in wrapper
    return callable(*args, **kwargs)
  File "C:\Python27\lib\site-packages\psutil\_psmswindows.py", line 81, in 
get_process_info
    infoTuple = _psutil_mswindows.get_process_info(pid)
NoSuchProcess: No process found with pid 6396 

What is the expected output?  


What do you see instead?  
I expected it doesn't throws any error. 

What version of psutil are you using? What Python version?  
Python 2.7. I use the psutil-python2.7 windows installer. 

On what operating system? Is it 32bit or 64bit version?  
I use 32 bit win 7 profession 

Please provide any additional information below.  
import os,sys,time,threading,psutil
from threading import Timer


class Performance(threading.Thread):
    def __init__(self):
        threading.Thread.__init__(self)
        self.flag = 1
    def run(self):
        filename = os.path.join(".." ,"test_result", "cpumem")
        resultFile = open(filename,"a")
        measureNetwork()
        pid = 0
        while(self.flag == 1):
            pid = measureCPUandMem(resultFile, pid)
            time.sleep(0.4)


def measureCPUandMem(resultFile, pid):
    print >> resultFile, "-----------" + time.asctime() + "\n" + 
"&#37;f"&#37;time.time()
    process = psutil.Process(pid) 
    if sys.platform == "win32":
         for process in psutil.get_process_list():
            if process.name.find("notepad") >=0:
                print process.name
                print >> resultFile, "win32", process.get_cpu_percent(), 
process.get_memory_percent()    
                print "win32", process.get_cpu_percent(), 
process.get_cpu_times(), process.get_memory_percent()

    elif sys.platform.find("linux") >=0:
        file = os.popen("ps aux|grep openttd")
        lines = file.readlines()
        for line in lines:
            print >> resultFile, line
    print >> resultFile, "-----------\n"
    resultFile.flush()
    return pid

def networkWork():
    if sys.platform == "win32":
        file = os.popen("ps aux -W")
        lines = file.readlines()
        for line in lines:
            if line.find("C:\\\"Program Files\"\\Wireshark\\tshark") >=0:
                return 
        os.system("C:\\\"Program Files\"\\Wireshark\\tshark -b filesize:1000000 
-f ip -q -w ..\\test_result\\packages")
    else:
        file = os.popen("ps aux|grep tshak")
        lines = file.readlines()
        if(len(lines) >=2):
            return 
        os.system("tshark -b filesize:1000000 -f ip -q -w 
../test_result/packages &")

def measureNetwork():
    t = threading.Thread(None, networkWork)
    t.start()


if __name__ == "__main__":
  abc = Performance()
  abc.start()
#    while True:
#        for process in psutil.get_process_list():
#            if process.name.find("notepad") >=0:
#                print process.name
#                print "win32", process.get_cpu_percent(), 
process.get_cpu_times(), process.get_memory_percent()
#        time.sleep(0.5)
```

_Original issue: http://code.google.com/p/psutil/issues/detail?id=132_

**Comment by saadli** [comment]
ps aux | grep airflow
kill all airflow processes and restart with :
airflow webserver
airflow scheduler
