### ISSUE TITLE
[Linux/Android] Handle case when no access to /proc/stats

### ISSUE THREAD

**Issue by alxchk** [giampaolo/psutil#1334]
Android Oreo prohibited access to some info from proc. Likely it's worth to handle such cases without explicit exceptions.

![Python2, Android Oreo, Termux](https://user-images.githubusercontent.com/329535/45377206-96bda180-b602-11e8-8b25-c3683b09433c.jpg)

**Comment by giampaolo** [comment]
Unfortunately there is nothing that psutil can do about it. Raising `AccessDenied` is the right way to handle this situation.

**Comment by alxchk** [comment]
But it's not raising AccessDenied. It's printing that exception using traceback in global exception handler. My suggestion is to silently ignore AccessDenied.

https://github.com/giampaolo/psutil/blob/master/psutil/_pslinux.py#L332

**Comment by giampaolo** [comment]
I find it hard to understand the traceback from my phone. Please paste the error as pure text.

**Comment by alxchk** [comment]
```
>>> import psutil
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/psutil/_pslinux.py", line 329, in <module>
    set_scputimes_ntuple("/proc")
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/psutil/_common.py", line 299, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/psutil/_pslinux.py", line 296, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/psutil/_pslinux.py", line 205, in open_binary
    return open(fname, "rb", **kwargs)
IOError: [Errno 13] Permission denied: '/proc/stat'
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/psutil/__init__.py", line 1608, in <module>
    _last_cpu_times = cpu_times()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/psutil/__init__.py", line 1602, in cpu_times
    return _psplatform.cpu_times()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/psutil/_pslinux.py", line 582, in cpu_times
    set_scputimes_ntuple(procfs_path)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/psutil/_common.py", line 299, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/psutil/_pslinux.py", line 296, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/psutil/_pslinux.py", line 205, in open_binary
    return open(fname, "rb", **kwargs)
IOError: [Errno 13] Permission denied: '/proc/stat'
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/psutil/__init__.py", line 1615, in <module>
    _last_per_cpu_times = cpu_times(percpu=True)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/psutil/__init__.py", line 1604, in cpu_times
    return _psplatform.per_cpu_times()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/psutil/_pslinux.py", line 595, in per_cpu_times
    set_scputimes_ntuple(procfs_path)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/psutil/_common.py", line 299, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/psutil/_pslinux.py", line 296, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/psutil/_pslinux.py", line 205, in open_binary
    return open(fname, "rb", **kwargs)
IOError: [Errno 13] Permission denied: '/proc/stat'
>>>
```

**Comment by giampaolo** [comment]
I suppressed the message suppressed occurring at import time in 2e220c8ae1b69299eb07bcbd419cf2f59837853d. As such the exception will actually occur (and bubble up) on the first call to `cpu_times()` or `cpu_percent()` functions. Closing as fixed.

**Comment by z8512** [comment]
`Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_common.py", line 397, in wrapper
    return cache[key]
KeyError: (('/proc',), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_pslinux.py", line 303, in <module>
    set_scputimes_ntuple("/proc")
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_common.py", line 399, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_pslinux.py", line 270, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_common.py", line 711, in open_binary
    return open(fname, "rb", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/stat'`

But why?

**Comment by chapmanjacobd** [comment]
I also experience this often in my own program. I'm not sure which library I'm using is calling psutil but I also don't expect the many downstream library maintainers to each handle Android as a special case in every place that they use psutil


```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_common.py", line 398, in wrapper
    return cache[key]
KeyError: (('/proc',), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_pslinux.py", line 285, in <module>
    set_scputimes_ntuple("/proc")
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_common.py", line 400, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_pslinux.py", line 268, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_common.py", line 727, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
PermissionError: [Errno 13] Permission denied: '/proc/stat'
```

**Comment by giampaolo** [comment]
"PermissionError: [Errno 13] Permission denied: '/proc/stat'"

Note that this happens on `import psutil` (which is bad) but don't crash the app: the exception is just printed.
Still, it's weird that Android doesn't allow reading something as basic as /proc/stat. 
As previously said, there is likely nothing psutil can do about it.

**Comment by chapmanjacobd** [comment]
```py
try:
    read_proc_stat
except PermissionError as e:
    is_android = any([k in os.environ for k in ['ANDROID_STORAGE']])
    if is_android:
        pass  # expected on this platform
    else:
        raise e
```

**Comment by elmustafaa** [comment]
comment fieds witch contain raise

**Comment by phanirithvij** [comment]
> "PermissionError: [Errno 13] Permission denied: '/proc/stat'"
> 
> Note that this happens on `import psutil` (which is bad) but don't crash the app: the exception is just printed. Still, it's weird that Android doesn't allow reading something as basic as /proc/stat. As previously said, there is likely nothing psutil can do about it.

@giampaolo so can the traceback be not printed for this too? https://github.com/giampaolo/psutil/blob/49aba759744c06fb3a6fa998155428520f161734/psutil/_pslinux.py#L288
