### ISSUE TITLE
NotImplementedError "kernel too old?" running debian 9.5 (kernel 4.14) via Chrome OS Linux 

### ISSUE THREAD

**Issue by jmeppley** [giampaolo/psutil#1340]
I'm testing out the new linux VM on my chromebook and I'm getting an error from psutil:

```
Python 2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> pid=674
>>> import psutil
>>> psutil.__version__
'5.4.7'
>>> proc = psutil.Process(674)
>>> ioinfo = proc.io_counters()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 750, in io_counters
    return self._proc.io_counters()
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 1619, in io_counters
    "too old?)" % self.pid)
NotImplementedError: couldn't find /proc/674/io (kernel too old?)
```

As far as I can tell, the chrome OS linux terminal drops you into a Debian 9.5 VM. I installed psutil using `sudo pip` after installing gcc and python-dev with apt-get.

```
jmeppley@penguin:~$ cat /etc/debian_version 
9.5
jmeppley@penguin:~$ uname -r
4.14.65-05969-g6f2926628697
```

Is there something weird about working in a VM that I'm missing? 

Thanks!

**Comment by giampaolo** [comment]
That basically means `/proc/{PID}/io` file is missing. There's nothing much psutil can do except that.
