### ISSUE TITLE
top.py script fails on MacOS with Python3

### ISSUE THREAD

**Issue by rahulsh1** [giampaolo/psutil#1386]
Running this with Python `3.6` on MacOS HighSierra. The same works fine with Python `2.7`

    $ ./top.py
    Traceback (most recent call last):
      File "./top.py", line 237, in <module>
        main()
      File "./top.py", line 229, in main
        args = poll(interval)
      File "./top.py", line 123, in poll
        reverse=True)
    TypeError: '<' not supported between instances of 'NoneType' and 'float'

Issue with line:
`processes = sorted(procs, key=lambda p: p.dict['cpu_percent'], reverse=True)`

I see several processes with 'cpu_percent' as None. 
As mentioned before, the same works fine with Python `2.7`

**Comment by aditisrinivas97** [comment]
Did you try running it with superuser privileges?

**Comment by rahulsh1** [comment]
The issue is with that line given above. Running with superuser privileges won't help. As I mentioned, same works on python 2.7

**Comment by aditisrinivas97** [comment]
Hey, did you check how cpu times are obtained on mac os here? My guess is that it needs privileges to obtain these. The script works if you give it privileges and there are no zombie processes present. If you have a zombie process, the cpu_time for it will be None causing it to fail.

**Comment by aditisrinivas97** [comment]
Ah weird, it worked for me! Except it didn't work if there were zombie processes.
