### ISSUE TITLE
num_fds() fails when looped through process.iter().

### ISSUE THREAD

**Issue by PunshiB** [giampaolo/psutil#1407]
I needed total count of open file descriptor so i tried to get by iterating num_fds() through for loop but I get this error. Any idea how to solve it ?

import psutil

for fdescr in psutil.process_iter():
    print(fdescr.num_fds())

Output-

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/psutil/_pslinux.py", line 1510, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/psutil/_pslinux.py", line 2094, in num_fds
    return len(os.listdir("%s/%s/fd" % (self._procfs_path, self.pid)))
PermissionError: [Errno 13] Permission denied: '/proc/1/fd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shyam/PycharmProjects/Python1/daemon_list.py", line 51, in <module>
    print(fdescr.num_fds())
  File "/usr/local/lib/python3.7/site-packages/psutil/__init__.py", line 743, in num_fds
    return self._proc.num_fds()
  File "/usr/local/lib/python3.7/site-packages/psutil/_pslinux.py", line 1513, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil._exceptions.AccessDenied: psutil.AccessDenied (pid=1)

**Comment by giampaolo** [comment]
From the doc:

> Q: Why do I get AccessDenied for certain processes? A: This may happen when you query processess owned by another user, especially on macOS and Windows. Unfortunately there’s not much you can do about this except running the Python process with higher privileges. On Unix you may run the the Python process as root or use the SUID bit (this is the trick used by tools such as ps and netstat). On Windows you may run the Python process as NT AUTHORITY\SYSTEM or install the Python script as a Windows service (this is the trick used by tools such as ProcessHacker).
