### ISSUE TITLE
setup.py test fails during initialisation: No such file or directory: '/sys/class/power_supply'

### ISSUE THREAD

**Issue by jayvdb** [giampaolo/psutil#1414]
on openSUSE bare build machines, `setup.py test` halts during init with error: [Errno 2] No such file or directory: '/sys/class/power_supply'

Can be seen by branching https://build.opensuse.org/package/show/home:jayvdb:pyexcel/python-psutil and removing the hacks in `%check`.

Running `psutil/tests/__main__.py` gives slightly more detail
```
[   14s] + PYTHONPATH=/home/abuild/rpmbuild/BUILDROOT/python-psutil-5.5.1-0.x86_64/usr/lib64/python2.7/site-packages
[   14s] + psutil/tests/__main__.py
[   15s] Traceback (most recent call last):
[   15s]   File "psutil/tests/__main__.py", line 23, in <module>
[   15s]     from psutil.tests import PYTHON_EXE
[   15s]   File "/home/abuild/rpmbuild/BUILDROOT/python-psutil-5.5.1-0.x86_64/usr/lib64/python2.7/site-packages/psutil/tests/__init__.py", line 175, in <module>
[   15s]     HAS_BATTERY = HAS_SENSORS_BATTERY and bool(psutil.sensors_battery())
[   15s]   File "/home/abuild/rpmbuild/BUILDROOT/python-psutil-5.5.1-0.x86_64/usr/lib64/python2.7/site-packages/psutil/__init__.py", line 2360, in sensors_battery
[   15s]     return _psplatform.sensors_battery()
[   15s]   File "/home/abuild/rpmbuild/BUILDROOT/python-psutil-5.5.1-0.x86_64/usr/lib64/python2.7/site-packages/psutil/_pslinux.py", line 1341, in sensors_battery
[   15s]     bats = [x for x in os.listdir(POWER_SUPPLY_PATH) if x.startswith('BAT')]
[   15s] OSError: [Errno 2] No such file or directory: '/sys/class/power_supply'
[   15s] error: Bad exit status from /var/tmp/rpm-tmp.Vc71wT (%check)
```

I was able to bypass it with the following hack
```
sed -i 's/^HAS_SENSORS_BATTERY.*$/HAS_SENSORS_BATTERY = False/' %{buildroot}%{$python_sitearch}/psutil/tests/__init__.py
```

There are other `/sys` also missing and required by other tests, /sys/block, /sys/devices/system/cpu/possible, etc, but these cause failing individual tests rather than failing to start the test suite.

Ideally the tests skip nicely with a warning if /sys is missing, but failing is also ok.

Other workarounds needed to get the build green on a very bare build machine
```sh
# pmap fails on py37 only
sed -i 's/test_\(disk_usage\|sensors\|temperatures\|who\|setup_script\|coverage\|pmap\)/_test_\1/' psutil/tests/test_misc.py

sed -i 's/test_\(wait_non_children\|wait_timeout_0\)/_test_\1/' psutil/tests/test_process.py

sed -i 's/test_\(disk_usage\|users\)/_test_\1/' psutil/tests/test_posix.py

sed -i 's/test_\(cpu_freq\)/_test_\1/' psutil/tests/test_contracts.py

sed -i 's/test_\(cpu_freq\|disk_io_counters\|disk_partitions\|users\)/_test_\1/' psutil/tests/test_system.py

sed -i 's/test_\(cpu_affinity\|emulate_eio_error\|cpu_freq\|disk_partitions_and_usage\|disk_io_counters_sysfs\|cpu_count_.*w_lscpu\|avail_old_missing_zoneinfo\|avail_old_missing_fields\)/_test_\1/' psutil/tests/test_linux.py

sed -i 's/test_\(multi_sockets_procs\)/_test_\1/' psutil/tests/test_connections.py
```

**Comment by jayvdb** [comment]
Many of the errors I see are also reported at https://github.com/giampaolo/psutil/issues/1226

**Comment by giampaolo** [comment]
Fixed, thanks.
