### ISSUE TITLE
cmdline() on Windows may return OSError with no exception set

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#1416]
```
Traceback (most recent call last):
  File "C:\Users\user\Desktop\psutil\psutil\_pswindows.py", line 735, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=True)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

PermissionError: [WinError 5] Access is denied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "foo.py", line 13, in <module>
    print(psutil.Process(96).cmdline())
  File "C:\Users\user\Desktop\psutil\psutil\__init__.py", line 768, in cmdline
    return self._proc.cmdline()
  File "C:\Users\user\Desktop\psutil\psutil\_pswindows.py", line 661, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\user\Desktop\psutil\psutil\_pswindows.py", line 738, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=False)
SystemError: <class 'OSError'> returned a result with an error set
```

**Comment by giampaolo** [comment]
Fixed in c0ba8485d09e8decb64529c743af109ce7cee0a4 (not merged yet).
