### ISSUE TITLE
Process.environ() raise NotImplementedError with 32-bit-WoW processes

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#1419]
This bug has been chasing me for years. It should happen when we try to get the environ of a 32-bit-wow processes from a 64-bit process. 

```
======================================================================
ERROR: psutil.tests.test_windows.RemoteProcessTestCase.test_environ_64
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\user\desktop\psutil\psutil\tests\test_windows.py", line 778, in test_environ_64
    e = p.environ()
  File "c:\users\user\desktop\psutil\psutil\__init__.py", line 939, in environ
    return self._proc.environ()
  File "c:\users\user\desktop\psutil\psutil\_pswindows.py", line 661, in wrapper
    return fun(self, *args, **kwargs)
  File "c:\users\user\desktop\psutil\psutil\_pswindows.py", line 748, in environ
    ustr = cext.proc_environ(self.pid)
NotImplementedError: NtWow64QueryVirtualMemory64 missing
```

Instead of `NotImplementedError` we'll just give up with `AccessDenied`.

**Comment by Meathoook** [comment]
I could get environment variables on Windows Server 2012 (64-bit) when checking environ() on a 64-bit process from python 3.5.3 (32-bit) before this change but now I get the AccessDenied error instead.
Works with psutil version 5.5.1 but not on version 5.6.0 and above.

Can something be done for it to work again or do I have to change to 64-bit python?

**Comment by Meathoook** [comment]
Forgot to mention that I was running python through a command promt with administrator rights which I guess is why it worked before. Tested without administrator rights and got same error as you wrote above.
Is it possible to add a check for that before it goes to AccessDenied?

**Comment by giampaolo** [comment]
To be clear, what did you get before? NotImplementedError or a valid result?

**Comment by Meathoook** [comment]
This is what I get with 5.5.1 (removed some value text)

```
>>> import psutil
>>> psutil.Process(2788).environ()
{'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW', 'COMPUTERNAME': '', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'USERNAME': '', 'USERDOMAIN': '', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'FP_NO_HOST_CHECK': 'NO', 'PROCESSOR_IDENTIFIER': '', 'PSMODULEPATH': 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'APPDATA': 'C:\\Users\\\\AppData\\Roaming', 'TMP': 'C:\\Users\\\\AppData\\Local\\Temp', 'USERDOMAIN_ROAMINGPROFILE': '', 'HOMEDRIVE': 'C:', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'TEMP': 'C:\\Users\\\\AppData\\Local\\Temp', 'PUBLIC': 'C:\\Users\\Public', 'SYSTEMROOT': 'C:\\Windows', 'LOCALAPPDATA': 'C:\\Users\\\\AppData\\Local', 'USERPROFILE': 'C:\\Users\\', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'PROCESSOR_REVISION': '3e04', 'NUMBER_OF_PROCESSORS': '8', 'OS': 'Windows_NT', 'SYSTEMDRIVE': 'C:', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'PROGRAMFILES': 'C:\\Program Files', 'PROMPT': '$P$G', 'PROCESSOR_LEVEL': '6', 'PROGRAMW6432': 'C:\\Program Files', 'HOMEPATH': '\\Users\\', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PROGRAMDATA': 'C:\\ProgramData', 'LOGONSERVER': '\\\\', 'PATH': 'C:\\Program Files (x86)\\Python35-32\\Scripts\\;C:\\Program Files (x86)\\Python35-32\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'WINDIR': 'C:\\Windows'}
```

This is what I get with 5.6.0:

```
>>> import psutil
>>> psutil.Process(2788).environ()
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\psutil\_pswindows.py", line 661, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\psutil\_pswindows.py", line 754, in environ
    ustr = cext.proc_environ(self.pid)
PermissionError: [Errno 13] can't query 64-bit process in 32-bit-WoW mode

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\psutil\__init__.py", line 954, in environ
    return self._proc.environ()
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\psutil\_pswindows.py", line 664, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=2788)
```

Both results are with administrator rights

**Comment by giampaolo** [comment]
The story about that part of the code (which unfortunately I didn't implement) is convoluted. The reason I pre-emptively decided to raise AD is because sometimes that part of the code resulted in EINVAL error.

**Comment by giampaolo** [comment]
Reopening because the error message should include "can't query 64-bit process in 32-bit-WoW mode"

**Comment by Meathoook** [comment]
Executed again without administrator rights with 5.5.1 and got this:

```
>>> import psutil
>>> psutil.Process(2788).environ()
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\psutil\_pswindows.py", line 639, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\psutil\_pswindows.py", line 725, in environ
    ustr = cext.proc_environ(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\psutil\__init__.py", line 939, in environ
    return self._proc.environ()
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\psutil\_pswindows.py", line 642, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=2788)
```

Getting the same error with 5.6.0 but different line numbers. 
Dunno if that is the same error as in this issue if that helps in any way.

**Comment by Meathoook** [comment]
Started the process without administator rights and I could get environ() with 5.5.1 without administartor rights aswell then. Got same answers as what I posted with administartor rights earlier so might not have anything to do with that.

I guess if the code sometimes throw an error there is nothing to do about it.

**Comment by giampaolo** [comment]
Closing this out as I got rid of the `NotImplementedError`s in that part of the code some time ago, and replaced it with `AccessDenied`.
