### ISSUE TITLE
disk_io_counters() is broken on Linux kernel 4.20

### ISSUE THREAD

**Issue by tjbwyk** [giampaolo/psutil#1423]
With system python:
```
$ python
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.__version__
'5.4.8'
>>> psutil.disk_io_counters()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 2026, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 1115, in disk_io_counters
    for entry in gen:
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 1088, in read_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line '   7       0 loop0 206 0 2462 48 0 0 0 0 0 32 56 0 0 0 0\n'
```

With python in pkgsrc:
```
$ /pkg/bin/python2.7
Python 2.7.15 (default, Aug 21 2018, 16:29:39) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.__version__
'5.4.5'
>>> psutil.disk_io_counters()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/pkg/lib/python2.7/site-packages/psutil/__init__.py", line 2017, in disk_io_counters
    rawdict = _psplatform.disk_io_counters()
  File "/pkg/lib/python2.7/site-packages/psutil/_pslinux.py", line 1081, in disk_io_counters
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line '   7       0 loop0 206 0 2462 48 0 0 0 0 0 32 56 0 0 0 0\n'
```

**Comment by giampaolo** [comment]
Already fixed. Upgrade psutil.
