### ISSUE TITLE
FreeBSD: net_connections() raise RuntimeError

### ISSUE THREAD

**Issue by YunLoong** [giampaolo/psutil#1430]
When I use `net_connections` to list all sockets , it will raise the runtimeError. My OS version is `FreeBSD 11.1-RELEASE-p10`.

\>>> import psutil
\>>> psutil.net_connections(kind='inet')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/gpostd_virtualenv/lib/python2.7/site-packages/psutil/__init__.py", line 2121, in net_connections
    return _psplatform.net_connections(kind)
  File "/usr/local/gpostd_virtualenv/lib/python2.7/site-packages/psutil/_psbsd.py", line 382, in net_connections
    rawlist = cext.net_connections()
RuntimeError: struct xtcpcb size mismatch

**Comment by YunLoong** [comment]
Has resolved it by upgrading psutil to version 5.5.1.
