### ISSUE TITLE
[Windows] memory_full_info() crashes

### ISSUE THREAD

**Issue by alxchk** [giampaolo/psutil#1451]
**Platform**
* OS Windows 10.0.17758 N/A Build 17758
* psutil version 4.2 - 5.6

**Bug description**

Crash while trying to access 'memory_full_info' or build dict with as_dict() method.

```
C:\P27>python -m pip install psutil==4.2
Collecting psutil==4.2
  Downloading https://files.pythonhosted.org/packages/c8/e5/5d0a1b2e182e41888fc4e9f4f657f37f126f9fdcd431b592442311c2db98/psutil-4.2.0-cp27-cp27m-win_amd64.whl (167kB)
    100% |UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU| 174kB 1.2MB/s
Installing collected packages: psutil
  Found existing installation: psutil 4.3.0
    Uninstalling psutil-4.3.0:
      Successfully uninstalled psutil-4.3.0
Successfully installed psutil-4.2.0
You are using pip version 18.1, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\P27>python
Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from psutil import process_iter; a = [x.as_dict() for x in process_iter()]
C:\P27>

C:\P27>python -m pip install psutil==4.1
Collecting psutil==4.1
  Downloading https://files.pythonhosted.org/packages/90/97/0a34c0e98bb794f0fc19f0eae13d26fbf39583c768a9a6c614c917135c00/psutil-4.1.0-cp27-cp27m-win_amd64.whl (161kB)
    100% |UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU| 163kB 1.3MB/s
Installing collected packages: psutil
  Found existing installation: psutil 4.2.0
    Uninstalling psutil-4.2.0:
      Successfully uninstalled psutil-4.2.0
Successfully installed psutil-4.1.0
You are using pip version 18.1, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\P27>python
Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from psutil import process_iter; a = [x.as_dict() for x in process_iter()]
>>>
C:\P27>python
Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> print psutil.__version__
5.6.0
>>> for p in psutil.process_iter():
...     print p.as_dict(['memory_full_info'])
...
{'memory_full_info': None}
{'memory_full_info': None}
{'memory_full_info': None}
{'memory_full_info': None}

C:\P27>
```

**Comment by giampaolo** [comment]
Is this a segfault?

**Comment by alxchk** [comment]
This machine is not configured for debugging, but, according to event log:

```
Faulting application name: python.exe, version: 0.0.0.0, time stamp: 0x5c7c8191
Faulting module name: ntdll.dll, version: 10.0.17758.1, time stamp: 0x11e00b28
Exception code: 0xc0000005
Fault offset: 0x000000000000e7c3
Faulting process id: 0x142c
Faulting application start time: 0x01d4d5d027483b9d
Faulting application path: C:\P27\python.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 57afb428-6883-4db4-af85-4dff7165650b
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by giampaolo** [comment]
These are the differences between psutil 4.0.0 and latest:

```diff
diff --git a/psutil/_psutil_windows.c b/psutil/_psutil_windows.c
index 2a498bb1..862087cc 100644
--- a/psutil/_psutil_windows.c
+++ b/psutil/_psutil_windows.c
@@ -789,16 +789,15 @@ psutil_proc_memory_uss(PyObject *self, PyObject *args)
     size_t private_pages;
     size_t i;
     DWORD info_array_size;
-    // needed by QueryWorkingSet
-    DWORD access = PROCESS_QUERY_INFORMATION | PROCESS_VM_READ;
     PSAPI_WORKING_SET_INFORMATION* info_array;
+    SYSTEM_INFO system_info;
     PyObject* py_result = NULL;
     unsigned long long total = 0;
 
     if (! PyArg_ParseTuple(args, "l", &pid))
         return NULL;
 
-    proc = psutil_handle_from_pid(pid, access);
+    proc = psutil_handle_from_pid(pid);
     if (proc == NULL)
         return NULL;
 
@@ -820,8 +819,7 @@ psutil_proc_memory_uss(PyObject *self, PyObject *args)
         goto done;
     }
 
-    info_array_size = tmp_size + \
-        ((DWORD)entries * sizeof(PSAPI_WORKING_SET_BLOCK));
+    info_array_size = tmp_size + (entries * sizeof(PSAPI_WORKING_SET_BLOCK));
     info_array = (PSAPI_WORKING_SET_INFORMATION*)malloc(info_array_size);
     if (!info_array) {
         PyErr_NoMemory();
@@ -843,7 +841,9 @@ psutil_proc_memory_uss(PyObject *self, PyObject *args)
         }
     }
 
-    total = private_pages * PSUTIL_SYSTEM_INFO.dwPageSize;
+    // GetSystemInfo has no return value.
+    GetSystemInfo(&system_info);
+    total = private_pages * system_info.dwPageSize;
     py_result = Py_BuildValue("K", total);
 
 done:
@@ -858,7 +858,6 @@ done:
     return py_result;
 }
```

Can you please verify 4.0.0 doesn't have this problem?

**Comment by alxchk** [comment]
4.0.0 - ok
4.1.0 - ok
4.2.0 - fail

**Comment by giampaolo** [comment]
Mmm no relevant changes were introduced in 4.2.0 so it must be something else:
https://github.com/giampaolo/psutil/compare/release-4.4.1...release-4.4.2#files_bucket

**Comment by giampaolo** [comment]
Test script which bashes `proc_memory_uss` function:

```python
import psutil
cext = psutil._psplatform.cext
while 1:
    for pid in psutil.pids():
        try:
            print(cext.proc_memory_uss(pid))
        except PermissionError as err:
            print(err)
```

**Comment by giampaolo** [comment]
@alxchk just to be sure, you can reproduce the issue with the above script, right?

**Comment by alxchk** [comment]
```
int __fastcall sub_180001E80(__int64 a1, __int64 a2)
{
  __int64 v2; // rbx@1
  void *v3; // rax@2
  void *v4; // rbp@3
  void *v5; // rdi@6
  unsigned int v6; // esi@8
  void *v7; // rax@8
  __int64 v8; // rdx@12
  __int64 *v9; // rcx@13
  __int64 v10; // rax@14
  __int64 v12; // [sp+20h] [bp-48h]@4
  __int64 v13; // [sp+28h] [bp-40h]@4
  struct _SYSTEM_INFO SystemInfo; // [sp+30h] [bp-38h]@18
  void *Memory; // [sp+80h] [bp+18h]@1

  v2 = 0i64;
  if ( PyArg_ParseTuple(a2, asc_18000C0D0, &Memory) )
  {
    LODWORD(v3) = sub_180006530((unsigned int)Memory);
    v4 = v3;
    if ( v3 )
    {
      v12 = 0i64;
      v13 = 0i64;
      if ( QueryWorkingSet(v3, &v12, 16i64) || v12 )
      {
        if ( 2 * v12 )
        {
          v6 = 16 * v12 + 16;
          v7 = malloc(v6);
          v5 = v7;
          if ( v7 )
          {
            if ( QueryWorkingSet(v4, v7, v6) )
            {
              v8 = *(_QWORD *)v5;
              if ( *(_QWORD *)v5 )
              {
                v9 = (__int64 *)((char *)v5 + 8);
                do
                {
                  v10 = *v9;
                  if ( !_bittest64(&v10, 8u) || (*v9 & 0xE0ui64) <= 0x20 )
                    ++v2;
                  ++v9;
                  --v8;
                }
                while ( v8 );
              }
              GetSystemInfo(&SystemInfo);
              LODWORD(v2) = Py_BuildValue(aK, v2 * (unsigned int)SystemInfo.dwPageSize);
            }
            else
            {
              PyErr_SetFromWindowsErr(0i64);
            }
          }
          else
          {
            PyErr_NoMemory();
          }
        }
        else
        {
          v5 = Memory;
        }
      }
      else
      {
        PyErr_SetFromWindowsErr(0i64);
        v5 = Memory;
      }
      CloseHandle(v4);
      if ( v5 )
        free(v5); <<<---- here ??
      LODWORD(v3) = v2;
    }
  }
  else
  {
    LODWORD(v3) = 0;
  }
  return (unsigned __int64)v3;
}
```

**Comment by alxchk** [comment]
```
import psutil
cext = psutil._psplatform.cext
while 1:
    for pid in psutil.pids():
        try:
	    print("Try", pid)
            print(cext.proc_memory_uss(pid))
            print("OK")
        except Exception as err:
            print("ERR", err)

print("OKAY")
```
```
C:\temp>C:\P27\python.exe test.py.txt
('Try', 0)
('ERR', OSError(13, 'Permission denied'))
('Try', 4)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 68)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 276)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 368)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 440)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 448)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 508)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 516)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 548)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 656)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 664)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 724)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 776)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 872)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 956)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 976)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 296)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 308)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 916)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 1112)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 1228)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 1340)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 1456)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 1528)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 1544)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 1560)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 1644)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 1688)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 1948)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 1984)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 1996)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 1108)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 8)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 1392)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 2168)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 2252)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 2336)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 2612)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 2780)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 2972)
262144
OK
('Try', 2988)
4104192
OK
('Try', 3024)
815104
OK
('Try', 1768)
1028096
OK
('Try', 1336)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 1964)
667648
OK
('Try', 3204)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 3444)
49127424
OK
('Try', 3608)
1646592
OK
('Try', 3756)
0
OK
('Try', 3960)
('ERR', WindowsError(5, 'Access is denied'))
('Try', 4008)

C:\temp>
```

**Comment by giampaolo** [comment]
How about this? (honestly I don't think it'll make a difference, just trying)
```diff
diff --git a/psutil/_psutil_windows.c b/psutil/_psutil_windows.c
index 2a498bb1..56904ddc 100644
--- a/psutil/_psutil_windows.c
+++ b/psutil/_psutil_windows.c
@@ -791,7 +791,7 @@ psutil_proc_memory_uss(PyObject *self, PyObject *args)
     DWORD info_array_size;
     // needed by QueryWorkingSet
     DWORD access = PROCESS_QUERY_INFORMATION | PROCESS_VM_READ;
-    PSAPI_WORKING_SET_INFORMATION* info_array;
+    PSAPI_WORKING_SET_INFORMATION* info_array = NULL;
     PyObject* py_result = NULL;
     unsigned long long total = 0;

@@ -851,7 +851,7 @@ done:
         CloseHandle(proc);
     }

-    if (info_array) {
+    if (info_array != NULL) {
         free(info_array);
     }
```

**Comment by giampaolo** [comment]
To quickly recompile and test (with latest GIT version) you can use:

```
make.bat test script.py
```

**Comment by alxchk** [comment]
I'm not 100% sure about the crash, also if this is free, then very likely it's about heap corruption

**Comment by alxchk** [comment]
>> +    PSAPI_WORKING_SET_INFORMATION* info_array = NULL;

this

**Comment by alxchk** [comment]
And now:

```
>>> a = [x.as_dict() for x in psutil.process_iter()]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\temp\psutil-master\psutil\__init__.py", line 634, in as_dict
    ret = meth()
  File "c:\temp\psutil-master\psutil\__init__.py", line 1186, in memory_full_info
    return self._proc.memory_full_info()
  File "c:\temp\psutil-master\psutil\_pswindows.py", line 661, in wrapper
    return fun(self, *args, **kwargs)
  File "c:\temp\psutil-master\psutil\_pswindows.py", line 800, in memory_full_info
    uss = cext.proc_memory_uss(self.pid)
SystemError: error return without exception set
>>>
```

**Comment by alxchk** [comment]
This happens here:

https://github.com/giampaolo/psutil/blob/master/psutil/_psutil_windows.c#L820

**Comment by giampaolo** [comment]
ProcessHacker appears to achieve the same thing by using `NtQueryVirtualMemory` instead of `QueryWorkingSet`. I'll try looking into that.

**Comment by alxchk** [comment]
Isn't it better to fix these two issues and leave as is? This process is privileged, so unlikely there will be more additional info.

**Comment by giampaolo** [comment]
I am not sure how to fix it, that’s the issue. :)

**Comment by giampaolo** [comment]
@alxchk OK done, could you please try https://github.com/giampaolo/psutil/pull/1453?

**Comment by giampaolo** [comment]
actually hang on, there are test failures

**Comment by giampaolo** [comment]
all green now

**Comment by alxchk** [comment]
Looks like works for me
