### ISSUE TITLE
glances not able to call psutil

### ISSUE THREAD

**Issue by timcowchip** [giampaolo/psutil#1457]
**Platform**
* { Crux-3.4 }
* { 5.6.1}

**Bug description**
{'invalid attr name 'io_counters'}
```
glances
Traceback (most recent call last):
  File "/usr/bin/glances", line 11, in <module>
    load_entry_point('Glances==3.1.0', 'console_scripts', 'glances')()
  File "/usr/lib/python3.6/site-packages/glances/__init__.py", line 140, in main
    start(config=config, args=args)
  File "/usr/lib/python3.6/site-packages/glances/__init__.py", line 106, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python3.6/site-packages/glances/standalone.py", line 74, in __init__
    self.stats.update()
  File "/usr/lib/python3.6/site-packages/glances/stats.py", line 222, in update
    self._plugins[p].update()
  File "/usr/lib/python3.6/site-packages/glances/plugins/glances_processcount.py", line 71, in update
    glances_processes.update()
  File "/usr/lib/python3.6/site-packages/glances/processes.py", line 247, in update
    ad_value=None)
  File "/usr/lib/python3.6/site-packages/glances/processes.py", line 246, in <listcomp>
    self.processlist = [p.info for p in psutil.process_iter(attrs=standard_attrs,
  File "/usr/lib/python3.6/site-packages/psutil/__init__.py", line 1562, in process_iter
    yield add(pid)
  File "/usr/lib/python3.6/site-packages/psutil/__init__.py", line 1539, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
  File "/usr/lib/python3.6/site-packages/psutil/__init__.py", line 623, in as_dict
    ", ".join(map(repr, invalid_names))))
ValueError: invalid attr name 'io_counters'
```
https://github.com/timcowchip/timcowchip/blob/master/python3-psutil/Pkgfile

**Comment by giampaolo** [comment]
That looks like a Glances bug. It should avoid attempting `io_counters` if not available on the platform.
