### ISSUE TITLE
AIX 7.2 Failed to iterate through processes using process_iter

### ISSUE THREAD

**Issue by pawelmy** [giampaolo/psutil#1486]
**Platform**
* OS: AIX 7.2
* Python version: 3.7.1
* psutil version: 5.6.1
* gcc version: 7.2.0

**Bug description**
When trying to iterate through processes, psutil crashes with the exception `AttributeError: 'function' object has no attribute 'cache_deactivate'`. Same issue is visible when running `python3 -m psutil.tests` (along with other failing tests).

```
Traceback (most recent call last):
  File "/opt/freeware/lib64/python3.7/site-packages/psutil/__init__.py", line 593, in oneshot
    self._proc.oneshot_enter()
  File "/opt/freeware/lib64/python3.7/site-packages/psutil/_psaix.py", line 369, in oneshot_enter
    self._proc_name_and_args.cache_activate(self)
AttributeError: 'function' object has no attribute 'cache_activate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/freeware/lib64/python3.7/site-packages/psutil/__init__.py", line 1562, in process_iter
    yield add(pid)
  File "/opt/freeware/lib64/python3.7/site-packages/psutil/__init__.py", line 1539, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
  File "/opt/freeware/lib64/python3.7/site-packages/psutil/__init__.py", line 627, in as_dict
    with self.oneshot():
  File "/opt/freeware/lib64/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/opt/freeware/lib64/python3.7/site-packages/psutil/__init__.py", line 601, in oneshot
    self._proc.oneshot_exit()
  File "/opt/freeware/lib64/python3.7/site-packages/psutil/_psaix.py", line 374, in oneshot_exit
    self._proc_name_and_args.cache_deactivate(self)
AttributeError: 'function' object has no attribute 'cache_deactivate'
```

**Way to reproduce**

```python
import psutil
for p in psutil.process_iter(attrs=["cmdline"]):
    p.info.get("cmdline")
```

**Test results**
```
======================================================================
ERROR: psutil.tests.test_contracts.TestFetchAllProcesses.test_fetch_all
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/freeware/lib64/python3.7/site-packages/psutil/__init__.py", line 593, in oneshot
    self._proc.oneshot_enter()
  File "/opt/freeware/lib64/python3.7/site-packages/psutil/_psaix.py", line 369, in oneshot_enter
    self._proc_name_and_args.cache_activate(self)
AttributeError: 'function' object has no attribute 'cache_activate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/freeware/lib64/python3.7/site-packages/psutil/tests/test_contracts.py", line 337, in test_fetch_all
    for p, name in self.iter_procs():
  File "/opt/freeware/lib64/python3.7/site-packages/psutil/tests/test_contracts.py", line 316, in iter_procs
    with p.oneshot():
  File "/opt/freeware/lib64/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/opt/freeware/lib64/python3.7/site-packages/psutil/__init__.py", line 601, in oneshot
    self._proc.oneshot_exit()
  File "/opt/freeware/lib64/python3.7/site-packages/psutil/_psaix.py", line 374, in oneshot_exit
    self._proc_name_and_args.cache_deactivate(self)
AttributeError: 'function' object has no attribute 'cache_deactivate'
```

**Comment by giampaolo** [comment]
Weird but I can't test it. Can you paste the full test output?

**Comment by pawelmy** [comment]
Here's the full log from `python3 -m psutil.tests`
[psutil-test.log](https://github.com/giampaolo/psutil/files/3071888/psutil-test.log)

**Comment by pawelmy** [comment]
@giampaolo If you have any ideas on a potential fix let me know and I can test it in my environment.

**Comment by wiggin15** [comment]
I can reproduce this. Happens because of we added the `wrap_exceptions` decorator on top of `memoize_when_activated`, and it probably stripped the extra cache methods (attributes) of the wrapped functions. Apparently we are missing `functools.wraps` in `wrap_exceptions` on some of the platforms.

**Comment by giampaolo** [comment]
Good catch (also `_pssunos.py`). Adding `functools.wraps` fixes it, right?

**Comment by wiggin15** [comment]
Just tested. Yes.
