### ISSUE TITLE
[AIX] connections() raises UnicodeDecodeError

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#1489]
**Platform**
* AIX 7.2
* 5.6.1

**Bug description**
Taken from #1486.
```
======================================================================
ERROR: psutil.tests.test_unicode.TestFSAPIsWithInvalidPath.test_proc_connections
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/freeware/lib64/python3.7/site-packages/psutil/tests/test_unicode.py", line 233, in test_proc_connections
    conn = psutil.Process().connections('unix')[0]
  File "/opt/freeware/lib64/python3.7/site-packages/psutil/__init__.py", line 1274, in connections
    return self._proc.connections(kind)
  File "/opt/freeware/lib64/python3.7/site-packages/psutil/_psaix.py", line 337, in wrapper
    return fun(self, *args, **kwargs)
  File "/opt/freeware/lib64/python3.7/site-packages/psutil/_psaix.py", line 456, in connections
    ret = net_connections(kind, _pid=self.pid)
  File "/opt/freeware/lib64/python3.7/site-packages/psutil/_psaix.py", line 230, in net_connections
    rawlist = cext.net_connections(_pid)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 48: invalid start byte
```

**Comment by wiggin15** [comment]
There were 7 tests in the `TestFSAPIsWithInvalidPath` suite that failed in that ticket. They are probably all related to the invalid name we use: `INVALID_NAME = TESTFN + "f\xc0\x80"`

**Comment by giampaolo** [comment]
I wouldn't bother about unicode-related and tests. Same for tests. re the script directory. There's another couple of tests which drew my attention:

```
======================================================================
ERROR: psutil.tests.test_contracts.TestDeprecations.test_memory_info_ex
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/freeware/lib64/python3.7/site-packages/psutil/tests/test_contracts.py", line 185, in test_memory_info_ex
    w = ws[0]
IndexError: list index out of range
```

Does this mean memory_info() returns an empty tuple?

```
======================================================================
FAIL: psutil.tests.test_process.TestProcess.test_terminal
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/freeware/lib64/python3.7/site-packages/psutil/tests/test_process.py", line 306, in test_terminal
    self.assertEqual(terminal, tty)
AssertionError: None != '/dev/pts/0'
```
If we can't get terminal for the current process I guess we can't in general?
