### ISSUE TITLE
[Windows Server 2016] AttributeError: 'Process' object has no attribute 'num_fds'

### ISSUE THREAD

**Issue by anelshaer** [giampaolo/psutil#1492]
**Platform**
Microsoft Windows Server 2016 Standard, Version : 10.0.14393, BuildNumber : 14393

Name: psutil, Version: 5.6.1
Location: c:\python27\lib\site-packages

**Bug description**
Process Object has no attribute 'num_fds' when running Osquery profiler on windows although on linux it runs smoothly. https://github.com/facebook/osquery

```
Profiling query: SELECT version, build, platform FROM os_version;
Traceback (most recent call last):
  File "C:\Users\dev\Downloads\osquery\tools\analysis\profile.py", line 365, in <module>
    timeout=args.timeout, count=args.count, rounds=args.rounds
  File "C:\Users\dev\Downloads\osquery\tools\analysis\profile.py", line 201, in profile
    result = run_query(shell, query, timeout=timeout, count=count)
  File "C:\Users\dev\Downloads\osquery\tools\analysis\profile.py", line 144, in run_query
    ], timeout=timeout, count=count)
  File "C:\Users\dev\Downloads\osquery\tools\analysis/../tests/utils.py", line 166, in profile_cmd
    current_stats = get_stats(p, step)
  File "C:\Users\dev\Downloads\osquery\tools\analysis/../tests/utils.py", line 142, in get_stats
    "fds": p.num_fds(),
AttributeError: 'Process' object has no attribute 'num_fds'
```
**Use Case**
```
osquery\tools\analysis\profile.py" --shell .\osqueryi.exe --table "osquery\osquery\tables\" --count 1 --round 4 --query  "SELECT version, build, platform FROM os_version;"
```

**Comment by giampaolo** [comment]
This looks like a osquery bug: num_fds() is not available on Windows (it's documented) so it should not be used.
