### ISSUE TITLE
[Windows] process command line throws error [1106]

### ISSUE THREAD

**Issue by MrElliott** [giampaolo/psutil#1508]
**Windows**
* { Edition: Windows Server 2019 Standard, Version 1809, OS build 17763.437 } 
* { psutil version 5.6.2 }  

**Bug description**
When I request the command line for a process on a new windows machine an error is thrown:

WindowsError: [Error 1168] Element not found: '(originated from NtQueryInformationProcess(ProcessBasicInformation))'

The code I use to get the command line looks very similar to this:

```python
        for proc in psutil.process_iter():
            try:
                localData = psutil.Process(proc.pid)
                commandLine = localData.cmdline()
            except psutil.Error:
                continue
```

and the traceback that is kicked out is as follows:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "snapshot.py", line 65, in __init__
    self.TopProcesses = ProcessSnapShot()
  File "snapshot.py", line 38, in __init__
    commandLine = localData.cmdline()
  File "C:\Python27\lib\site-packages\psutil\__init__.py", line 790, in cmdline
    return self._proc.cmdline()
  File "C:\Python27\lib\site-packages\psutil\_pswindows.py", line 718, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
  File "C:\Python27\lib\site-packages\psutil\_pswindows.py", line 708, in convert_oserror
    raise exc
WindowsError: [Error 1168] Element not found: '(originated from NtQueryInformationProcess(ProcessBasicInformation))'
```

from investigations I have done so far all I can tell is that the module may have been removed by microsoft. Any help with this would be greatly appreciated

**Comment by EccoTheFlintstone** [comment]
it may be related to #1501 

you don't need to create localData, proc is already a psutil.Process instance
could you call `print(proc)` before accessing `cmdline() `? (to see if it fails on Registry/Memory Compression, which is the bug described in #1501)

**Comment by MrElliott** [comment]
When I print proc this is the output I get

```python
psutil.Process(pid=0, name='System Idle Process', started='15:11:26')
psutil.Process(pid=4, name='System', started='15:11:26')
psutil.Process(pid=168, name='Registry', started='15:11:26')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "snapshot.py", line 66, in __init__
    self.TopProcesses = ProcessSnapShot()
  File "snapshot.py", line 39, in __init__
    commandLine = localData.cmdline()
  File "C:\Python27\lib\site-packages\psutil\__init__.py", line 790, in cmdline
    return self._proc.cmdline()
  File "C:\Python27\lib\site-packages\psutil\_pswindows.py", line 718, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
  File "C:\Python27\lib\site-packages\psutil\_pswindows.py", line 708, in convert_oserror
    raise exc
WindowsError: [Error 1168] Element not found: '(originated from NtQueryInformationProcess(ProcessBasicInformation))'
```

**Comment by EccoTheFlintstone** [comment]
It's failing on pseudo process "Registry" as expected.
It's the same bug as in #1501 , just wait for it to be solved an you'll be good to go :)

**Comment by MrElliott** [comment]
sounds good, thanks for the quick feedback :)
