### ISSUE TITLE
[Win 10] When try to open localhost:61209

### ISSUE THREAD

**Issue by Duke1715** [giampaolo/psutil#1514]
**glances -V**
Glances v3.1.0 with psutil v5.6.2
**python -V**
Python 3.7.3
```
> C:\Users\Duke>glances
> Glances Web User Interface started on http://0.0.0.0:61209/
> Traceback (most recent call last):
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 138, in run
>     self.finish_response()
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 180, in finish_response
>     self.write(data)
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 274, in write
>     self.send_headers()
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 333, in send_headers
>     self._write(bytes(self.headers))
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\headers.py", line 142, in __bytes__
>     return str(self).encode('iso-8859-1')
> UnicodeEncodeError: 'latin-1' codec can't encode characters in position 78-79: ordinal not in range(256)
> ----------------------------------------
> Exception happened during processing of request from ('127.0.0.1', 52219)
> Traceback (most recent call last):
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 138, in run
>     self.finish_response()
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 180, in finish_response
>     self.write(data)
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 274, in write
>     self.send_headers()
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 333, in send_headers
>     self._write(bytes(self.headers))
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\headers.py", line 142, in __bytes__
>     return str(self).encode('iso-8859-1')
> UnicodeEncodeError: 'latin-1' codec can't encode characters in position 78-79: ordinal not in range(256)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 141, in run
>     self.handle_error()
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 368, in handle_error
>     self.finish_response()
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 180, in finish_response
>     self.write(data)
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 274, in write
>     self.send_headers()
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 331, in send_headers
>     if not self.origin_server or self.client_is_modern():
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 344, in client_is_modern
>     return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
> TypeError: 'NoneType' object is not subscriptable
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\socketserver.py", line 316, in _handle_request_noblock
>     self.process_request(request, client_address)
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\socketserver.py", line 347, in process_request
>     self.finish_request(request, client_address)
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\socketserver.py", line 360, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\socketserver.py", line 720, in __init__
>     self.handle()
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\simple_server.py", line 133, in handle
>     handler.run(self.server.get_app())
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 144, in run
>     self.close()
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\simple_server.py", line 35, in close
>     self.status.split(' ',1)[0], self.bytes_sent
> AttributeError: 'NoneType' object has no attribute 'split'
> ----------------------------------------
> Traceback (most recent call last):
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 138, in run
>     self.finish_response()
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 180, in finish_response
>     self.write(data)
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 274, in write
>     self.send_headers()
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 333, in send_headers
>     self._write(bytes(self.headers))
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\headers.py", line 142, in __bytes__
>     return str(self).encode('iso-8859-1')
> UnicodeEncodeError: 'latin-1' codec can't encode characters in position 65-66: ordinal not in range(256)
> ----------------------------------------
> Exception happened during processing of request from ('127.0.0.1', 52220)
> Traceback (most recent call last):
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 138, in run
>     self.finish_response()
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 180, in finish_response
>     self.write(data)
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 274, in write
>     self.send_headers()
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 333, in send_headers
>     self._write(bytes(self.headers))
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\headers.py", line 142, in __bytes__
>     return str(self).encode('iso-8859-1')
> UnicodeEncodeError: 'latin-1' codec can't encode characters in position 65-66: ordinal not in range(256)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 141, in run
>     self.handle_error()
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 368, in handle_error
>     self.finish_response()
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 180, in finish_response
>     self.write(data)
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 274, in write
>     self.send_headers()
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 331, in send_headers
>     if not self.origin_server or self.client_is_modern():
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 344, in client_is_modern
>     return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
> TypeError: 'NoneType' object is not subscriptable
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\socketserver.py", line 316, in _handle_request_noblock
>     self.process_request(request, client_address)
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\socketserver.py", line 347, in process_request
>     self.finish_request(request, client_address)
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\socketserver.py", line 360, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\socketserver.py", line 720, in __init__
>     self.handle()
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\simple_server.py", line 133, in handle
>     handler.run(self.server.get_app())
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\handlers.py", line 144, in run
>     self.close()
>   File "c:\users\duke\appdata\local\programs\python\python37-32\lib\wsgiref\simple_server.py", line 35, in close
>     self.status.split(' ',1)[0], self.bytes_sent
> AttributeError: 'NoneType' object has no attribute 'split'
> ----------------------------------------
```

**Comment by giampaolo** [comment]
Doesn't look related to psutil. Closing.
