### ISSUE TITLE
[WIN10, Ubuntu] Failure setting process pid using multiprocessing namespace

### ISSUE THREAD

**Issue by misantroop** [giampaolo/psutil#1523]
**Platform**
* { python version } - 3.6.8
* { psutil version } - 5.5.0 and later

**Bug description**
Discovered this after an upgrade, works in 5.4.8 but breaks in 5.5.0 and later versions. Setting namespace attributes to strings works.

```
Process Process-2:
Traceback (most recent call last):
  File "C:\Python\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\WERK\test3.py", line 47, in primary
    ns.primary = psutil.Process()
  File "C:\Python\lib\multiprocessing\managers.py", line 1065, in __setattr__
    return callmethod('__setattr__', (key, value))
  File "C:\Python\lib\multiprocessing\managers.py", line 756, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "C:\Python\lib\multiprocessing\connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Python\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects
Process Process-3:
Traceback (most recent call last):
  File "C:\Python\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\WERK\test3.py", line 50, in secondary
    ns.secondary = psutil.Process()
  File "C:\Python\lib\multiprocessing\managers.py", line 1065, in __setattr__
    return callmethod('__setattr__', (key, value))
  File "C:\Python\lib\multiprocessing\managers.py", line 756, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "C:\Python\lib\multiprocessing\connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Python\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects
```

```python
from multiprocessing import Process, Manager
import psutil

def main():
	manager = Manager()
	main.ns = manager.Namespace()
	main.ls = manager.list([1])
	runParallel(primary, secondary)

def runParallel(*fns):
	proc = []
	for fn in fns:
		p = Process(target=fn, args=(main.ns, main.ls))
		p.start()
		proc.append(p)
	for p in proc: p.join()

def primary(ns, ls):
	ns.primary = psutil.Process()

def secondary(ns, ls):
	ns.secondary = psutil.Process()

if __name__ ==  '__main__':
	main()
```

**Comment by giampaolo** [comment]
old bug; upgrade to later version

**Comment by misantroop** [comment]
The issue is also present in the latest version. It breaks in versions 5.5.0 and up.
