### ISSUE TITLE
[MAC OS] Import Error (Python 3.7)

### ISSUE THREAD

**Issue by kwekwl** [giampaolo/psutil#1547]
**Platform**
* { OS version 10.14.5 }     (also add appropriate OS issue label (linux, windows, ...))
* { psutil version 5.4.7 }  (use "pip show psutil")

**Bug description**
{ I tried to import psutil on python but I received an import error, I uninstall psutil and install psutil and I still receive the same error message. }

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wenlin.kwek/Documents/fp_churn/venv/lib/python3.7/site-packages/psutil/__init__.py", line 157, in <module>
    from . import _psosx as _psplatform
  File "/Users/wenlin.kwek/Documents/fp_churn/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 16, in <module>
    from . import _psutil_osx as cext
ImportError: dlopen(/Users/wenlin.kwek/Documents/fp_churn/venv/lib/python3.7/site-packages/psutil/_psutil_osx.cpython-37m-darwin.so, 2): Symbol not found: _kIOMasterPortDefault
  Referenced from: /Users/wenlin.kwek/Documents/fp_churn/venv/lib/python3.7/site-packages/psutil/_psutil_osx.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/wenlin.kwek/Documents/fp_churn/venv/lib/python3.7/site-packages/psutil/_psutil_osx.cpython-37m-darwin.so
```

```python
>>> import psutil
```

**Test results**
```
output of `python -c psutil.tests` (failures only, not full result)
```
{ you may want to do this in order to discover other issues affecting your platform }
{ if failures look unrelated with the issue at hand open another ticket }

**Comment by fhaque** [comment]
So, as far as I can tell, this import issue happens for Python <3.7. 3.6 seems to be okay. I found this issue has affected my install of the Pants repo.

**Comment by giampaolo** [comment]
Python 3.7 and macOS 10.14 are no longer supported. Closing as obsolete.
