### ISSUE TITLE
Windows 10 cannot import name '_psutil_windows'

### ISSUE THREAD

**Issue by officialstargator** [giampaolo/psutil#1557]
**Platform**
*  Microsoft Windows 10 Home  Version: 10.017134  Build: 17134
* Psutil version: 5.2.2

**Bug description**
When i try to import psutil in python an import error shows up.

```
Traceback (most recent call last):
  File "C:/Users/danie/PycharmProjects/Utilities/Test/Test_1.py", line 1, in <module>
    import psutil
  File "C:\Users\danie\AppData\Local\Programs\Python\Python36-32\lib\site-packages\psutil\__init__.py", line 126, in <module>
    from . import _pswindows as _psplatform
  File "C:\Users\danie\AppData\Local\Programs\Python\Python36-32\lib\site-packages\psutil\_pswindows.py", line 16, in <module>
    from . import _psutil_windows as cext
ImportError: cannot import name '_psutil_windows'

Process finished with exit code 1
```

```python 
import psutil
```

**Test results**
```
Traceback (most recent call last):
  File "C:\Users\danie\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python36-32\lib\site-packages\psutil\__init__.py", line 126, in <module>
    from . import _pswindows as _psplatform
  File "C:\Users\danie\AppData\Local\Programs\Python\Python36-32\lib\site-packages\psutil\_pswindows.py", line 16, in <module>
    from . import _psutil_windows as cext
ImportError: cannot import name '_psutil_windows'
```

**Comment by xiaosong97** [comment]
Hello~Is this bug solved? I also met the same problem.

**Comment by giampaolo** [comment]
That looks like an installation problem. Try to delete `C:\Users\danie\AppData\Local\Programs\Python\Python36-32\lib\site-packages\psutil` directory and reinstall psutil.
