### ISSUE TITLE
FAIL: test_get_pid_list (__main__.TestModuleFunctionsLeaks)

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#156]
_From [matrixhasu](https://code.google.com/u/matrixhasu/) on April 04, 2011 19:57:43_

```
Hi,
on a Debian sid chroot (amd64), when running unit test on the on-built package I got:

    FAIL: test_get_pid_list (__main__.TestModuleFunctionsLeaks)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "test/test_memory_leaks.py", line 155, in test_get_pid_list
        self.execute('get_pid_list')
      File "test/test_memory_leaks.py", line 152, in execute
        self.fail("rss1=&#37;s, rss2=&#37;s, difference=&#37;s" &#37;(rss1, 
rss2, difference))
    AssertionError: rss1=9482240, rss2=9494528, difference=12288

If I can help you somehow in debugging this problem, just ask :)
```

_Original issue: http://code.google.com/p/psutil/issues/detail?id=156_

**Comment by giampaolo** [comment]
Closing this out as outdated.
