### ISSUE TITLE
[Linux- CentOS 6] 5.6.4 install fails with ImportError: No module named 'setuptools.build_meta

### ISSUE THREAD

**Issue by rfboykin** [giampaolo/psutil#1613]
**Platform**
* { Linux, CentOS 6 }
* { Version 5.6.4 }

**Bug description**
When attempting to install 5.6.4, I receive the following error: `ImportError: No module named 'setuptools.build_meta`

Installing 5.6.3 completes as expected

**Traceback**
Note I've removed the full path name with {build_location}
```
Collecting psutil
  Downloading http://devpi/root/pypi/%2Bf/512/e854d68f8b42f/psutil-5.6.4.tar.gz (447kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
ERROR: Exception:
Traceback (most recent call last):
  File "{build_location}/env/lib/python3.5/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "{build_location}/env/lib/python3.5/site-packages/pip/_internal/commands/install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "{build_location}/env/lib/python3.5/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "{build_location}/env/lib/python3.5/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "{build_location}/env/lib/python3.5/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "{build_location}/env/lib/python3.5/site-packages/pip/_internal/operations/prepare.py", line 224, in prepare_linked_requirement
    req, self.req_tracker, finder, self.build_isolation,
  File "{build_location}/env/lib/python3.5/site-packages/pip/_internal/operations/prepare.py", line 49, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "{build_location}/env/lib/python3.5/site-packages/pip/_internal/distributions/source/legacy.py", line 37, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "{build_location}/env/lib/python3.5/site-packages/pip/_internal/distributions/source/legacy.py", line 90, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "{build_location}/env/lib/python3.5/site-packages/pip/_vendor/pep517/wrappers.py", line 152, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "{build_location}/env/lib/python3.5/site-packages/pip/_vendor/pep517/wrappers.py", line 255, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "{build_location}/env/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 63, in _build_backend
    obj = import_module(mod_path)
  File "{build_location}/env/lib64/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'setuptools.build_meta'
```

**Comment by rfboykin** [comment]
Turns out my environment was using an older version of setuptools while setuptools.build_meta was introduced in version 36.6.0. 
Upgrading setuptools resolved it.
