### ISSUE TITLE
[Linux] several test failures

### ISSUE THREAD

**Issue by DerDakon** [giampaolo/psutil#1635]
**Platform**
* Linux, Sparc T5120
* 5.6.7

**Bug description**
Several test failures, as below. Downstream issue: https://bugs.gentoo.org/701918

**Test results**
```
======================================================================
ERROR: psutil.tests.test_system.TestSystemAPIs.test_sensors_battery
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_system.py", line 854, in test_sensors_battery
    ret = psutil.sensors_battery()
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/__init__.py", line 2397, in sensors_battery
    return _psplatform.sensors_battery()
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/_pslinux.py", line 1345, in sensors_battery
    bats = [x for x in os.listdir(POWER_SUPPLY_PATH) if x.startswith('BAT')]
OSError: [Errno 2] No such file or directory: '/sys/class/power_supply'

======================================================================
ERROR: psutil.tests.test_linux.TestSensorsBattery.test_emulate_energy_full_0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_linux.py", line 1523, in test_emulate_energy_full_0
    self.assertEqual(psutil.sensors_battery().percent, 0)
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/__init__.py", line 2397, in sensors_battery
    return _psplatform.sensors_battery()
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/_pslinux.py", line 1345, in sensors_battery
    bats = [x for x in os.listdir(POWER_SUPPLY_PATH) if x.startswith('BAT')]
OSError: [Errno 2] No such file or directory: '/sys/class/power_supply'

======================================================================
ERROR: psutil.tests.test_linux.TestSensorsBattery.test_emulate_energy_full_not_avail
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_linux.py", line 1537, in test_emulate_energy_full_not_avail
    self.assertEqual(psutil.sensors_battery().percent, 88)
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/__init__.py", line 2397, in sensors_battery
    return _psplatform.sensors_battery()
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/_pslinux.py", line 1345, in sensors_battery
    bats = [x for x in os.listdir(POWER_SUPPLY_PATH) if x.startswith('BAT')]
OSError: [Errno 2] No such file or directory: '/sys/class/power_supply'

======================================================================
ERROR: psutil.tests.test_linux.TestSensorsBattery.test_emulate_no_base_files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_linux.py", line 1517, in test_emulate_no_base_files
    self.assertIsNone(psutil.sensors_battery())
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/__init__.py", line 2397, in sensors_battery
    return _psplatform.sensors_battery()
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/_pslinux.py", line 1345, in sensors_battery
    bats = [x for x in os.listdir(POWER_SUPPLY_PATH) if x.startswith('BAT')]
OSError: [Errno 2] No such file or directory: '/sys/class/power_supply'

======================================================================
ERROR: psutil.tests.test_linux.TestSensorsBattery.test_emulate_no_power
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_linux.py", line 1550, in test_emulate_no_power
    self.assertIsNone(psutil.sensors_battery().power_plugged)
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/__init__.py", line 2397, in sensors_battery
    return _psplatform.sensors_battery()
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/_pslinux.py", line 1345, in sensors_battery
    bats = [x for x in os.listdir(POWER_SUPPLY_PATH) if x.startswith('BAT')]
OSError: [Errno 2] No such file or directory: '/sys/class/power_supply'

======================================================================
ERROR: psutil.tests.test_linux.TestSensorsBattery.test_emulate_power_not_plugged
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_linux.py", line 1470, in test_emulate_power_not_plugged
    self.assertEqual(psutil.sensors_battery().power_plugged, False)
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/__init__.py", line 2397, in sensors_battery
    return _psplatform.sensors_battery()
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/_pslinux.py", line 1345, in sensors_battery
    bats = [x for x in os.listdir(POWER_SUPPLY_PATH) if x.startswith('BAT')]
OSError: [Errno 2] No such file or directory: '/sys/class/power_supply'

======================================================================
ERROR: psutil.tests.test_linux.TestSensorsBattery.test_emulate_power_not_plugged_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_linux.py", line 1487, in test_emulate_power_not_plugged_2
    self.assertEqual(psutil.sensors_battery().power_plugged, False)
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/__init__.py", line 2397, in sensors_battery
    return _psplatform.sensors_battery()
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/_pslinux.py", line 1345, in sensors_battery
    bats = [x for x in os.listdir(POWER_SUPPLY_PATH) if x.startswith('BAT')]
OSError: [Errno 2] No such file or directory: '/sys/class/power_supply'

======================================================================
ERROR: psutil.tests.test_linux.TestSensorsBattery.test_emulate_power_plugged
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_linux.py", line 1437, in test_emulate_power_plugged
    self.assertEqual(psutil.sensors_battery().power_plugged, True)
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/__init__.py", line 2397, in sensors_battery
    return _psplatform.sensors_battery()
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/_pslinux.py", line 1345, in sensors_battery
    bats = [x for x in os.listdir(POWER_SUPPLY_PATH) if x.startswith('BAT')]
OSError: [Errno 2] No such file or directory: '/sys/class/power_supply'

======================================================================
ERROR: psutil.tests.test_linux.TestSensorsBattery.test_emulate_power_plugged_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_linux.py", line 1456, in test_emulate_power_plugged_2
    self.assertEqual(psutil.sensors_battery().power_plugged, True)
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/__init__.py", line 2397, in sensors_battery
    return _psplatform.sensors_battery()
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/_pslinux.py", line 1345, in sensors_battery
    bats = [x for x in os.listdir(POWER_SUPPLY_PATH) if x.startswith('BAT')]
OSError: [Errno 2] No such file or directory: '/sys/class/power_supply'

======================================================================
ERROR: psutil.tests.test_linux.TestSensorsBattery.test_emulate_power_undetermined
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_linux.py", line 1505, in test_emulate_power_undetermined
    self.assertIsNone(psutil.sensors_battery().power_plugged)
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/__init__.py", line 2397, in sensors_battery
    return _psplatform.sensors_battery()
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/_pslinux.py", line 1345, in sensors_battery
    bats = [x for x in os.listdir(POWER_SUPPLY_PATH) if x.startswith('BAT')]
OSError: [Errno 2] No such file or directory: '/sys/class/power_supply'

======================================================================
ERROR: psutil.tests.test_linux.TestSystemCPUCountLogical.test_emulate_fallbacks
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_linux.py", line 673, in test_emulate_fallbacks
    self.assertEqual(psutil._pslinux.cpu_count_logical(), original)
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/_pslinux.py", line 610, in cpu_count_logical
    with open_text('%s/stat' % get_procfs_path()) as f:
ValueError: I/O operation on closed file.

======================================================================
FAIL: psutil.tests.test_contracts.TestAvailability.test_cpu_freq
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_contracts.py", line 114, in test_cpu_freq
    linux or MACOS or WINDOWS or FREEBSD)
AssertionError: True != False

======================================================================
FAIL: psutil.tests.test_contracts.TestAvailability.test_proc_io_counters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_contracts.py", line 148, in test_proc_io_counters
    self.assertEqual(hasit, False if MACOS or SUNOS else True)
AssertionError: False != True

======================================================================
FAIL: psutil.tests.test_process.TestProcess.test_cpu_affinity_all_combinations
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_process.py", line 954, in test_cpu_affinity_all_combinations
    self.assertEqual(p.cpu_affinity(), combo)
AssertionError: Lists differ: [8, 1] != [1, 8]

First differing element 0:
8
1

- [8, 1]
+ [1, 8]

======================================================================
FAIL: psutil.tests.test_linux.TestSystemCPUCountPhysical.test_against_lscpu
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_linux.py", line 693, in test_against_lscpu
    self.assertEqual(psutil.cpu_count(logical=False), len(core_ids))
AssertionError: 8 != 16

======================================================================
FAIL: psutil.tests.test_linux.TestSystemCPUFrequency.test_emulate_use_cpuinfo
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_linux.py", line 739, in test_emulate_use_cpuinfo
    assert ret
AssertionError

----------------------------------------------------------------------
Ran 542 tests in 33.239s

FAILED (failures=5, errors=11, skipped=200)
```

**Comment by DerDakon** [comment]
Similar on hppa:

```
======================================================================
ERROR: psutil.tests.test_linux.TestSensorsBattery.test_emulate_energy_full_0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_linux.py", line 1523, in test_emulate_energy_full_0
    self.assertEqual(psutil.sensors_battery().percent, 0)
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/__init__.py", line 2397, in sensors_battery
    return _psplatform.sensors_battery()
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/_pslinux.py", line 1345, in sensors_battery
    bats = [x for x in os.listdir(POWER_SUPPLY_PATH) if x.startswith('BAT')]
OSError: [Errno 2] No such file or directory: '/sys/class/power_supply'

======================================================================
ERROR: psutil.tests.test_linux.TestSensorsBattery.test_emulate_energy_full_not_avail
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_linux.py", line 1537, in test_emulate_energy_full_not_avail
    self.assertEqual(psutil.sensors_battery().percent, 88)
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/__init__.py", line 2397, in sensors_battery
    return _psplatform.sensors_battery()
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/_pslinux.py", line 1345, in sensors_battery
    bats = [x for x in os.listdir(POWER_SUPPLY_PATH) if x.startswith('BAT')]
OSError: [Errno 2] No such file or directory: '/sys/class/power_supply'

======================================================================
ERROR: psutil.tests.test_linux.TestSensorsBattery.test_emulate_no_base_files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_linux.py", line 1517, in test_emulate_no_base_files
    self.assertIsNone(psutil.sensors_battery())
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/__init__.py", line 2397, in sensors_battery
    return _psplatform.sensors_battery()
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/_pslinux.py", line 1345, in sensors_battery
    bats = [x for x in os.listdir(POWER_SUPPLY_PATH) if x.startswith('BAT')]
OSError: [Errno 2] No such file or directory: '/sys/class/power_supply'

======================================================================
ERROR: psutil.tests.test_linux.TestSensorsBattery.test_emulate_no_power
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_linux.py", line 1550, in test_emulate_no_power
    self.assertIsNone(psutil.sensors_battery().power_plugged)
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/__init__.py", line 2397, in sensors_battery
    return _psplatform.sensors_battery()
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/_pslinux.py", line 1345, in sensors_battery
    bats = [x for x in os.listdir(POWER_SUPPLY_PATH) if x.startswith('BAT')]
OSError: [Errno 2] No such file or directory: '/sys/class/power_supply'

======================================================================
ERROR: psutil.tests.test_linux.TestSensorsBattery.test_emulate_power_not_plugged
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_linux.py", line 1470, in test_emulate_power_not_plugged
    self.assertEqual(psutil.sensors_battery().power_plugged, False)
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/__init__.py", line 2397, in sensors_battery
    return _psplatform.sensors_battery()
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/_pslinux.py", line 1345, in sensors_battery
    bats = [x for x in os.listdir(POWER_SUPPLY_PATH) if x.startswith('BAT')]
OSError: [Errno 2] No such file or directory: '/sys/class/power_supply'

======================================================================
ERROR: psutil.tests.test_linux.TestSensorsBattery.test_emulate_power_not_plugged_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_linux.py", line 1487, in test_emulate_power_not_plugged_2
    self.assertEqual(psutil.sensors_battery().power_plugged, False)
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/__init__.py", line 2397, in sensors_battery
    return _psplatform.sensors_battery()
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/_pslinux.py", line 1345, in sensors_battery
    bats = [x for x in os.listdir(POWER_SUPPLY_PATH) if x.startswith('BAT')]
OSError: [Errno 2] No such file or directory: '/sys/class/power_supply'

======================================================================
ERROR: psutil.tests.test_linux.TestSensorsBattery.test_emulate_power_plugged
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_linux.py", line 1437, in test_emulate_power_plugged
    self.assertEqual(psutil.sensors_battery().power_plugged, True)
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/__init__.py", line 2397, in sensors_battery
    return _psplatform.sensors_battery()
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/_pslinux.py", line 1345, in sensors_battery
    bats = [x for x in os.listdir(POWER_SUPPLY_PATH) if x.startswith('BAT')]
OSError: [Errno 2] No such file or directory: '/sys/class/power_supply'

======================================================================
ERROR: psutil.tests.test_linux.TestSensorsBattery.test_emulate_power_plugged_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_linux.py", line 1456, in test_emulate_power_plugged_2
    self.assertEqual(psutil.sensors_battery().power_plugged, True)
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/__init__.py", line 2397, in sensors_battery
    return _psplatform.sensors_battery()
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/_pslinux.py", line 1345, in sensors_battery
    bats = [x for x in os.listdir(POWER_SUPPLY_PATH) if x.startswith('BAT')]
OSError: [Errno 2] No such file or directory: '/sys/class/power_supply'

======================================================================
ERROR: psutil.tests.test_linux.TestSensorsBattery.test_emulate_power_undetermined
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_linux.py", line 1505, in test_emulate_power_undetermined
    self.assertIsNone(psutil.sensors_battery().power_plugged)
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/__init__.py", line 2397, in sensors_battery
    return _psplatform.sensors_battery()
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/_pslinux.py", line 1345, in sensors_battery
    bats = [x for x in os.listdir(POWER_SUPPLY_PATH) if x.startswith('BAT')]
OSError: [Errno 2] No such file or directory: '/sys/class/power_supply'

======================================================================
ERROR: psutil.tests.test_system.TestSystemAPIs.test_sensors_battery
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_system.py", line 854, in test_sensors_battery
    ret = psutil.sensors_battery()
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/__init__.py", line 2397, in sensors_battery
    return _psplatform.sensors_battery()
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/_pslinux.py", line 1345, in sensors_battery
    bats = [x for x in os.listdir(POWER_SUPPLY_PATH) if x.startswith('BAT')]
OSError: [Errno 2] No such file or directory: '/sys/class/power_supply'

======================================================================
FAIL: psutil.tests.test_contracts.TestAvailability.test_cpu_freq
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_contracts.py", line 114, in test_cpu_freq
    linux or MACOS or WINDOWS or FREEBSD)
AssertionError: True != False

======================================================================
FAIL: psutil.tests.test_contracts.TestAvailability.test_proc_io_counters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_contracts.py", line 148, in test_proc_io_counters
    self.assertEqual(hasit, False if MACOS or SUNOS else True)
AssertionError: False != True

======================================================================
FAIL: psutil.tests.test_linux.TestSystemCPUCountPhysical.test_against_lscpu
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/psutil-5.6.7/work/psutil-5.6.7-python2_7/lib/psutil/tests/test_linux.py", line 693, in test_against_lscpu
    self.assertEqual(psutil.cpu_count(logical=False), len(core_ids))
AssertionError: 2 != 4

----------------------------------------------------------------------
Ran 542 tests in 30.776s

FAILED (failures=3, errors=10, skipped=198)
```

**Comment by DerDakon** [comment]
Seems that some things are even wrong on AMD64: https://bugs.gentoo.org/703154

**Comment by DerDakon** [comment]
The last failure on hppa is reported with additional detail in #1645, the last sparc issue in #1644.

**Comment by giampaolo** [comment]
> (BTW, would it be possible to make the test suite compatible with plain pytest or python3 -munittest discover? It would be easier to skip failing tests)

I just switched to pytest: https://github.com/giampaolo/psutil/issues/2446.

**Comment by giampaolo** [comment]
psutil 5.6.7 on Python 2.7. The two failures that were actually actionable got split out into #1644 and #1645, and the missing /sys/class/power_supply one is long fixed. Closing as stale.
