### ISSUE TITLE
[5.5.1-arch1-1] psutil.disk_io_counters() raises "ValueError: not sure how to interpret line"

### ISSUE THREAD

**Issue by Twofyw** [giampaolo/psutil#1680]
**Platform**
* Linux 5.5.1-arch1-1     (also add appropriate OS issue label (linux, windows, ...))
* psutil v5.7.0  (use "pip show psutil")

**Bug description**
`disk_io_counters()` fails on Linux kernel 5.5.1.
Modifying `site-packages/psutil/_pslinux.py:1087` from `elif flen == 14 or flen == 18:` to 
`elif flen == 14 or flen == 18 or flen == 20:` fixes this issue.
```
traceback message (if any)
>>> import psutil
>>> psutil.disk_io_counters()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/psutil/__init__.py", line 2168, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1125, in disk_io_counters
    for entry in gen:
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1098, in read_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line ' 259       0 nvme0n1 365820 102074 34177090 116528 583679 453195 55649570 783890 0 558424 385707 0 0 0 0 95529 124896\n'
```

**Test results**
BTW, several tests fail with a clean clone from git. Since I'm new to psutil, I'm not sure if making a pull request with above work around would be a good idea, so I'll leave it with you.
```
output of `make test` (failures only, not full result)
======================================================================
ERROR: psutil.tests.test_linux.TestSensorsTemperatures.test_emulate_eio_error
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/twofyw/projects/psutil/psutil/tests/test_linux.py", line 1568, in test_emulate_eio_error
    self.assertIn("ignoring", str(ws[0].message))
IndexError: list index out of range

======================================================================
ERROR: psutil.tests.test_linux.TestSystemDiskIoCounters.test_emulate_use_sysfs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/twofyw/projects/psutil/psutil/tests/test_linux.py", line 1195, in test_emulate_use_sysfs
    wsysfs = psutil.disk_io_counters(perdisk=True)
  File "/home/twofyw/projects/psutil/psutil/__init__.py", line 2065, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/home/twofyw/projects/psutil/psutil/_pslinux.py", line 1122, in disk_io_counters
    for entry in gen:
  File "/home/twofyw/projects/psutil/psutil/_pslinux.py", line 1107, in read_sysfs
    (reads, reads_merged, rbytes, rtime, writes, writes_merged,
ValueError: too many values to unpack (expected 11)

======================================================================
FAIL: psutil.tests.test_process.TestProcess.test_cpu_affinity_all_combinations
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/twofyw/projects/psutil/psutil/tests/test_process.py", line 953, in test_cpu_affinity_all_combinations
    self.assertEqual(p.cpu_affinity(), combo)
AssertionError: Lists differ: [8, 1] != [1, 8]

First differing element 0:
8
1

- [8, 1]
+ [1, 8]

======================================================================
FAIL: psutil.tests.test_contracts.TestFetchAllProcesses.test_fetch_all
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/twofyw/projects/psutil/psutil/_pslinux.py", line 1514, in wrapper
    return fun(self, *args, **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/420317/fd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/twofyw/projects/psutil/psutil/tests/test_contracts.py", line 385, in test_fetch_all
    ret = self.call_meth(p, name)
psutil.AccessDenied: psutil.AccessDenied (pid=420317, name='kworker/7:2-mm_percpu_wq')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/twofyw/projects/psutil/psutil/tests/test_contracts.py", line 395, in test_fetch_all
    self.assertEqual(err.name, p.name())
AssertionError: 'kworker/7:2-mm_percpu_wq' != 'kworker/7:2-events'
- kworker/7:2-mm_percpu_wq
+ kworker/7:2-events


----------------------------------------------------------------------
Ran 548 tests in 6.199s

FAILED (failures=2, errors=2, skipped=159)
make: *** [Makefile:110: test] Error 1
```

This problem causes nicolargo/glances to not show diskio (https://github.com/nicolargo/glances/issues/1356#issuecomment-582215547).

**Comment by giampaolo** [comment]
This is an old bug which is already fixed. You should upgrade.

**Comment by dliappis** [comment]
For the record AFAICS this got fixed in https://github.com/giampaolo/psutil/pull/1665 and [will be included](https://github.com/giampaolo/psutil/blob/master/HISTORY.rst#570-unreleased) in the (unreleased as of yet) 5.7.0.
