### ISSUE TITLE
[Arch Linux x86_64] psutil.disk_io_counters() returns value error after system update

### ISSUE THREAD

**Issue by nims11** [giampaolo/psutil#1683]
**Platform**
* OS: Arch Linux x86_64
* `uname -s -r`: Linux 5.5.2-arch1-1
* `pip show psutil`
```
Name: psutil
Version: 5.6.7
Summary: Cross-platform lib for process and system monitoring in Python.
Home-page: https://github.com/giampaolo/psutil
Author: Giampaolo Rodola
Author-email: g.rodola@gmail.com
License: BSD
Location: /usr/lib/python3.8/site-packages
Requires:
Required-by:
```

**Bug description**
After a recent system upgrade, I am unable to use `psutil.disk_io_counters()`. Doing so leads to:

```
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/psutil/__init__.py", line 2168, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1125, in disk_io_counters
    for entry in gen:
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1098, in read_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line ' 259       0 nvme0n1 19720 20636 1419157 7884 5400 3811 206626 5450 0 9807 6914 0 0 0 0 354
```

Code to reproduce:

```python
import psutil
psutil.disk_io_counters()
```

**Test results**
```
======================================================================
ERROR: psutil.tests.test_linux.TestSystemDiskIoCounters.test_emulate_use_sysfs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/psutil/tests/test_linux.py", line 1191, in test_emulate_use_sysfs
    wprocfs = psutil.disk_io_counters(perdisk=True)
  File "/usr/lib/python3.8/site-packages/psutil/__init__.py", line 2168, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1125, in disk_io_counters
    for entry in gen:
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1098, in read_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line ' 259       0 nvme0n1 22389 22391 1604445 8411 7761 6043 512586 11004 0 13340 11377 0 0 0 0 573 3591\n'

======================================================================
ERROR: psutil.tests.test_contracts.TestDeprecations.test_memory_info_ex
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/psutil/tests/test_contracts.py", line 180, in test_memory_info_ex
    w = ws[0]
IndexError: list index out of range

======================================================================
ERROR: psutil.tests.test_contracts.TestSystem.test_io_counters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/psutil/tests/test_contracts.py", line 214, in test_io_counters
    for k in psutil.disk_io_counters(perdisk=True):
  File "/usr/lib/python3.8/site-packages/psutil/__init__.py", line 2168, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1125, in disk_io_counters
    for entry in gen:
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1098, in read_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line ' 259       0 nvme0n1 22389 22391 1604445 8411 7761 6043 512586 11004 0 13340 11377 0 0 0 0 573 3591\n'

======================================================================
ERROR: psutil.tests.test_system.TestSystemAPIs.test_disk_io_counters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/psutil/tests/test_system.py", line 702, in test_disk_io_counters
    ret = psutil.disk_io_counters(perdisk=False)
  File "/usr/lib/python3.8/site-packages/psutil/__init__.py", line 2168, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1125, in disk_io_counters
    for entry in gen:
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1098, in read_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line ' 259       0 nvme0n1 22389 22391 1604445 8411 7761 6043 512586 11004 0 13340 11377 0 0 0 0 573 3591\n'

======================================================================
ERROR: psutil.tests.test_system.TestSystemAPIs.test_net_if_addrs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/psutil/tests/test_system.py", line 600, in test_net_if_addrs
    if nic_stats[nic].isup:
KeyError: 'enp4s0'

======================================================================
ERROR: psutil.tests.test_misc.TestMisc.test_serialization
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/psutil/tests/test_misc.py", line 365, in test_serialization
    check(psutil.disk_io_counters())
  File "/usr/lib/python3.8/site-packages/psutil/__init__.py", line 2168, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1125, in disk_io_counters
    for entry in gen:
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1098, in read_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line ' 259       0 nvme0n1 22389 22391 1604445 8411 7762 6043 512594 11005 0 13344 11377 0 0 0 0 573 3591\n'

======================================================================
ERROR: psutil.tests.test_misc.TestWrapNumbers.test_cache_clear_public_apis
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/psutil/tests/test_misc.py", line 626, in test_cache_clear_public_apis
    if not psutil.disk_io_counters() or not psutil.net_io_counters():
  File "/usr/lib/python3.8/site-packages/psutil/__init__.py", line 2168, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1125, in disk_io_counters
    for entry in gen:
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1098, in read_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line ' 259       0 nvme0n1 22389 22391 1604445 8411 7764 6061 512754 11009 0 13350 11380 0 0 0 0 574 3593\n'

----------------------------------------------------------------------
Ran 542 tests in 5.107s

FAILED (errors=7, skipped=147)
```

It could very well be an issue with the kernel upgrade (I will downgrade and test again).

**Comment by giampaolo** [comment]
Fixed in https://github.com/giampaolo/psutil/commit/796b2dda2e0d8751eee0a4d16ab8c027839f8908.
