### ISSUE TITLE
[OS] ImportError: cannot import name '_psutil_linux' on ppc64 RHEL8 LE

### ISSUE THREAD

**Issue by srikanthjoshi** [giampaolo/psutil#1689]
**Platform**
* { OS version } - RHEL8
* { psutil version: python3 -c "import psutil; print(psutil.__version__)" }
* { python version } 3.6.8

**Bug description**
I am trying to configure airflow on IBM POWER platform which is with ppc64 architecture. It is failing with error - "ImportError: cannot import name '_psutil_linux'"

I just tried to import psutil in python, even that is also giving same error :

(srikanth) [root@brazossrik01 psutil]# python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:34:02) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/srikanth/lib/python3.6/site-packages/psutil/__init__.py", line 96, in <module>
    from . import _pslinux as _psplatform
  File "/root/anaconda3/envs/srikanth/lib/python3.6/site-packages/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: cannot import name '_psutil_linux'
>>> 

I am assuming the problem seems to be It looks like we don't have psutil built for ppc64 architecture.

If not, please let me know what is the issue.

**Test results**
{ output of `python -c psutil.tests` (failures only, not full result) }

**Comment by JavaScriptDude** [comment]
Same here on Ubuntu 18.04:

```
% python3
Python 3.7.3 (default, May 19 2019, 22:17:35) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 100, in <module>
    from . import _pslinux as _psplatform
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: cannot import name '_psutil_linux' from 'psutil' (/usr/lib/python3/dist-packages/psutil/__init__.py)
>>> 
```

I tried the [purge script](https://github.com/giampaolo/psutil/blob/master/scripts/internal/purge_installation.py) from another issue and re-installing and it had no effect. Same problem.

**Comment by JavaScriptDude** [comment]
Note: I was able to resolve by re-installing my python3.7 files using a PPA and then installing psutil in user mode (`python3.7 -m pip install --user psutil`). Once I did this, it worked fine.  However, I still have not figured out how to get it working from a cron job. Seems like a different issue as it just cannot find the package and others I tested.

**Comment by giampaolo** [comment]
There's no _psutil_linux module anymore: the C extension builds as a single _psutil since 0330c813, so this import error can't happen. Both of you also got it working again by reinstalling Python, which points at the install rather than psutil. Closing.
