### ISSUE TITLE
Having issue while installing pstuil in pycharm on windows

### ISSUE THREAD

**Issue by pseemaJohn** [giampaolo/psutil#1719]
Collecting psutil
  Using cached https://files.pythonhosted.org/packages/c4/b8/3512f0e93e0db23a71d82485ba256071ebef99b227351f0f5540f744af41/psutil-5.7.0.tar.gz
Installing collected packages: psutil
  Running setup.py install for psutil: started
    Running setup.py install for psutil: finished with status 'error'
    Complete output from command C:\Users\pseem\PycharmProjects\FirstProj\venv\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\pseem\\AppData\\Local\\Temp\\pycharm-packaging\\psutil\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\pseem\AppData\Local\Temp\pip-record-d72bk79o\install-record.txt --single-version-externally-managed --compile --install-headers C:\Users\pseem\PycharmProjects\FirstProj\venv\include\site\python3.8\psutil:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.8
    creating build\lib.win32-3.8\psutil
    copying psutil\_common.py -> build\lib.win32-3.8\psutil
    copying psutil\_compat.py -> build\lib.win32-3.8\psutil
    copying psutil\_psaix.py -> build\lib.win32-3.8\psutil
    copying psutil\_psbsd.py -> build\lib.win32-3.8\psutil
    copying psutil\_pslinux.py -> build\lib.win32-3.8\psutil
    copying psutil\_psosx.py -> build\lib.win32-3.8\psutil
    copying psutil\_psposix.py -> build\lib.win32-3.8\psutil
    copying psutil\_pssunos.py -> build\lib.win32-3.8\psutil
    copying psutil\_pswindows.py -> build\lib.win32-3.8\psutil
    copying psutil\__init__.py -> build\lib.win32-3.8\psutil
    creating build\lib.win32-3.8\psutil\tests
    copying psutil\tests\runner.py -> build\lib.win32-3.8\psutil\tests
    copying psutil\tests\test_aix.py -> build\lib.win32-3.8\psutil\tests
    copying psutil\tests\test_bsd.py -> build\lib.win32-3.8\psutil\tests
    copying psutil\tests\test_connections.py -> build\lib.win32-3.8\psutil\tests
    copying psutil\tests\test_contracts.py -> build\lib.win32-3.8\psutil\tests
    copying psutil\tests\test_linux.py -> build\lib.win32-3.8\psutil\tests
    copying psutil\tests\test_memory_leaks.py -> build\lib.win32-3.8\psutil\tests
    copying psutil\tests\test_misc.py -> build\lib.win32-3.8\psutil\tests
    copying psutil\tests\test_osx.py -> build\lib.win32-3.8\psutil\tests
    copying psutil\tests\test_posix.py -> build\lib.win32-3.8\psutil\tests
    copying psutil\tests\test_process.py -> build\lib.win32-3.8\psutil\tests
    copying psutil\tests\test_sunos.py -> build\lib.win32-3.8\psutil\tests
    copying psutil\tests\test_system.py -> build\lib.win32-3.8\psutil\tests
    copying psutil\tests\test_unicode.py -> build\lib.win32-3.8\psutil\tests
    copying psutil\tests\test_windows.py -> build\lib.win32-3.8\psutil\tests
    copying psutil\tests\__init__.py -> build\lib.win32-3.8\psutil\tests
    copying psutil\tests\__main__.py -> build\lib.win32-3.8\psutil\tests
    warning: build_py: byte-compiling is disabled, skipping.
    
    running build_ext
    building 'psutil._psutil_windows' extension
    Traceback (most recent call last):
      File "C:\Users\pseem\PycharmProjects\FirstProj\venv\lib\site-packages\setuptools-40.8.0-py3.8.egg\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
    IndexError: list index out of range
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Users\pseem\AppData\Local\Programs\Python\Python38-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\pseem\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\pseem\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\pseem\PycharmProjects\FirstProj\venv\lib\site-packages\setuptools-40.8.0-py3.8.egg\setuptools\command\install.py", line 61, in run
      File "C:\Users\pseem\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\pseem\AppData\Local\Programs\Python\Python38-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\pseem\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\pseem\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\pseem\AppData\Local\Programs\Python\Python38-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\pseem\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\pseem\PycharmProjects\FirstProj\venv\lib\site-packages\setuptools-40.8.0-py3.8.egg\setuptools\command\build_ext.py", line 78, in run
      File "C:\Users\pseem\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "C:\Users\pseem\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "C:\Users\pseem\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "C:\Users\pseem\PycharmProjects\FirstProj\venv\lib\site-packages\setuptools-40.8.0-py3.8.egg\setuptools\command\build_ext.py", line 199, in build_extension
      File "C:\Users\pseem\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\build_ext.py", line 528, in build_extension
        objects = self.compiler.compile(sources,
      File "C:\Users\pseem\AppData\Local\Programs\Python\Python38-32\lib\distutils\_msvccompiler.py", line 360, in compile
        self.initialize()
      File "C:\Users\pseem\AppData\Local\Programs\Python\Python38-32\lib\distutils\_msvccompiler.py", line 253, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\Users\pseem\PycharmProjects\FirstProj\venv\lib\site-packages\setuptools-40.8.0-py3.8.egg\setuptools\msvc.py", line 185, in msvc14_get_vc_env
      File "C:\Users\pseem\PycharmProjects\FirstProj\venv\lib\site-packages\setuptools-40.8.0-py3.8.egg\setuptools\msvc.py", line 843, in __init__
      File "C:\Users\pseem\PycharmProjects\FirstProj\venv\lib\site-packages\setuptools-40.8.0-py3.8.egg\setuptools\msvc.py", line 485, in __init__
      File "C:\Users\pseem\PycharmProjects\FirstProj\venv\lib\site-packages\setuptools-40.8.0-py3.8.egg\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Users\pseem\AppData\Local\Temp\pycharm-packaging\psutil\setup.py", line 393, in main
        setup(**kwargs)
      File "C:\Users\pseem\PycharmProjects\FirstProj\venv\lib\site-packages\setuptools-40.8.0-py3.8.egg\setuptools\__init__.py", line 145, in setup
    
      File "C:\Users\pseem\AppData\Local\Programs\Python\Python38-32\lib\distutils\core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\pseem\AppData\Local\Temp\pycharm-packaging\psutil\setup.py", line 426, in <module>
        main()
      File "C:\Users\pseem\AppData\Local\Temp\pycharm-packaging\psutil\setup.py", line 422, in main
        print(hilite(s, ok=False), file=sys.stderr)
    TypeError: hilite() got an unexpected keyword argument 'ok'
    
    ----------------------------------------

Command "C:\Users\pseem\PycharmProjects\FirstProj\venv\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\pseem\\AppData\\Local\\Temp\\pycharm-packaging\\psutil\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\pseem\AppData\Local\Temp\pip-record-d72bk79o\install-record.txt --single-version-externally-managed --compile --install-headers C:\Users\pseem\PycharmProjects\FirstProj\venv\include\site\python3.8\psutil" failed with error code 1 in C:\Users\pseem\AppData\Local\Temp\pycharm-packaging\psutil\

**Comment by pseemaJohn** [comment]
Sorry I opened this issue on here, I will open it under issues through my profile
