### ISSUE TITLE
[LINUX] pypy -m pip install psutil fails

### ISSUE THREAD

**Issue by nkpro2000sr** [giampaolo/psutil#1720]
in Linux + PyPy `pypy -m pip install psutil` fails  
```bash
$ pip install psutil
DEPRECATION: A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting psutil
  Using cached psutil-5.7.0.tar.gz (449 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/elcot/.pyenv/versions/pypy-5.7.1/envs/check/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-WpZ3yC/psutil/setup.py'"'"'; __file__='"'"'/tmp/pip-install-WpZ3yC/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-WpZ3yC/psutil/pip-egg-info
         cwd: /tmp/pip-install-WpZ3yC/psutil/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<module>", line 1, in <module>
      File "/tmp/pip-install-WpZ3yC/psutil/setup.py", line 46, in <module>
        from _compat import PY3  # NOQA
      File "/tmp/pip-install-WpZ3yC/psutil/psutil/_compat.py", line 120, in <module>
        "broken / incompatible Python implementation, see: "
    RuntimeError: broken / incompatible Python implementation, see: https://github.com/giampaolo/psutil/issues/1659
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
but it works fine with psutil <= 5.6.7

**Comment by giampaolo** [comment]
I remember this was fixed in a more recent pypy 2.7 versions.
