### ISSUE TITLE
[win10] access denied 5.7.0, 5.6.2 worked

### ISSUE THREAD

**Issue by shamashii** [giampaolo/psutil#1723]
**windows**
* { win10 1803 x64 }
* { psutil version: 5.7.0 }
* { python version 3.7.2 32bit }

**Bug description**
```
import psutil
import subprocess
import time


processnames = []


for process in psutil.process_iter():

    processnames.append(process.name())
    

```

**Test results**
```
============ RESTART: C:/Users/Administrator/Desktop/untitled.py ============
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psutil\_common.py", line 449, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psutil\_common.py", line 452, in wrapper
    return fun(self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psutil\_pswindows.py", line 766, in exe
    exe = cext.proc_exe(self.pid)
PermissionError: [WinError 24] 程序发出命令，但命令长度不正确。: '(originated from NtQuerySystemInformation)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/untitled.py", line 11, in <module>
    processnames.append(process.name())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psutil\__init__.py", line 630, in name
    name = self._proc.name()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psutil\_pswindows.py", line 750, in name
    return os.path.basename(self.exe())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=8336)
>>> 

```

which, pid=8336 is WindowsInternal.ComposableShell.Experiences.TextInput.InputApp.exe
downgrade psutil to 5.6.2 worked

**Comment by fengerzh** [comment]
confirmed. 5.6.7 cannot work, but 5.6.2 can work.

**Comment by giampaolo** [comment]
Closing as outdated. `name()` and `process_iter()` were basically rewritten since then.
