### ISSUE TITLE
[FreeBSD] memory leaks in different functions

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#1730]
https://github.com/giampaolo/psutil/runs/610640496

```
======================================================================
FAIL: psutil.tests.test_memory_leaks.TestModuleFunctionsLeaks.test_disk_io_counters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/psutil/tests/test_memory_leaks.py", line 410, in test_disk_io_counters
    self.execute(lambda: psutil.disk_io_counters(nowrap=False))
  File "/tmp/cirrus-ci-build/psutil/tests/__init__.py", line 922, in execute
    raise self.fail(msg)
AssertionError: +580.0K memory increase after 1200 calls; +584.0K after another 132337 calls over 3.0 secs

======================================================================
FAIL: psutil.tests.test_memory_leaks.TestModuleFunctionsLeaks.test_net_connections
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/psutil/tests/test_memory_leaks.py", line 431, in test_net_connections
    self.execute(psutil.net_connections)
  File "/tmp/cirrus-ci-build/psutil/tests/__init__.py", line 922, in execute
    raise self.fail(msg)
AssertionError: +40.0K memory increase after 1200 calls; +76.0K after another 14942 calls over 3.0 secs

----------------------------------------------------------------------
```
Intermittently I also saw failures for `net_io_counters()`.

**Comment by giampaolo** [comment]
This was probably a false positive, fixed when I introduced the new memleak test class.
