### ISSUE TITLE
[OS] Mac psutil with exe attrs throws FileNotFoundError exception 

### ISSUE THREAD

**Issue by ajinabraham** [giampaolo/psutil#1738]
**Platform**
* Mac OS Mojave 10.14.6
* Psutil Version 5.7.0
* Python 3.7.7

**Bug description**
```
Python 3.7.7 (default, Apr 25 2020, 01:55:29)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.__version__
'5.7.0'
>>> x = list(psutil.process_iter(attrs=['name', 'cmdline']))
>>>
>>> x = list(psutil.process_iter(attrs=['name', 'exe', 'cmdline']))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "******/venv/lib/python3.7/site-packages/psutil/__init__.py", line 1457, in process_iter
    yield add(pid)
  File "******/venv/lib/python3.7/site-packages/psutil/__init__.py", line 1434, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
  File "******/venv/lib/python3.7/site-packages/psutil/__init__.py", line 538, in as_dict
    ret = meth()
  File "******/venv/lib/python3.7/site-packages/psutil/__init__.py", line 673, in exe
    exe = self._proc.exe()
  File "******/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 334, in wrapper
    return fun(self, *args, **kwargs)
  File "******/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 413, in exe
    return cext.proc_exe(self.pid)
FileNotFoundError: [Errno 2] No such file or directory (originated from proc_pidpath())
```

**Test results**
```
======================================================================
ERROR: setUpClass (psutil.tests.test_unicode.TestFSAPIsWithInvalidPath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_unicode.py", line 170, in setUpClass
    create_exe(cls.funky_name)
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 781, in create_exe
    shutil.copyfile(PYTHON_EXE, outpath)
  File "/Users/ajinabraham/.pyenv/versions/3.7.7/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 92] Illegal byte sequence: '******/@psutil-test-75208f\udcc0\udc80'

======================================================================
ERROR: psutil.tests.test_misc.TestMisc.test_setup_script
----------------------------------------------------------------------
Traceback (most recent call last):
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 376, in test_setup_script
    module = import_module_by_path(setup_py)
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 1054, in import_module_by_path
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 859, in get_code
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '******/venv/lib/python3.7/site-packages/setup.py'

======================================================================
ERROR: psutil.tests.test_misc.TestScripts.test_battery
----------------------------------------------------------------------
Traceback (most recent call last):
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 784, in test_battery
    self.assert_stdout('battery.py')
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 667, in assert_stdout
    out = sh(cmd, **kwargs).strip()
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 305, in wrapper
    return fun(*args, **kwargs)
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 457, in sh
    raise RuntimeError(stderr)
RuntimeError: ******/venv/bin/python: can't open file '******/venv/lib/python3.7/site-packages/scripts/battery.py': [Errno 2] No such file or directory


======================================================================
ERROR: psutil.tests.test_misc.TestScripts.test_coverage
----------------------------------------------------------------------
Traceback (most recent call last):
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 690, in test_coverage
    for name in os.listdir(SCRIPTS_DIR):
FileNotFoundError: [Errno 2] No such file or directory: '******/venv/lib/python3.7/site-packages/scripts'

======================================================================
ERROR: psutil.tests.test_misc.TestScripts.test_cpu_distribution
----------------------------------------------------------------------
Traceback (most recent call last):
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 765, in test_cpu_distribution
    self.assert_syntax('cpu_distribution.py')
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 680, in assert_syntax
    f = open(exe, 'rt', encoding='utf8')
FileNotFoundError: [Errno 2] No such file or directory: '******/venv/lib/python3.7/site-packages/scripts/cpu_distribution.py'

======================================================================
ERROR: psutil.tests.test_misc.TestScripts.test_disk_usage
----------------------------------------------------------------------
Traceback (most recent call last):
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 706, in test_disk_usage
    self.assert_stdout('disk_usage.py')
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 667, in assert_stdout
    out = sh(cmd, **kwargs).strip()
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 305, in wrapper
    return fun(*args, **kwargs)
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 457, in sh
    raise RuntimeError(stderr)
RuntimeError: ******/venv/bin/python: can't open file '******/venv/lib/python3.7/site-packages/scripts/disk_usage.py': [Errno 2] No such file or directory


======================================================================
ERROR: psutil.tests.test_misc.TestScripts.test_executable
----------------------------------------------------------------------
Traceback (most recent call last):
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 699, in test_executable
    for name in os.listdir(SCRIPTS_DIR):
FileNotFoundError: [Errno 2] No such file or directory: '******/venv/lib/python3.7/site-packages/scripts'

======================================================================
ERROR: psutil.tests.test_misc.TestScripts.test_free
----------------------------------------------------------------------
Traceback (most recent call last):
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 709, in test_free
    self.assert_stdout('free.py')
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 667, in assert_stdout
    out = sh(cmd, **kwargs).strip()
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 305, in wrapper
    return fun(*args, **kwargs)
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 457, in sh
    raise RuntimeError(stderr)
RuntimeError: ******/venv/bin/python: can't open file '******/venv/lib/python3.7/site-packages/scripts/free.py': [Errno 2] No such file or directory


======================================================================
ERROR: psutil.tests.test_misc.TestScripts.test_ifconfig
----------------------------------------------------------------------
Traceback (most recent call last):
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 733, in test_ifconfig
    self.assert_stdout('ifconfig.py')
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 667, in assert_stdout
    out = sh(cmd, **kwargs).strip()
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 305, in wrapper
    return fun(*args, **kwargs)
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 457, in sh
    raise RuntimeError(stderr)
RuntimeError: ******/venv/bin/python: can't open file '******/venv/lib/python3.7/site-packages/scripts/ifconfig.py': [Errno 2] No such file or directory


======================================================================
ERROR: psutil.tests.test_misc.TestScripts.test_iotop
----------------------------------------------------------------------
Traceback (most recent call last):
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 754, in test_iotop
    self.assert_syntax('iotop.py')
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 680, in assert_syntax
    f = open(exe, 'rt', encoding='utf8')
FileNotFoundError: [Errno 2] No such file or directory: '******/venv/lib/python3.7/site-packages/scripts/iotop.py'

======================================================================
ERROR: psutil.tests.test_misc.TestScripts.test_killall
----------------------------------------------------------------------
Traceback (most recent call last):
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 745, in test_killall
    self.assert_syntax('killall.py')
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 680, in assert_syntax
    f = open(exe, 'rt', encoding='utf8')
FileNotFoundError: [Errno 2] No such file or directory: '******/venv/lib/python3.7/site-packages/scripts/killall.py'

======================================================================
ERROR: psutil.tests.test_misc.TestScripts.test_meminfo
----------------------------------------------------------------------
Traceback (most recent call last):
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 712, in test_meminfo
    self.assert_stdout('meminfo.py')
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 667, in assert_stdout
    out = sh(cmd, **kwargs).strip()
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 305, in wrapper
    return fun(*args, **kwargs)
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 457, in sh
    raise RuntimeError(stderr)
RuntimeError: ******/venv/bin/python: can't open file '******/venv/lib/python3.7/site-packages/scripts/meminfo.py': [Errno 2] No such file or directory


======================================================================
ERROR: psutil.tests.test_misc.TestScripts.test_netstat
----------------------------------------------------------------------
Traceback (most recent call last):
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 728, in test_netstat
    self.assert_stdout('netstat.py')
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 667, in assert_stdout
    out = sh(cmd, **kwargs).strip()
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 305, in wrapper
    return fun(*args, **kwargs)
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 457, in sh
    raise RuntimeError(stderr)
RuntimeError: ******/venv/bin/python: can't open file '******/venv/lib/python3.7/site-packages/scripts/netstat.py': [Errno 2] No such file or directory


======================================================================
ERROR: psutil.tests.test_misc.TestScripts.test_nettop
----------------------------------------------------------------------
Traceback (most recent call last):
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 748, in test_nettop
    self.assert_syntax('nettop.py')
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 680, in assert_syntax
    f = open(exe, 'rt', encoding='utf8')
FileNotFoundError: [Errno 2] No such file or directory: '******/venv/lib/python3.7/site-packages/scripts/nettop.py'

======================================================================
ERROR: psutil.tests.test_misc.TestScripts.test_pidof
----------------------------------------------------------------------
Traceback (most recent call last):
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 757, in test_pidof
    output = self.assert_stdout('pidof.py', psutil.Process().name())
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 667, in assert_stdout
    out = sh(cmd, **kwargs).strip()
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 305, in wrapper
    return fun(*args, **kwargs)
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 457, in sh
    raise RuntimeError(stderr)
RuntimeError: ******/venv/bin/python: can't open file '******/venv/lib/python3.7/site-packages/scripts/pidof.py': [Errno 2] No such file or directory


======================================================================
ERROR: psutil.tests.test_misc.TestScripts.test_procinfo
----------------------------------------------------------------------
Traceback (most recent call last):
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 715, in test_procinfo
    self.assert_stdout('procinfo.py', str(os.getpid()))
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 667, in assert_stdout
    out = sh(cmd, **kwargs).strip()
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 305, in wrapper
    return fun(*args, **kwargs)
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 457, in sh
    raise RuntimeError(stderr)
RuntimeError: ******/venv/bin/python: can't open file '******/venv/lib/python3.7/site-packages/scripts/procinfo.py': [Errno 2] No such file or directory


======================================================================
ERROR: psutil.tests.test_misc.TestScripts.test_procsmem
----------------------------------------------------------------------
Traceback (most recent call last):
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 742, in test_procsmem
    self.assert_stdout('procsmem.py', stderr=DEVNULL)
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 667, in assert_stdout
    out = sh(cmd, **kwargs).strip()
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 305, in wrapper
    return fun(*args, **kwargs)
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 457, in sh
    raise RuntimeError(stderr)
RuntimeError: None

======================================================================
ERROR: psutil.tests.test_misc.TestScripts.test_ps
----------------------------------------------------------------------
Traceback (most recent call last):
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 722, in test_ps
    self.assert_stdout('ps.py')
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 667, in assert_stdout
    out = sh(cmd, **kwargs).strip()
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 305, in wrapper
    return fun(*args, **kwargs)
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 457, in sh
    raise RuntimeError(stderr)
RuntimeError: ******/venv/bin/python: can't open file '******/venv/lib/python3.7/site-packages/scripts/ps.py': [Errno 2] No such file or directory


======================================================================
ERROR: psutil.tests.test_misc.TestScripts.test_pstree
----------------------------------------------------------------------
Traceback (most recent call last):
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 725, in test_pstree
    self.assert_stdout('pstree.py')
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 667, in assert_stdout
    out = sh(cmd, **kwargs).strip()
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 305, in wrapper
    return fun(*args, **kwargs)
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 457, in sh
    raise RuntimeError(stderr)
RuntimeError: ******/venv/bin/python: can't open file '******/venv/lib/python3.7/site-packages/scripts/pstree.py': [Errno 2] No such file or directory


======================================================================
ERROR: psutil.tests.test_misc.TestScripts.test_sensors
----------------------------------------------------------------------
Traceback (most recent call last):
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 787, in test_sensors
    self.assert_stdout('sensors.py')
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 667, in assert_stdout
    out = sh(cmd, **kwargs).strip()
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 305, in wrapper
    return fun(*args, **kwargs)
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 457, in sh
    raise RuntimeError(stderr)
RuntimeError: ******/venv/bin/python: can't open file '******/venv/lib/python3.7/site-packages/scripts/sensors.py': [Errno 2] No such file or directory


======================================================================
ERROR: psutil.tests.test_misc.TestScripts.test_top
----------------------------------------------------------------------
Traceback (most recent call last):
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 751, in test_top
    self.assert_syntax('top.py')
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 680, in assert_syntax
    f = open(exe, 'rt', encoding='utf8')
FileNotFoundError: [Errno 2] No such file or directory: '******/venv/lib/python3.7/site-packages/scripts/top.py'

======================================================================
ERROR: psutil.tests.test_misc.TestScripts.test_who
----------------------------------------------------------------------
Traceback (most recent call last):
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 719, in test_who
    self.assert_stdout('who.py')
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 667, in assert_stdout
    out = sh(cmd, **kwargs).strip()
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 305, in wrapper
    return fun(*args, **kwargs)
  File "******/venv/lib/python3.7/site-packages/psutil/tests/__init__.py", line 457, in sh
    raise RuntimeError(stderr)
RuntimeError: ******/venv/bin/python: can't open file '******/venv/lib/python3.7/site-packages/scripts/who.py': [Errno 2] No such file or directory


======================================================================
FAIL: psutil.tests.test_contracts.TestFetchAllProcesses.test_fetch_all
----------------------------------------------------------------------
Traceback (most recent call last):
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_contracts.py", line 398, in test_fetch_all
    meth(ret, p)
  File "******/venv/lib/python3.7/site-packages/psutil/tests/test_contracts.py", line 426, in exe
    assert os.access(ret, os.X_OK)
AssertionError

----------------------------------------------------------------------
```

**Comment by giampaolo** [comment]
Please run this:

```
import psutil
for p in psutil.process_iter():
    try:
        p.exe()
    except psutil.AccessDenied:
        pass
```

Still the same error?

**Comment by ajinabraham** [comment]
Yes!
Is this expected?

```
....
...
'/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Support/mdworker'
'/System/Library/PrivateFrameworks/CommerceKit.framework/Versions/A/Resources/storeinstalld'
'/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Support/mdwrite'
'/System/Library/Frameworks/Metal.framework/Versions/A/XPCServices/MTLCompilerService.xpc/Contents/MacOS/MTLCompilerService'
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "******/venv/lib/python3.7/site-packages/psutil/__init__.py", line 673, in exe
    exe = self._proc.exe()
  File "******/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 334, in wrapper
    return fun(self, *args, **kwargs)
  File "******/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 413, in exe
    return cext.proc_exe(self.pid)
FileNotFoundError: [Errno 2] No such file or directory (originated from proc_pidpath())
```

**Comment by giampaolo** [comment]
No. =)
Can you also check if the PID exists after you catch that exception?

```
psutil.pid_exists(p.pid)
```

**Comment by ajinabraham** [comment]
```
Traceback (most recent call last):
  File "******/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 352, in catch_zombie
    yield
  File "******/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 413, in exe
    return cext.proc_exe(self.pid)
ProcessLookupError: [Errno 3] No such process (originated from proc_pidpath())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "******/venv/lib/python3.7/site-packages/psutil/__init__.py", line 673, in exe
    exe = self._proc.exe()
  File "******/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 334, in wrapper
    return fun(self, *args, **kwargs)
  File "******/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 413, in exe
    return cext.proc_exe(self.pid)
  File "/****/.pyenv/versions/3.7.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "******/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 363, in catch_zombie
    raise ZombieProcess(proc.pid, proc._name, proc._ppid)
psutil.ZombieProcess: psutil.ZombieProcess process still exists but it's a zombie (pid=52463)
```

**Comment by giampaolo** [comment]
That's legitimate. Change it to:

```python
import psutil
for p in psutil.process_iter():
    try:
        p.exe()
    except (psutil.NoSuchProcess, psutil.ZombieProcess):
        pass
    except psutil.AccessDenied:
        pass
    except FileNotFoundError:
        print(f'{p} - PID exists {psutil.pid_exists(p.pid)}')
```

**Comment by ajinabraham** [comment]
That works without any exceptions.

**Comment by giampaolo** [comment]
It doesn't print anything? What happened to FileNotFoundError?

**Comment by ajinabraham** [comment]
Actually my bad. Haven't noticed that the print was under the exception.

There is a lot of files (around 540) getting printed from the following locations.
```
/Applications/...
/usr/...
/sbin/...
/System/Library/...
/Library/...
```

**Comment by gonewest818** [comment]
I had exactly the same symptom:
* macos 10.15.5
* psutil 5.7.0
* python 3.7.7

```
>>> for p in psutil.process_iter():
...     try:
...         _ = p.exe()
...     except (psutil.NoSuchProcess, psutil.ZombieProcess):
...         pass
...     except psutil.AccessDenied:
...         pass
...     except FileNotFoundError:
...         print(f'{p} - PID exists {psutil.pid_exists(p.pid)}')
... 
psutil.Process(pid=25143, name='python3.7', started='18:40:56') - PID exists True
psutil.Process(pid=25146, name='python3.7', started='18:40:57') - PID exists True
>>> 
```

In my case those two python processes (pids 25143 and 25146) were actually `jedi` processes started days ago when I last launched emacs.  Jedi was running from a python interpreter I compiled from source, but I had subsequently deleted that python install. So the pids survived but their executables and site-packages, etc were gone.

Whereas the `psutil.process_iter()` loop was running in different process on a newer build of python 3.7.7 and with libs and site-packages in a completely different path.

**Comment by giampaolo** [comment]
I should have fixed this. Please reopen if I didn't.
