### ISSUE TITLE
send_signal() doesn't rise proper error on missing parameter

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#1748]
This happens if the process was already killed. The reason is because it's decorated with a function which checks the process is not gone **before** checking the parameter which is declared as `*args`.

```python
>>> import psutil
>>> from psutil.tests import spawn_testproc
>>> sp = spawn_testproc()
>>> p = psutil.Process(sp.pid)
>>> p.terminate()
>>> p.wait()
<Negsignal.SIGTERM: -15>
>>> p.send_signal()  # should raise TypeError "missing sig parameter"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/giampaolo/svn/psutil/psutil/__init__.py", line 288, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=3893)
```

**Comment by giampaolo** [comment]
Fixed. send_signal() takes an explicit 'sig' argument now, so calling it with no args raises TypeError before anything else runs:

    TypeError: Process.send_signal() missing 1 required positional argument: 'sig'
