### ISSUE TITLE
test_get_connections_all failure on OS X r1054

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#176]
_From [jlo...@gmail.com](https://code.google.com/u/104710261032439836788/) on June 28, 2011 05:46:20_
    
        Error in test case test_get_connections_all() on OS X r1054 
    ===================================================
        ERROR: test_get_connections_all (__main__.TestCase)
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "test/test_psutil.py", line 145, in inner
            return fun(self, *args, **kwargs)
          File "test/test_psutil.py", line 1034, in test_get_connections_all
            s.bind((conn.local_address[0], 0))
          File "<string>", line 1, in bind
        error: [Errno 49] Can't assign requested address
    
        ----------------------------------------------------------------------
    
    Printing the address and conn type when this exception occurs shows: 
    
        conn.local_address[0] is 192.168.101.129 and conn.type is 1
    
    I'm not sure what this means or what the bind to the local address is supposed 
    to be testing in the first place.
    
_Original issue: http://code.google.com/p/psutil/issues/detail?id=176_

**Comment by giampaolo** [comment]
Outdated
