### ISSUE TITLE
OSError: [WinError 0] The operation completed successfully: '(originated from OpenProcess)'

### ISSUE THREAD

**Issue by CanML** [giampaolo/psutil#1770]
Windows Server 2012 R2
psutil version 5.7.0
Python version 3.8.3

I just recently created a fresh environment after upgrading to Python 3.8 and am now getting this error (totally fresh psutil install). My previous version which was stable and working with my script (which hasn't changed at all) for a long time with Python 3.6 was psutil 5.4.0. However, if I try to install previous versions with my current Python 3.8.3 environment I seem to be getting build errors related to VC++ 14.0.

I have seen the below error in other threads here but it seemed to be fixed for most people in another recent build - not sure why I'm getting it now.

Not expecting anything but hoping this can help nail things down or add it for others experiencing a similar issue.
```
C:\Python38\envs\xyz_env\Scripts\python.exe C:/XYZ/xyz_watchdog.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\python38\lib\threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "C:/XYZ/xyz_watchdog.py", line 13, in check_and_launch_xyz
    if process.cmdline() == process_cmdline_to_look_for:
  File "C:\Python38\envs\xyz_env\lib\site-packages\psutil\__init__.py", line 690, in cmdline
    return self._proc.cmdline()
  File "C:\Python38\envs\xyz_env\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
  File "C:\Python38\envs\xyz_env\lib\site-packages\psutil\_pswindows.py", line 671, in convert_oserror
    raise exc
  File "C:\Python38\envs\xyz_env\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Python38\envs\xyz_env\lib\site-packages\psutil\_pswindows.py", line 695, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Python38\envs\xyz_env\lib\site-packages\psutil\_pswindows.py", line 780, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=True)
OSError: [WinError 0] The operation completed successfully: '(originated from OpenProcess)'
...
```

**Comment by CanML** [comment]
Update: I've confirmed it works just fine on 5.6.7, but again confirmed it breaks with the error mentioned in the original post if I use 5.7.0.

**Comment by codeyourdream** [comment]
Got the same issue with 5.7.0 with a slightly different trace:

File "D:\Python38\lib\site-packages\psutil\__init__.py", line 1457, in process_iter
  File "D:\Python38\lib\site-packages\psutil\__init__.py", line 1432, in add
  File "D:\Python38\lib\site-packages\psutil\__init__.py", line 346, in init
  File "D:\Python38\lib\site-packages\psutil\__init__.py", line 373, in _init
  File "D:\Python38\lib\site-packages\psutil\__init__.py", line 723, in create_time
  File "D:\Python38\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
  File "D:\Python38\lib\site-packages\psutil\_pswindows.py", line 671, in convert_oserror
  File "D:\Python38\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
  File "D:\Python38\lib\site-packages\psutil\_pswindows.py", line 933, in create_time
OSError: [WinError 0] Операция успешно завершена: '(originated from OpenProcess)'

This happened on only one computer with Windows 7, doesn't happen on Win10 test boxes and other Win7 boxes.

**Comment by NavyTitanium** [comment]
I'm still having this issue with psutil version 5.7.2 using Python 3.7.5 on W7 SP1 when running as non-administrator

```
Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> [p for p in psutil.process_iter()]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
  File "C:\Users\lab\AppData\Local\Programs\Python\Python37\lib\site-packages\psutil\__init__.py", line 1459, in process_iter
    yield add(pid)
  File "C:\Users\lab\AppData\Local\Programs\Python\Python37\lib\site-packages\psutil\__init__.py", line 1434, in add
    proc = Process(pid)
  File "C:\Users\lab\AppData\Local\Programs\Python\Python37\lib\site-packages\psutil\__init__.py", line 343, in __init__
    self._init(pid)
  File "C:\Users\lab\AppData\Local\Programs\Python\Python37\lib\site-packages\psutil\__init__.py", line 371, in _init
    self.create_time()
  File "C:\Users\lab\AppData\Local\Programs\Python\Python37\lib\site-packages\psutil\__init__.py", line 727, in create_time
    self._create_time = self._proc.create_time()
  File "C:\Users\lab\AppData\Local\Programs\Python\Python37\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
  File "C:\Users\lab\AppData\Local\Programs\Python\Python37\lib\site-packages\psutil\_pswindows.py", line 671, in convert_oserror
    raise exc
  File "C:\Users\lab\AppData\Local\Programs\Python\Python37\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\lab\AppData\Local\Programs\Python\Python37\lib\site-packages\psutil\_pswindows.py", line 933, in create_time
    user, system, created = cext.proc_times(self.pid)
OSError: [WinError 0] The operation completed successfully: '(originated from OpenProcess)'
```

**Comment by giampaolo** [comment]
What's the PID for this process and what are its permissions (username)?
It's weird `OpenProcess` returns error 0 but by googling it seems it's a permission issues, so perhaps we should turn error 0 into `AccessDenied`.

**Comment by NavyTitanium** [comment]
I had issues running other software as well, so I installed all Windows updates and now it works. So never mind my comment :) Thanks.

**Comment by giampaolo** [comment]
This should now fixed as of https://github.com/giampaolo/psutil/pull/1887.

**Comment by grintor** [comment]
I am still affected by this in version 5.8.0. Rolling back to 5.6.7 resolved the issue. Was the fix ever published to pypi?
