### ISSUE TITLE
[FreeBSD] Data collection thread failed

### ISSUE THREAD

**Issue by iron-udjin** [giampaolo/psutil#1801]
**Platform**
* FreeBSD 12.1-STABLE r363784
* psutil version: 5.7.2
* python: 3.7.8

CPU: Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz (2200.07-MHz K8-class CPU)
FreeBSD/SMP: Multiprocessor System Detected: 48 CPUs
FreeBSD/SMP: 2 package(s) x 12 core(s) x 2 hardware threads

**Bug description**
I'm trying to run [bpytop](https://github.com/aristocratos/bpytop) 1.0.1 which throws an error:
```
03/08/20 (22:02:01) | ERROR: Data collection thread failed with exception: 'utf-8' codec can't decode byte 0xff in position 153: invalid start byte
Traceback (most recent call last):
File "./bpytop.py", line 2313, in _runner
collector._collect()
File "./bpytop.py", line 2406, in _collect
if hasattr(psutil.cpu_freq(), "current"):
File "/usr/local/lib/python3.7/site-packages/psutil/init.py", line 1879, in cpu_freq
ret = _psplatform.cpu_freq()
File "/usr/local/lib/python3.7/site-packages/psutil/_psbsd.py", line 454, in cpu_freq
current, available_freq = cext.cpu_frequency(cpu)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 153: invalid start byte
03/08/20 (22:02:01) | WARNING: Exiting with errorcode (1). Runtime 0:00:03
```

**Test results**

```
======================================================================
ERROR: psutil.tests.test_system.TestCpuAPIs.test_cpu_freq
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/psutil/tests/test_system.py", line 533, in test_cpu_freq
    ls = psutil.cpu_freq(percpu=True)
  File "/usr/local/lib/python3.7/site-packages/psutil/__init__.py", line 1879, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/usr/local/lib/python3.7/site-packages/psutil/_psbsd.py", line 454, in cpu_freq
    current, available_freq = cext.cpu_frequency(cpu)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb3 in position 153: invalid start byte

======================================================================
ERROR: psutil.tests.test_system.TestNetAPIs.test_net_if_addrs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/psutil/tests/test_system.py", line 768, in test_net_if_addrs
    s.bind(sa)
OSError: [Errno 49] Can't assign requested address

======================================================================
ERROR: psutil.tests.test_misc.TestMisc.test_setup_script
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/psutil/tests/test_misc.py", line 358, in test_setup_script
    module = import_module_by_path(setup_py)
  File "/usr/local/lib/python3.7/site-packages/psutil/tests/__init__.py", line 1537, in import_module_by_path
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 859, in get_code
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/setup.py'

======================================================================
FAIL: psutil.tests.test_bsd.BSDTestCase.test_process_create_time
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/psutil/tests/test_bsd.py", line 94, in test_process_create_time
    self.assertEqual(start_ps, start_psutil)
AssertionError: 'вторник,  4 августа 2020 г. 00:14:15' != 'Tue Aug  4 00:14:15 2020'
- вторник,  4 августа 2020 г. 00:14:15
+ Tue Aug  4 00:14:15 2020


======================================================================
FAIL: psutil.tests.test_bsd.FreeBSDSystemTestCase.test_cpu_stats_ctx_switches
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/psutil/tests/test_bsd.py", line 366, in test_cpu_stats_ctx_switches
    sysctl('vm.stats.sys.v_swtch'), delta=1000)
AssertionError: 605792713 != 4900760160 within 1000 delta (4294967447 difference)

======================================================================
FAIL: psutil.tests.test_contracts.TestFetchAllProcesses.test_all
----------------------------------------------------------------------
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/psutil/_psbsd.py", line 552, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/psutil/_psbsd.py", line 903, in memory_maps
    return cext.proc_memory_maps(self.pid)
ProcessLookupError: [Errno 3] No such process (originated from kinfo_getvmmap())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/psutil/tests/test_contracts.py", line 366, in proc_info
    info[fun_name] = fun()
  File "/usr/local/lib/python3.7/site-packages/psutil/__init__.py", line 1137, in memory_maps
    it = self._proc.memory_maps()
  File "/usr/local/lib/python3.7/site-packages/psutil/_psbsd.py", line 557, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=54595, name='postgres')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/site-packages/psutil/tests/test_contracts.py", line 368, in proc_info
    check_exception(exc, proc, name, ppid)
  File "/usr/local/lib/python3.7/site-packages/psutil/tests/test_contracts.py", line 343, in check_exception
    tcase.assertProcessGone(proc)
  File "/usr/local/lib/python3.7/site-packages/psutil/tests/__init__.py", line 902, in assertProcessGone
    self.assertRaises(psutil.NoSuchProcess, psutil.Process, proc.pid)
  File "/usr/local/lib/python3.7/unittest/case.py", line 756, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/local/lib/python3.7/unittest/case.py", line 178, in handle
    callable_obj(*args, **kwargs)
  File "/usr/local/lib/python3.7/unittest/case.py", line 201, in __exit__
    self.obj_name))
  File "/usr/local/lib/python3.7/unittest/case.py", line 135, in _raiseFailure
    raise self.test_case.failureException(msg)
AssertionError: NoSuchProcess not raised by Process
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/psutil/tests/test_contracts.py", line 396, in test_all
    for info in self.iter_proc_info():
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
AssertionError: NoSuchProcess not raised by Process

======================================================================
FAIL: psutil.tests.test_process.TestProcess.test_terminal
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/psutil/tests/test_process.py", line 305, in test_terminal
    self.assertIsNone(terminal)
AssertionError: '/dev/pts/1' is not None

```

**Comment by giampaolo** [comment]
We no longer read the XML on FreeBSD, we ask CPU freq directly to the kernel, so this is outdated.

**Comment by giampaolo** [comment]
I got confused. The XML parsing was on another BSD. This bug appears real. Even if I can't reproduce it 7dc983db should fix it.
