### ISSUE TITLE
[Linux] FileNotFoundError: [Errno 2] No such file or directory: '/proc/21580/cmdline'

### ISSUE THREAD

**Issue by rht** [giampaolo/psutil#1811]
**Platform**
* NixOS unstable
* psutil version: 5.7.2 (latest master)
* Python 3.8.5

**Bug description**
Steps to reproduce:
Write test_psutil.py with content
```python
import psutil

def pgrep(pattern):
    for proc in psutil.process_iter():
        if pattern in ' '.join(proc.cmdline()):
            return True
    return False

pgrep('foobar')
```
Write test_psutil.sh with content
```sh
#!/usr/bin/env bash

response() {
    for ((i = 0; i < 40; i++)); do
        python3 test_psutil.py &
    done
        wait

}

time response
```

Run `test_psutil.sh`, which will sometimes work, and sometimes error with this error message
```
Traceback (most recent call last):
  File "/home/rht/code/venv/lib/python3.8/site-packages/psutil-5.7.2-py3.8-linux-x86_64.egg/psutil/_pslinux.py", line 1515, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/rht/code/venv/lib/python3.8/site-packages/psutil-5.7.2-py3.8-linux-x86_64.egg/psutil/_pslinux.py", line 1635, in cmdline
    with open_text("%s/%s/cmdline" % (self._procfs_path, self.pid)) as f:
  File "/home/rht/code/venv/lib/python3.8/site-packages/psutil-5.7.2-py3.8-linux-x86_64.egg/psutil/_common.py", line 727, in open_text
    return open(fname, "rt", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/21573/cmdline'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_psutil.py", line 9, in <module>
    pgrep('foobar')
  File "test_psutil.py", line 5, in pgrep
    if pattern in ' '.join(proc.cmdline()):
  File "/home/rht/code/venv/lib/python3.8/site-packages/psutil-5.7.2-py3.8-linux-x86_64.egg/psutil/__init__.py", line 694, in cmdline
    return self._proc.cmdline()
  File "/home/rht/code/venv/lib/python3.8/site-packages/psutil-5.7.2-py3.8-linux-x86_64.egg/psutil/_pslinux.py", line 1522, in wrapper
Traceback (most recent call last):
  File "/home/rht/code/venv/lib/python3.8/site-packages/psutil-5.7.2-py3.8-linux-x86_64.egg/psutil/_pslinux.py", line 1515, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/rht/code/venv/lib/python3.8/site-packages/psutil-5.7.2-py3.8-linux-x86_64.egg/psutil/_pslinux.py", line 1636, in cmdline
    data = f.read()
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_psutil.py", line 9, in <module>
    pgrep('foobar')
  File "test_psutil.py", line 5, in pgrep
    if pattern in ' '.join(proc.cmdline()):
  File "/home/rht/code/venv/lib/python3.8/site-packages/psutil-5.7.2-py3.8-linux-x86_64.egg/psutil/__init__.py", line 694, in cmdline
    return self._proc.cmdline()
  File "/home/rht/code/venv/lib/python3.8/site-packages/psutil-5.7.2-py3.8-linux-x86_64.egg/psutil/_pslinux.py", line 1519, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=21564)
Traceback (most recent call last):
    raise NoSuchProcess(self.pid, self._name)
  File "/home/rht/code/venv/lib/python3.8/site-packages/psutil-5.7.2-py3.8-linux-x86_64.egg/psutil/_pslinux.py", line 1515, in wrapper
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=21573)
    return fun(self, *args, **kwargs)
  File "/home/rht/code/venv/lib/python3.8/site-packages/psutil-5.7.2-py3.8-linux-x86_64.egg/psutil/_pslinux.py", line 1635, in cmdline
    with open_text("%s/%s/cmdline" % (self._procfs_path, self.pid)) as f:
  File "/home/rht/code/venv/lib/python3.8/site-packages/psutil-5.7.2-py3.8-linux-x86_64.egg/psutil/_common.py", line 727, in open_text
    return open(fname, "rt", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/21580/cmdline'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_psutil.py", line 9, in <module>
    pgrep('foobar')
  File "test_psutil.py", line 5, in pgrep
    if pattern in ' '.join(proc.cmdline()):
  File "/home/rht/code/venv/lib/python3.8/site-packages/psutil-5.7.2-py3.8-linux-x86_64.egg/psutil/__init__.py", line 694, in cmdline
    return self._proc.cmdline()
  File "/home/rht/code/venv/lib/python3.8/site-packages/psutil-5.7.2-py3.8-linux-x86_64.egg/psutil/_pslinux.py", line 1522, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=21580)

```

**Comment by rht** [comment]
Note that using native `pgrep` works with no error. But I need to use `psutil` so that my code is cross-platform.

**Comment by rht** [comment]
Possibly related: #1447.

**Comment by giampaolo** [comment]
`FileNotFoundError` gets translated to `NoSuchProcess`. That is a legitimate exception (process is gone). You should catch `NoSuchProcess` in a try/except and ignore it.

**Comment by rht** [comment]
The process is gone, but that doesn't mean that the process I am grep-ing for is gone.
Adding a try-except like this is not going to work:
```python
def pgrep(pattern):
    try:
        for proc in psutil.process_iter():
            if pattern in ' '.join(proc.cmdline()):
                return True
    except psutil.NoSuchProcess:
        pass
    return False
```

**Comment by rht** [comment]
My bad, it's supposed to be
```python
def pgrep(pattern):
    for proc in psutil.process_iter():
        try:
            if pattern in ' '.join(proc.cmdline()):
                return True
        except psutil.NoSuchProcess:
            pass
    return False
```

Correct?

**Comment by rht** [comment]
Also, ideally there should be only one exception, `NoSuchProcess`, but the library created some noise with the intermediate exceptions, which is confusing.
