### ISSUE TITLE
[LINUX] Install through pip fails

### ISSUE THREAD

**Issue by smoia** [giampaolo/psutil#1840]
**Platform**
* Linux Ubuntu 18.04.5
* psutil version 5.7.2
* Python 3.6.9

**Bug description**
Hi,
I tried to install psutil using pip, but the installation failed due to an `ImportError`:

```
~$ sudo pip3 install psutil==5.7.2
Collecting psutil==5.7.2
  Downloading psutil-5.7.2.tar.gz (460 kB)
     |████████████████████████████████| 460 kB 2.1 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6105x4n9/psutil/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6105x4n9/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-qo8rd98l
         cwd: /tmp/pip-install-6105x4n9/psutil/
    Complete output (30 lines):
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2455, in resolve
        return functools.reduce(getattr, self.attrs, module)
    AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6105x4n9/psutil/setup.py", line 434, in <module>
        main()
      File "/tmp/pip-install-6105x4n9/psutil/setup.py", line 401, in main
        setup(**kwargs)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/dist.py", line 424, in __init__
        k: v for k, v in attrs.items()
      File "/usr/lib/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/dist.py", line 694, in finalize_options
        for ep in sorted(eps, key=by_order):
      File "/usr/local/lib/python3.6/dist-packages/setuptools/dist.py", line 693, in <lambda>
        eps = map(lambda e: e.load(), pkg_resources.iter_entry_points(group))
      File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2447, in load
        return self.resolve()
      File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2457, in resolve
        raise ImportError(str(exc)) from exc
    ImportError: type object 'Distribution' has no attribute '_finalize_feature_opts'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by moseswynn** [comment]
Can you confirm which version of setuptools you have? You can find this by running `pip show setuptools`.

**Comment by smoia** [comment]
Ah, apologies! I didn't think about updating `setuptools`.
The version was `42.0.2` - which was working well for all the other packages I have around.
However, updating `setuptools` solved the issue.

Sorry again!
