### ISSUE TITLE
OSError: [WinError 0] The operation completed successfully

### ISSUE THREAD

**Issue by rhazz** [giampaolo/psutil#1877]
**Platform**
* { Windows nt 2012 }
* { psutil version: 5.7.3" }
* { python 3.8.2}

**Bug description**
Version 5.7.3 again presented this error corrected in version 3.6.7, I solved my problem by going back to version 3.6.7 ... the error ran on windows server 2012 R2 Datacenter virtualized by VMware

**Test results**
```

import psutil
from datetime import datetime, timedelta
processName='chrome'
listOfProcessObjects = []

for proc in psutil.process_iter():
    try:
        pinfo = proc.as_dict(attrs=['pid', 'name', 'create_time'])
        pinfo['started'] = datetime.fromtimestamp(pinfo['create_time'])
          # Check if process name contains the given name string.
        if pinfo['name'] and processName.lower() in pinfo['name'].lower():
            listOfProcessObjects.append(pinfo)
    except (psutil.PermissionError, psutil.NoSuchProcess, psutil.AccessDenied, psutil.ZombieProcess):
        pass

print(listOfProcessObjects)
```

```
Traceback (most recent call last):
  File ".\teste.py", line 6, in <module>
    for proc in psutil.process_iter():
  File "C:\Users\user10\AppData\Roaming\Python\Python38\site-packages\psutil\__init__.py", line 1457, in process_iter
    yield add(pid)
  File "C:\Users\user10\AppData\Roaming\Python\Python38\site-packages\psutil\__init__.py", line 1432, in add
    proc = Process(pid)
  File "C:\Users\user10\AppData\Roaming\Python\Python38\site-packages\psutil\__init__.py", line 346, in __init__
    self._init(pid)
  File "C:\Users\user10\AppData\Roaming\Python\Python38\site-packages\psutil\__init__.py", line 373, in _init
    self.create_time()
  File "C:\Users\user10\AppData\Roaming\Python\Python38\site-packages\psutil\__init__.py", line 723, in create_time
    self._create_time = self._proc.create_time()
  File "C:\Users\user10\AppData\Roaming\Python\Python38\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
  File "C:\Users\user10\AppData\Roaming\Python\Python38\site-packages\psutil\_pswindows.py", line 671, in convert_oserr
or
    raise exc
  File "C:\Users\user10\AppData\Roaming\Python\Python38\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\user10\AppData\Roaming\Python\Python38\site-packages\psutil\_pswindows.py", line 933, in create_time
    user, system, created = cext.proc_times(self.pid)
OSError: [WinError 0] The operation completed successfully: '(originated from OpenProcess)'
 }
```

**Comment by alxchk** [comment]
I have same thing with create_times with psutil 5.8.0/5.8.1 (from git).

```
>>> for p in psutil.pids():
>>>     try:
>>>         print(p, psutil._pswindows.cext.proc_times(p))
>>>     except Exception as e:
>>>         print("Failed", p, e)
>>> 
Failed 0 [Errno 13] assume access denied (originated from automatically set for PID 0)
Failed 4 [WinError 0] The operation completed successfully: '(originated from OpenProcess)'
Failed 248 [WinError 0] The operation completed successfully: '(originated from OpenProcess)'
Failed 316 [WinError 0] The operation completed successfully: '(originated from OpenProcess)'
...

788 (0.671875, 0.84375, 1610045289.4229844)
1416 (0.03125, 0.0625, 1610045355.533336)
1484 (0.0, 0.03125, 1610044217.9698591)
...
```

```
>>> OpenProcess(0x1000, False, 316)
>>> get_last_error()
5
```

Which is a bit weird, as I'm seeing checks in the source code. BTW, why is not to GetLastError instead of 0?
