### ISSUE TITLE
[Linux] AttributeError: _cache

### ISSUE THREAD

**Issue by justinkterry** [giampaolo/psutil#1925]
## Summary

* OS: Debian 10
* Architecture: X86-64 (GCP image
* Psutil version: 5.8.0
* Python version: { python3 -V }
* Type: core

## Description

I apologize for not having a small reproduction case here, but I can't entirely ascertain the origin of the bug. In wrote this incredibly script to be intermittently executed by a daemon to kill zombie processes leaking memory:

```
pids = psutil.pids()

for pid in pids:
    p = psutil.Process(pid)
    if p.name() == 'ray::ImplicitFunc':
        if p.memory_percent() > 0.0:
            if p.cpu_percent(interval=1.0) == 0.0:  # slow check
                p.kill()
```

This intermittently fails with a giant traceback that's largely incomprehensible to me but appears to represent a core bug. A patch for this that includes a comprehensible traceback may be wise.

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/psutil/_common.py", line 447, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/psutil/_common.py", line 450, in wrapper
    return fun(self)
  File "/opt/conda/lib/python3.7/site-packages/psutil/_pslinux.py", line 1618, in _parse_stat_file
    with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:
  File "/opt/conda/lib/python3.7/site-packages/psutil/_common.py", line 711, in open_binary
    return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/2800/stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/psutil/__init__.py", line 354, in _init
    self.create_time()
  File "/opt/conda/lib/python3.7/site-packages/psutil/__init__.py", line 710, in create_time
    self._create_time = self._proc.create_time()
  File "/opt/conda/lib/python3.7/site-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/psutil/_pslinux.py", line 1788, in create_time
    ctime = float(self._parse_stat_file()['create_time'])
  File "/opt/conda/lib/python3.7/site-packages/psutil/_pslinux.py", line 1583, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=2800)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "killer.py", line 50, in <module>
    schedule.run_pending()
  File "/opt/conda/lib/python3.7/site-packages/schedule/__init__.py", line 592, in run_pending
    default_scheduler.run_pending()
  File "/opt/conda/lib/python3.7/site-packages/schedule/__init__.py", line 94, in run_pending
    self._run_job(job)
  File "/opt/conda/lib/python3.7/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/opt/conda/lib/python3.7/site-packages/schedule/__init__.py", line 491, in run
    ret = self.job_func()
  File "killer.py", line 40, in killer
    p = psutil.Process(pid)
  File "/opt/conda/lib/python3.7/site-packages/psutil/__init__.py", line 326, in __init__
    self._init(pid)
  File "/opt/conda/lib/python3.7/site-packages/psutil/__init__.py", line 367, in _init
    raise NoSuchProcess(pid, None, msg)
psutil.NoSuchProcess: psutil.NoSuchProcess no process found with pid 2800
```

**Comment by giampaolo** [comment]
The traceback is misleading but it appears legitimate AFAICT. Your code has a race condition. It should be:


```python
try:
     p.kill()
except psutil.NoSuchProcess:
     pass
```
