### ISSUE TITLE
[armbian ubuntu20.04]  disk_io_counters raised ValueError in nginx-amplify-agent 1.8.0-1

### ISSUE THREAD

**Issue by rmadrona** [giampaolo/psutil#1950]
## Summary

* OS: { Ubuntu 20.04.2 LTS armbian latest}
* Architecture: { 64bit ARM }
* Psutil version: { 5.5.1 }
* Python version: { 3.8.5 }
* Type: { core}

## Description
{{{
OS metrics do not work on this platform, error log in 
2021-05-13 10:59:32,004 [4156492] sys_metrics sys_metrics failed to collect: disk_io_counters raised ValueError
same package is working on debian 11 on arm64 with python 3.9 and psutil 5.8.0
So  I tried to upgrade to psutil 5.8.0 
$ sudo pip3 install psutil==5.8.0
but it fails error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
so I decided to run unit test : 

[GCC 9.3.0] on linux
>>> import psutil
>>> psutil.__version__
'5.5.1'
>>> psutil.disk_usage('/home/bob')
sdiskusage(total=247516758016, used=9002024960, free=238514733056, percent=3.6)
>>> psutil.disk_io_counters(perdisk=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 2131, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1121, in disk_io_counters
    for entry in gen:
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1094, in read_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line '   7       0 loop0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n'

Can you please provide a fix or help upgrade to psutil 5.8.0 on python 3.8 ? 
}}}

**Comment by z26egors** [comment]
It has already been fixed in psutil, we'll upgrade to a newer version.

**Comment by giampaolo** [comment]
Closing as per your last comment, this was already fixed on our side.
