### ISSUE TITLE
regression - psutil5.8.0 again can not be used on WINE because 'RtlIpv6AddressToStringA' missing ... 

### ISSUE THREAD

**Issue by bitranox** [giampaolo/psutil#1985]
## Summary

* OS: WINE
* Architecture: 64 and 32bit
* Psutil version: psutil-5.8.0
* Python version: python3.9.7
* Type: { core, installation }

## Description
Dear Giampaolo,
You fixed it for me in an older version for wine.
wine does not have IPV6, therefore installation fails.
would You please be so kind and fix it again.
Maybe You can add some tests for that, so the regression will not happen again ?

Xie Xie !

Yours sincerely

Robert

```
Requirement already satisfied: pywin32 in c:\users\srvadmin\application data\python\python39\site-packages (301)
Traceback (most recent call last):
  File "i:\rotek-apps-install\rotek-apps\bin\util\install\rotek-apps-installer.py", line 81, in <module>
    import lib_servercontrol
  File "i:\rotek-apps-install/rotek-apps/lib\lib_servercontrol.py", line 2, in <module>
    from libs_local.lib_servercontrol.lib_servercontrol import *
  File "i:\rotek-apps-install/rotek-apps/lib\libs_local\lib_servercontrol\lib_servercontrol\__init__.py", line 1, in <module>
    from . import autobackup
  File "i:\rotek-apps-install/rotek-apps/lib\libs_local\lib_servercontrol\lib_servercontrol\autobackup.py", line 6, in <module>
    from . import lxc
  File "i:\rotek-apps-install/rotek-apps/lib\libs_local\lib_servercontrol\lib_servercontrol\lxc.py", line 7, in <module>
    import lib_lxc
  File "i:\rotek-apps-install/rotek-apps/lib\lib_lxc.py", line 2, in <module>
    from libs_local.lib_lxc.lib_lxc import *
  File "i:\rotek-apps-install/rotek-apps/lib\libs_local\lib_lxc\lib_lxc\__init__.py", line 1, in <module>
    from .lib_lxc import *
  File "i:\rotek-apps-install/rotek-apps/lib\libs_local\lib_lxc\lib_lxc\lib_lxc.py", line 9, in <module>
    import lib_shell    # type: ignore
  File "i:\rotek-apps-install/rotek-apps/lib\lib_shell.py", line 2, in <module>
    from bitranox.lib_shell.lib_shell import *
  File "i:\rotek-apps-install/rotek-apps/lib\bitranox\lib_shell\lib_shell\__init__.py", line 5, in <module>
    from .lib_shell_commandline import *
  File "i:\rotek-apps-install/rotek-apps/lib\bitranox\lib_shell\lib_shell\lib_shell_commandline.py", line 8, in <module>
    import psutil   # type: ignore
  File "C:\users\srvadmin\Application Data\Python\Python39\site-packages\psutil\__init__.py", line 107, in <module>
    from . import _pswindows as _psplatform
  File "C:\users\srvadmin\Application Data\Python\Python39\site-packages\psutil\_pswindows.py", line 35, in <module>
    from ._psutil_windows import ABOVE_NORMAL_PRIORITY_CLASS
OSError: [WinError 127] Prozedur nicht gefunden: 'RtlIpv6AddressToStringA'

Fehler bei der Installation der Python Bibliotheken
```

**Comment by giampaolo** [comment]
Hello Robert. Please continue in the old ticket: https://github.com/giampaolo/psutil/issues/1448.
