### ISSUE TITLE
[Windows 10] process.status() errors after process is terminated

### ISSUE THREAD

**Issue by mas-4** [giampaolo/psutil#2017]
## Summary

* OS: Windows 10
* Architecture: 64 bit
* Psutil version: 5.8.0
* Python version: 3.10.0
* Type: core

## Description

When I have a Process, gotten like so:

```python
def get_process() -> psutil.Process:
    """
    Gets the currently running process.

    Returns
    -------
    psutil.Process
    """
    return list(filter(lambda p: p.name() == "<proc_name>.exe", psutil.process_iter()))[0]
```

I can call `process.status()` while its still running. However, when I simulate a crash via task manager (just ending the task), calling `process.status()` raises an exception:

```
>>> process.status()
Traceback (most recent call last):
  File "...\venv\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "...\venv\lib\site-packages\psutil\_pswindows.py", line 1054, in status
    suspended = cext.proc_is_suspended(self.pid)
ProcessLookupError: [Errno 3] assume no such process (originated from NtQuerySystemInformation (no PID found))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "...\venv\lib\site-packages\psutil\__init__.py", line 682, in status
    return self._proc.status()
  File "...\venv\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=19160, name='<proc_name>.exe')
```

(traceback slightly modified to remove process/directory names)

It seemed to me that this must be a bug because the Process object's `__repr__` can clearly display the correct status as a string. I just can't find how to get it (I would assume `process.status()` would do that):

```
psutil.Process(pid=19160, name='<proc_name>.exe', status='terminated', started='12:59:12')
```

**Comment by giampaolo** [comment]
This is not a bug. `__repr__` displays `status="terminated"` because it catches NoSuchProcess:

```python
    def __str__(self):
        try:
            info = collections.OrderedDict()
        except AttributeError:  # pragma: no cover
            info = {}  # Python 2.6
        info["pid"] = self.pid
        if self._name:
            info['name'] = self._name
        with self.oneshot():
            try:
                info["name"] = self.name()
                info["status"] = self.status()
            except ZombieProcess:
                info["status"] = "zombie"
            except NoSuchProcess:
                info["status"] = "terminated"
            except AccessDenied:
                pass
            if self._exitcode not in (_SENTINEL, None):
                info["exitcode"] = self._exitcode
            if self._create_time:
                info['started'] = _pprint_secs(self._create_time)
            return "%s.%s(%s)" % (
                self.__class__.__module__,
                self.__class__.__name__,
                ", ".join(["%s=%r" % (k, v) for k, v in info.items()]))
```

Since you stated that you manually ended the task via taskmgr.exe, `status()` raising `NoSuchProcess` is expected behavior.

**Comment by mas-4** [comment]
@giampaolo Okay, thank you. I'll just catch NoSuchProcess in my code.
