### ISSUE TITLE
[Ubuntu] IndexError when instantiating a new Process

### ISSUE THREAD

**Issue by mike-fam** [giampaolo/psutil#2027]
## Summary

* OS: Ubuntu 18.04.5
* Architecture: Zone instance managed by [triton](https://apidocs.joyent.com/cloudapi/#provision-a-new-instance)
* Psutil version: 5.8.0
* Python version: Python 3.9
* Type: core

## Description
Whenever a new `Process` instance is created, with or without a pid, this error occurs:
```
>>> import psutil
>>> proc = psutil.Process(368380)
Traceback (most recent call last):
  File "/home/uqmpham6/.local/lib/python3.9/site-packages/psutil/_common.py", line 447, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/uqmpham6/.local/lib/python3.9/site-packages/psutil/__init__.py", line 326, in __init__
    self._init(pid)
  File "/home/uqmpham6/.local/lib/python3.9/site-packages/psutil/__init__.py", line 354, in _init
    self.create_time()
  File "/home/uqmpham6/.local/lib/python3.9/site-packages/psutil/__init__.py", line 710, in create_time
    self._create_time = self._proc.create_time()
  File "/home/uqmpham6/.local/lib/python3.9/site-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/uqmpham6/.local/lib/python3.9/site-packages/psutil/_pslinux.py", line 1788, in create_time
    ctime = float(self._parse_stat_file()['create_time'])
  File "/home/uqmpham6/.local/lib/python3.9/site-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/uqmpham6/.local/lib/python3.9/site-packages/psutil/_common.py", line 450, in wrapper
    return fun(self)
  File "/home/uqmpham6/.local/lib/python3.9/site-packages/psutil/_pslinux.py", line 1638, in _parse_stat_file
    ret['blkio_ticks'] = fields[39]  # aka 'delayacct_blkio_ticks'
IndexError: list index out of range
```
I'm not familiar with the architecture myself. If you require more information, please let me know. 

Thanks

**Comment by Jongy** [comment]
Looks like invalid output is being read from `/proc/pid/stat`. On my box (kernel 5.4.0) it has 52 fields, and this "field 39" exists since kernel 2.6.18 per the man page.

@mike-fam , can you please provide the output of `/proc/pid/stat` for such a process whose instantiation fails? For example, if `psutil.Process(368380)` raises, then the output of `/proc/368380/stat` would help here.

**Comment by giampaolo** [comment]
Fixed. The blkio_ticks lookup that blew up in your traceback is wrapped in a try/except IndexError now (done for #2455), so a short /proc/pid/stat no longer breaks Process().
