### ISSUE TITLE
[Linux/Docker] hasattr(psutil, 'sensors_battery') returns True even when a battery isn't available:

### ISSUE THREAD

**Issue by eelcohn** [giampaolo/psutil#2067]
## Summary

* OS: Linux 4.4.59 / Docker 20.10.0
* Architecture: 64 bit
* Psutil version: 5.8.0
* Python version: 3.8.10
* Type: core

## Description

`hasattr(psutil, 'sensors_battery')` returns `True` even when a battery isn't available:

```
Python 3.8.10 (default, May  6 2021, 00:05:59)
[GCC 10.2.1 20201203] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.sensors_battery()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/psutil/__init__.py", line 2288, in sensors_battery
    return _psplatform.sensors_battery()
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1398, in sensors_battery
    bats = [x for x in os.listdir(POWER_SUPPLY_PATH) if x.startswith('BAT') or
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/power_supply'
>>> hasattr(psutil, 'sensors_battery')
True
```

**Comment by bdrung** [comment]
`hasattr(psutil, 'sensors_battery')` just tells you if there is a `sensors_battery` function. The issue is that `psutil.sensors_battery()` crashes instead of returning `None`.
