### ISSUE TITLE
[Windows 10 Pro 21H1] PdhAddEnglishCounterW failed

### ISSUE THREAD

**Issue by Madelena** [giampaolo/psutil#2105]
## Summary

* OS: Windows 10 Pro 21H1 (OS Build 19044.1645)
* Architecture: 64bit
* Psutil version: 5.9.0
* Python version: 3.10.4
* Type: { core, doc, performance, scripts, tests, wheels, new-api, installation } (Not sure what this means)

## Description

I use Glances which uses psutil. When I tried to run it on one of my computers, it gave me this error. The error doesn't occur on other computers.

```
Error while initializing the docker plugin (No module named 'dateutil')
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Madelena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\glances.exe\__main__.py", line 7, in <module>
  File "C:\Users\Madelena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\glances\__init__.py", line 189, in main
    start(config=core.get_config(), args=core.get_args())
  File "C:\Users\Madelena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-package    mode = GlancesMode(config=config, args=args)
  File "C:\Users\Madelena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\glances\standalone.py", line 80, in __init__
    self.stats.update()
  File "C:\Users\Madelena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\glances\stats.py", line 221, in update
    self._plugins[p].update()
  File "C:\Users\Madelena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\glances\plugins\glances_plugin.py", line 1157, in wrapper
    ret = fct(self, *args, **kw)
  File "C:\Users\Madelena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\glances\plugins\glances_plugin.py", line 1174, in wrapper
    ret = fct(*args, **kw)
  File "C:\Users\Madelena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\glances\plugins\glances_load.py", line 116, in update
    load = self._getloadavg()
  File "C:\Users\Madelena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\glances\plugins\glances_load.py", line 97, in _getloadavg
    return psutil.getloadavg()
  File "C:\Users\Madelena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\psutil\_pswindows.py", line 347, in getloadavg
    cext.init_loadavg_counter()
RuntimeError: PdhAddEnglishCounterW failed
```

(I was referred here by @nicolargo through this bug: https://github.com/nicolargo/glances/issues/2045 )

**Comment by dbwiddis** [comment]
The code is attempting (and failing) to read the "\System\Processor Queue Length" performance counter.  It is possible the counters on your machine are corrupt or disabled.

Use the Performance Monitor application (perfmon.exe) and see if you can add that counter from within the app.  
 - If the counters are corrupt, attempt to [rebuild them](https://docs.microsoft.com/en-us/troubleshoot/windows-server/performance/rebuild-performance-counter-library-values)
 - If the counters are disabled, check the registry `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Perflib` and make sure there is no key "Disable" (or set it to 0).

**Comment by Madelena** [comment]
Awesome! Typing `lodctr /R` (nor /r) solved this.

**Comment by giampaolo** [comment]
Perhaps it's worth to mention `lodctr /R` in the error message, but then again, this solution appears to be Windows-server only:
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/lodctr

**Comment by dbwiddis** [comment]
You could just say “performance counters may be corrupt or disabled” which gives sufficient hints to search for a solution.

**Comment by giampaolo** [comment]
Good idea. Done.

**Comment by dbwiddis** [comment]
Might want to include "corrupt or...".  Also could you "graceful fallback" and simply not provide load counters in that case? Your counter thread will die but everything else should work.

**Comment by pmor13** [comment]
> Awesome! Typing `lodctr /R` (not /r) on elevated command prompt solved this.

Why `/R` and not `/r`? In the [parameters for `lodctr`](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/lodctr) I don't see `/R`. What's the difference between `/R` and `/r`? Isn't Windows command line (and most of the commands) case-insensitive?
