### ISSUE TITLE
[arch] process_iter - KeyError: 'psutil'

### ISSUE THREAD

**Issue by gmankab** [giampaolo/psutil#2106]
## Summary

* OS: Arch Linux
* Architecture: x86_64
* Kernel version: 5.17.5-arch1-1
* Psutil version: 5.9.0
* Python version: 3.10.4
* Type: process_iter function

neofetch - https://pastebin.com/cEPrCBRD
pip freeze - https://pastebin.com/9KaNtkRb

## Description

```
pip insrall psutil
python -c '
import psutil
print(list(psutil.process_iter()))
'
```

works fine, but

```
pip install psutil -t libs
python -c '
import sys
import os

sys.path += (
    os.getcwd(),
    f"{os.getcwd()}/libs"
)
from libs.psutil import process_iter
print(list(process_iter()))
'
```

returns

```
Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "/root/proj/backupper/libs/psutil/__init__.py", line 1432, in process_iter
    a = set(pids())
  File "/root/proj/backupper/libs/psutil/__init__.py", line 1372, in pids
    ret = sorted(_psplatform.pids())
  File "/root/proj/backupper/libs/psutil/_pslinux.py", line 1597, in pids
    return [int(x) for x in os.listdir(b(get_procfs_path())) if x.isdigit()]
  File "/root/proj/backupper/libs/psutil/_common.py", line 750, in get_procfs_path
    return sys.modules['psutil'].PROCFS_PATH
KeyError: 'psutil'
```

**Comment by giampaolo** [comment]
I've never used pip's `-t` option, but `from libs.psutil import X` simply looks wrong to me, and is not how psutil is supposed to be used/imported.  psutil assumes that its own name (and main namespace) is "psutil", not "libs.psutil", which is why it crashes.
