### ISSUE TITLE
ValueError: not sure how to interpret line '8[OS] title  in lxcfs 5.0.0

### ISSUE THREAD

**Issue by ForTheOne** [giampaolo/psutil#2148]
## Summary

* OS: { type-or-version }
* Architecture: { 64bit, 32bit, ARM, PowerPC, s390 }
* Psutil version: { pip3 show psutil }
* Python version: { python3 -V }
* Type: { core, doc, performance, scripts, tests, wheels, new-api, installation }

## Description
in lxcfs-5.0.0

[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.__version__
'5.9.2'
>>> psutil.disk_io_counters()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/psutil/__init__.py", line 2064, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/psutil/_pslinux.py", line 1154, in disk_io_counters
    for entry in gen:
  File "/usr/local/lib/python3.5/dist-packages/psutil/_pslinux.py", line 1127, in read_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line '8       0 sda 0 0 0 0 46 0 977 34 0 2 0 0 0 0\n'

**Comment by giampaolo** [comment]
Could you paste the output of `cat /proc/diskstats`?

**Comment by ForTheOne** [comment]
```
cat /proc/diskstats
8       0 sda 0 0 0 0 2 0 42 7 0 0 0 0 0 0
```

**Comment by ForTheOne** [comment]
> Could you paste the output of `cat /proc/diskstats`?
```
cat /proc/diskstats
8       0 sda 0 0 0 0 2 0 42 7 0 0 0 0 0 0
```

**Comment by ForTheOne** [comment]
```
Python 3.5.3 (default, Nov  4 2021, 15:29:10)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.disk_io_counters()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/psutil/__init__.py", line 2064, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/psutil/_pslinux.py", line 1154, in disk_io_counters
    for entry in gen:
  File "/usr/local/lib/python3.5/dist-packages/psutil/_pslinux.py", line 1127, in read_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line '8       0 sda 0 0 0 0 10 0 206 23 0 0 0 0 0 0\n'
>>> psutil.__version__
'5.9.2'
>>> exit()
root@nginx-xxx:/home# cat /proc/diskstats
8       0 sda 0 0 0 0 10 0 206 23 0 0 0 0 0 0
```

**Comment by giampaolo** [comment]
What linux version is this? What's the output of `uname -a`?

**Comment by ghtian123** [comment]
> What linux version is this? What's the output of `uname -a`?

Linux  4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux

**Comment by haaver** [comment]
similar on 5.15.0-86-generic #96~20.04.1-Ubuntu SMP Thu Sep 21 13:23:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux:
not sure how to interpret line '   7       0 loop0 11 0 28 0 0 0 0 0 0 4 0 0 0 0 0 0 0\n'

**Comment by giampaolo** [comment]
The 20 field line from the follow-up report is handled since 5.7.0, so both of you were likely on an older version. Closing, please reopen with the psutil version and the exact /proc/diskstats line if it still happens.
