### ISSUE TITLE
Cannot get cmdline attribute for terminal process

### ISSUE THREAD

**Issue by tamruta** [giampaolo/psutil#2189]
Recreated the problem I was facing:

``` python
process_hash = "login"  
for proc in psutil.process_iter():
    if process_hash in proc.name():
        server_process_running = True
        print(proc)
        print(str(proc.as_dict(['cmdline'])))  # this is where the problem rises 
```

``` console
psutil.Process(pid=3629, name='login', status='running', started='09:16:35')
Traceback (most recent call last):
  File "/opt/anaconda3/envs/trust/lib/python3.10/site-packages/psutil/_psosx.py", line 346, in wrapper
    return fun(self, *args, **kwargs)
  File "/opt/anaconda3/envs/trust/lib/python3.10/site-packages/psutil/_psosx.py", line 404, in cmdline
    return cext.proc_cmdline(self.pid)
ProcessLookupError: [Errno 3] assume no such process (originated from sysctl(KERN_PROCARGS2) -> EINVAL)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/test.py", line 14, in <module>
    print(str(proc.as_dict(['cmdline'])))
  File "/opt/anaconda3/envs/trust/lib/python3.10/site-packages/psutil/__init__.py", line 528, in as_dict
    ret = meth()
  File "/opt/anaconda3/envs/trust/lib/python3.10/site-packages/psutil/__init__.py", line 681, in cmdline
    return self._proc.cmdline()
  File "/opt/anaconda3/envs/trust/lib/python3.10/site-packages/psutil/_psosx.py", line 351, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=3629, name='login')
```

When I looked online about similar errors, some suggested it was caused by a zombie process. So I tried to kill the process and the terminal session closed. 

I'm not sure if this is a bug or a feature, but this only happened when I updated psutil from 5.6.7 to 5.9.4

**Comment by giampaolo** [comment]
That's a race condition: between the `for` loop iteration and the `proc.as_dict()` call the process disappears. You have to ways to solve this problem. You either specify what process attributes you want to access up front:

```python
for proc in psutil.process_iter(attrs=["name", "cmdline"]):
      print(proc.info["name"])
      print(proc.info["cmdline"])
```

...or you catch the exception later:

```python
for proc in psutil.process_iter():
    try:
        print(proc.name())
        print(proc.cmdline())
    except (psutil.NoSuchProcess, psutil.AccessDenied):
        continue
```

**Comment by tamruta** [comment]
Thank you!

**Comment by tamruta** [comment]
@giampaolo I'm confused why the process no longer exists when the terminal session is still open. The race shouldn't really exist because the process never closed

And it seems to be a new problem that didn't happen in 5.6.7

**Comment by jacob-lee** [comment]
Perhaps this is expected behavior, however I find it surprising on two counts. 

First, I have independently confirmed just now that no such exception is raised with version 5.6.7, but after upgrading to 5.9.4, the exception is thrown.

Secondly, it is the same process that consistently throws the error on my machine (M1 Macbook Pro, Ventura 13.0.1): the 'login -pf username' process running under root. Moreover, the process is *still* running under the same pid.

**Comment by giampaolo** [comment]
Mmm... even if the original python code had race condition, this may be a bug. Error originates from here:
https://github.com/giampaolo/psutil/blob/c6b71453653609827f74aa074989ae4b9da69ece/psutil/arch/osx/process_info.c#L135
Is the process a zombie? Can you guys please catch the NoSuchProcess exception and then print the process `status()`?

**Comment by tamruta** [comment]
The status is running:

It seems to be caused by Mac's permissions to root processes. When the code is run on `sudo` it works without any errors. Also there is no error on linux or windows

**Comment by jacob-lee** [comment]
Hmm. That seems to be right. No exception raised if I run the python process with sudo.

**Comment by giampaolo** [comment]
Note to self: the problem is that EINVAL on `sysctl()` should be translated to `AccessDenied` instead of `NoSuchProcess`, because the PID is still alive and is not a zombie. As such,  raising`AccessDenied` is really the best we can do in this circumstance (also confirmed by the fact that the problem does not occur with root as per @jacob-lee comment).

In order to fix this I'll have to refactor the C code a bit though, so this may take a while.

**Comment by giampaolo** [comment]
Fixed. EINVAL coming from sysctl(KERN_PROCARGS2) is translated into AccessDenied now, which is what I said we should do here.
