### ISSUE TITLE
Windows AttributeError: 'pmmap_grouped' object has no attribute 'is_readable'

### ISSUE THREAD

**Issue by adabugra** [giampaolo/psutil#2249]
## Summary

* OS: Windows 11
* Architecture: I7 64 bit
* Psutil version: 5.9.5
* Python version: Python 3.9.13
* Type: python file

## Description
Code: https://pastes.dev/V116V5sRin
Error
Traceback (most recent call last):
  File "C:\Users\adabu\Downloads\processhacker-2.38-bin\x64\o.py", line 26, in <module>
    search_string_in_process_memory(pid, search_string)
  File "C:\Users\adabu\Downloads\processhacker-2.38-bin\x64\o.py", line 11, in search_string_in_process_memory
    if mem.is_readable() and mem.path is not None:
AttributeError: 'pmmap_grouped' object has no attribute 'is_readable'

**Comment by giampaolo** [comment]
It's a namedtuple. That method does not exist. Not sure where you took it from.
Closing as invalid.
