### ISSUE TITLE
ERROR OF pyega3 package.

### ISSUE THREAD

**Issue by jianguozhouzunyimedicaluniversity** [giampaolo/psutil#2313]
`Traceback (most recent call last):
  File "/home/zhou2/miniconda3/envs/pyega3/bin/pyega3", line 6, in <module>
    from pyega3.pyega3 import main
  File "/home/zhou2/miniconda3/envs/pyega3/lib/python3.6/site-packages/pyega3/pyega3.py", line 14, in <module>
    from pyega3.libs.data_client import DataClient
  File "/home/zhou2/miniconda3/envs/pyega3/lib/python3.6/site-packages/pyega3/libs/data_client.py", line 8, in <module>
    from urllib3.util import retry
ModuleNotFoundError: No module named 'urllib3'
1288553`

ERROR OF pyega3 package.

**Comment by ShixiangWang** [comment]
Install the pyega3 based on python3.8 fix it, @jianguozhouzunyimedicaluniversity you can close it now.
