### ISSUE TITLE
[CentOS Stream 10] test_misc.TestCommonModule.test_debug often fails on ppc64le, s390x, or aarch64

### ISSUE THREAD

**Issue by hroncok** [giampaolo/psutil#2374]
## Summary

* OS: CentOS Stream 10
* Architecture: ppc64le, s390x, or aarch64
* Psutil version:  5.9.8
* Python version: 3.12.1
* Type: tests

## Description

Hello, similarly to https://github.com/giampaolo/psutil/issues/2373 I often get this failure on ppc64le, s390x, or aarch64 CentOS Stream 10 builders:

```
======================================================================
FAIL: psutil.tests.test_misc.TestCommonModule.test_debug
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/psutil-release-5.9.8/psutil/tests/test_misc.py", line 580, in test_debug
    assert msg.startswith("psutil-debug"), msg
AssertionError
----------------------------------------------------------------------
```

This however sometimes happens and sometimes does not (possibly flaky or related to the exact machine the builder uses).

I can provide more details as requested or try to debug the problem if instructed. Unfortunately, I cannot use the machine interactively :(

**Comment by hroncok** [comment]
I am retrying with `@retry_on_failure()`

**Comment by hroncok** [comment]
> I am retrying with `@retry_on_failure()`

Nah. One particular build either passes this test immediately or fails all the retrying attempts.

**Comment by giampaolo** [comment]
I attempted to fix this in aab8d09d0. Let me know how it goes.

**Comment by hroncok** [comment]
On it. First, I have verified that I can still reproduce the failures without https://github.com/giampaolo/psutil/commit/aab8d09d029420756f85df839b993e3f139dd2ac.

Now building with psutil/tests/test_misc.py changes from that commit.

**Comment by hroncok** [comment]
Unfortunately no difference, still fails.

```
======================================================================
FAIL: psutil.tests.test_misc.TestCommonModule.test_debug
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/psutil-release-5.9.8/psutil/tests/test_misc.py", line 582, in test_debug
    assert msg.startswith("psutil-debug"), msg
AssertionError
----------------------------------------------------------------------
Ran 569 tests in 2.863s
```

(the line number changed, due to the patch)

**Comment by giampaolo** [comment]
Do you still get this?

**Comment by giampaolo** [comment]
I recently got access to https://portal.cfarm.net/machines/list/, and didn't see this failure on any of these architectures, so I assume this got fixed. Closing. Please reopen if it's still there.

**Comment by hroncok** [comment]
I can no longer reproduce this reliably with the recent version 7.2.2.
