### ISSUE TITLE
[Windows] as_dict() failing for win_service_get('WaaSMedicSvc')

### ISSUE THREAD

**Issue by ConstantinaElena** [giampaolo/psutil#2383]
## Summary

* OS: { Win11 }
* Architecture: { 64bit }
* Psutil version: { 5.9.8 }
* Python version: { 3.11.2 }
* Type: { core }

## Description

{{{
  **as_dict() call fails (only) for "WaaSMedicSvc" service.**

  python.exe -c "import psutil; srvc = psutil.win_service_get('WaaSMedicSvc'); ret = srvc.as_dict();"

```
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python311\Lib\site-packages\psutil\_pswindows.py", line 650, in as_dict
    d['description'] = self.description()
                       ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\psutil\_pswindows.py", line 638, in description
    return py2_strencode(cext.winservice_query_descr(self.name()))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  FileNotFoundError: [WinError 2] The system cannot find the file specified: '(originated from QueryServiceConfig2W)'
```
}}}

**Comment by giampaolo** [comment]
Fixed.
