### ISSUE TITLE
'psutil' has no attribute 'sensors_temperatures'

### ISSUE THREAD

**Issue by aroramrinaal** [giampaolo/psutil#2426]
## Summary

* OS: MacOs
* Architecture: ARM64
* Psutil version:  5.9.8
* Python version: 3.9.6

## Description

I just tried to use psutil, but psutil.sensors_temperatures() currently returns an error
`Traceback (most recent call last):
  File "/Users/mrinaalarora/Desktop/SysTrack/systrack/system_monitor.py", line 57, in <module>
    print(get_sensor_temps())
  File "/Users/mrinaalarora/Desktop/SysTrack/systrack/system_monitor.py", line 49, in get_sensor_temps
    sensors = psu.sensors_temperatures()
AttributeError: module 'psutil' has no attribute 'sensors_temperatures'`

**Comment by giampaolo** [comment]
It's not implemented on OSX.
