### ISSUE TITLE
[Fedora Linux/CentOS Stream 10] psutil.tests.test_system.TestSensorsAPIs.test_sensors_temperatures assertion fails more often than not

### ISSUE THREAD

**Issue by befeleme** [giampaolo/psutil#2434]
## Summary

* OS: Fedora Linux 42, CentOS Stream 10
* Architecture: multiple
* Psutil version: 5.9.8
* Python version: 3.12
* Type: tests

## Description

We run tests during the package build, with invocation xxx

`psutil.tests.test_system.TestSensorsAPIs.test_sensors_temperatures` is flaky - fails much more often than not.

C10S output:

```
DEBUG: FAIL: psutil.tests.test_system.TestSensorsAPIs.test_sensors_temperatures
DEBUG: ----------------------------------------------------------------------
DEBUG: Traceback (most recent call last):
DEBUG:   File "/builddir/build/BUILD/psutil-release-5.9.8/psutil/tests/test_system.py", line 914, in test_sensors_temperatures
DEBUG:     self.assertGreaterEqual(entry.current, 0)
DEBUG: AssertionError: -0.15 not greater than or equal to 0
DEBUG: ----------------------------------------------------------------------
```

Fedora Linux ouput:

```
======================================================================
FAIL: psutil.tests.test_system.TestSensorsAPIs.test_sensors_temperatures
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.13/site-packages/psutil/tests/test_system.py", line 914, in test_sensors_temperatures
    self.assertGreaterEqual(entry.current, 0)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
AssertionError: -273.15 not greater than or equal to 0
```

**Comment by giampaolo** [comment]
Duplicate of https://github.com/giampaolo/psutil/issues/2434.
