### ISSUE TITLE
psutil: RuntimeError: PdhAddEnglishCounterW failed 

### ISSUE THREAD

**Issue by wolfkingal2000** [giampaolo/psutil#2458]
i use this software give this error
https://github.com/VoxelCubes/PanelCleaner

Traceback (most recent call last):
File "pcleaner\main.py", line 837, in
File "pcleaner\main.py", line 310, in main
File "pcleaner\gui\launcher.py", line 80, in launch
File "psutil_init_.py", line 2036, in swap_memory
File "psutil_pswindows.py", line 266, in swap_memory
RuntimeError: PdhAddEnglishCounterW failed. Performance counters may be disabled.

**Comment by giampaolo** [comment]
See this answer: https://support.nagios.com/forum/viewtopic.php?p=345792&sid=a3181b9c1310e7b57566ea78f10b3997#p345792.

**Comment by wolfkingal2000** [comment]
> See this answer: https://support.nagios.com/forum/viewtopic.php?p=345792&sid=a3181b9c1310e7b57566ea78f10b3997#p345792.

I have done this before but it did not work
