### ISSUE TITLE
BSD - get_open_files() doesn't work properly

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#373]
_From [g.rodola](https://code.google.com/u/g.rodola/) on April 30, 2013 21:31:49_

```
...because it returns an empty string:

    ======================================================================
    FAIL: test_get_open_files (__main__.TestCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "test/test_psutil.py", line 1202, in test_get_open_files
        self.assertIn(TESTFN, filenames)
    AssertionError: '/home/psutil/psutil/$testfile' not found in 
['/usr/local/bin/python', '']

    ======================================================================
    FAIL: test_get_open_files2 (__main__.TestCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "test/test_psutil.py", line 1230, in test_get_open_files2
        self.assertEqual(path, fileobj.name)
    AssertionError: '' != '/home/psutil/psutil/$testfile'


This is not new (started since we got rid of the lsof parser implementation I 
guess) but I always ignored it for lack of time and laziness.
At least now we have it tracked.
```

_Original issue: http://code.google.com/p/psutil/issues/detail?id=373_

**Comment by giampaolo** [comment]
Closing as duplicate of #595.
