### ISSUE TITLE
test_get_connections() failure on OS X 10.8.4

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#397]
_From [jlo...@gmail.com](https://code.google.com/u/104710261032439836788/) on June 18, 2013 02:44:02_
    
    ======================================================================
        FAIL: test_get_connections (proc=psutil.Process(pid=1759, name='VMware 
    Fusion'), ret=[connection(fd=29, family=2, type=1, 
    local_address=('192.168.15.104', 57061), remote_address=('208.91.0.10', 443), 
    status=7), connection(fd=37, family=2, type=1, local_address=('192.168.15.104', 
    57068), remote_address=('23.0.51.51', 443), status=7)]))
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "test/test_psutil.py", line 1937, in test_fetch_all
            meth(ret)
          File "test/test_psutil.py", line 2091, in get_connections
            s.bind((conn.local_address[0], 0))
          File 
    "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py",
     line 224, in meth
            return getattr(self._sock,name)(*args)
        error: [Errno 49] Can't assign requested address
    
_Original issue: http://code.google.com/p/psutil/issues/detail?id=397_

**Comment by giampaolo** [comment]
Probably outdated
