### ISSUE TITLE
test_get_ext_memory_info() failure on OS X 10.8.4

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#398]
_From [jlo...@gmail.com](https://code.google.com/u/104710261032439836788/) on June 18, 2013 02:44:43_
    
    ======================================================================
        FAIL: test_get_ext_memory_info (proc=psutil.Process(pid=45, 
    name='fseventsd'), ret=meminfo(rss=8351744L, vms=2654044160L, 
    pfaults=5896286208, pageins=4071424)))
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "test/test_psutil.py", line 1937, in test_fetch_all
            meth(ret)
          File "test/test_psutil.py", line 2049, in get_ext_memory_info
            assert ret.vms > value, ret
        AssertionError: meminfo(rss=8351744L, vms=2654044160L, pfaults=5896286208, 
    pageins=4071424)
    
_Original issue: http://code.google.com/p/psutil/issues/detail?id=398_

**Comment by giampaolo** [comment]
Closing out as outdated.
