### ISSUE TITLE
test_uids() failure on OS X 10.8.4

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#399]
_From [jlo...@gmail.com](https://code.google.com/u/104710261032439836788/) on June 18, 2013 02:46:06_
    
    ======================================================================
        FAIL: test_uids (proc=psutil.Process(pid=22, name='warmd'), 
    ret=user(real=0, effective=4294967294, saved=0)))
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "test/test_psutil.py", line 1937, in test_fetch_all
            meth(ret)
          File "test/test_psutil.py", line 1993, in uids
            self.assertIn(uid, self._uids)
          File 
    "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py",
     line 799, in assertIn
            self.fail(self._formatMessage(msg, standardMsg))
          File 
    "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py",
     line 408, in fail
            raise self.failureException(msg)
        AssertionError: 4294967294 not found in set([0, 1, 224, 4, 75, 215, 13, 88, 
    205, 89, 24, 25, 26, 27, 31, 32, 91, 92, 221, 99, 200, 94, 54, 55, 56, 58, 59, 
    60, 74, 65, 67, 70, 71, 72, 73, 202, 203, 76, 77, 78, 79, 208, 82, 83, 212, 
    213, 214, 87, 216, 217, 218, 219, 220, 93, 222, 95, 96, 97, 98, 227, 228, 229, 
    230, 231, 232, 233, 234, 235, 210, 211, 501, 84, -2])
    
    
    Looks like maybe an overflow on the effective UID field.
    
_Original issue: http://code.google.com/p/psutil/issues/detail?id=399_

**Comment by giampaolo** [comment]
I'm gonna close this out as outdated.
