### ISSUE TITLE
ImportError. undefined symbol: prlimit

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#442]
_From [shchepyo...@gmail.com](https://code.google.com/u/115763814826292337195/) on October 17, 2013 20:07:47_

```
Hi!
Sorry for my English.
I installed with the help of let pip. In the console do import psutil and get an error.

>>> import psutil
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.6/dist-packages/psutil/__init__.py", line 89, in <module>
    import psutil._pslinux as _psplatform
  File "/usr/local/lib/python2.6/dist-packages/psutil/_pslinux.py", line 21, in <module>
    import _psutil_linux
ImportError: /usr/local/lib/python2.6/dist-packages/_psutil_linux.so: undefined 
symbol: prlimit 

What version of psutil are you using? What Python version?  
psutil-1.1.1
Python 2.6.6

On what operating system?

OS: Debian GNU/Linux 6.0
Uname: Linux 3.2.0-0.bpo.4-amd64 #1 SMP Debian 3.2.41-2+deb7u2~bpo60+1 x86_64 GNU/Linux
```

_Original issue: http://code.google.com/p/psutil/issues/detail?id=442_

**Comment by jhaoheng** [comment]
Hi 

I got this issue 
`ImportError: /bin/psutil._psutil_linux.so: undefined symbol: prlimit64`

- python 2.7.10
- liunx 6 
- psutil 5.4.7

**Comment by giampaolo** [comment]
What Linux distro do you have?

**Comment by jhaoheng** [comment]
Hi @giampaolo 

I use 0.1.2 and the issue solved.
thank you so much.

**Comment by giampaolo** [comment]
I believe I fixed this some time ago. Closing.
