### ISSUE TITLE
Error " AttributeError: 'module' object has no attribute 'process_iter' " when executing a script from the Windows console

### ISSUE THREAD

**Issue by SSinternalIT** [giampaolo/psutil#524]
Hi,
we've created the following script:

```

import psutil
import time

Process to monitor

PROCNAME = "haltd"

for proc in psutil.process_iter():
    if proc.name == PROCNAME:
        proc_found = proc

pid=proc.pid
print "Found PID for "+PROCNAME+": ",pid

while True: 
    # log date time
    print (time.strftime("%x") + " " + time.strftime("%H:%M:%S"))
    # Read system
    syscpu = psutil.cpu_percent(interval=1, percpu=True)
    sysmem = psutil.virtual_memory()
    print "System CPU: ",syscpu
    print "System memory: ",sysmem
    # Read single file
    p = psutil.Process(pid)
    proc_cpu = p.cpu_percent(interval=1.0)
    proc_mem = p.memory_percent()
    print "Process CPU: ",proc_cpu
    print "Process Memory: ",proc_mem
    Sleep 1 second
    time.sleep(1)

```

Executed from the terminal on CentOS 6.3 ( w/ Python 2.6.6 and PSutil 2.1.1), with the command "python check_process.py", the script works flawlessly.

Sadly, the script fails on Windows 7 (64 bit):

```

C:\Users\omissis>python c:\check_process.py
Traceback (most recent call last):
  File "c:\check_process.py", line 1, in <module>
    import psutil
  File "c:\psutil.py", line 3, in <module>
    process = filter(lambda p: p.name == "python.exe", psutil.process_iter())
AttributeError: 'module' object has no attribute 'process_iter'

```

As can be seen, the error occurs at the beginning of the script, when the module is imported. It can be reproduced also executing (from a Windows console) a very simple script, containing:

import psutil 

We've tried the same script on Python 2.6.6, 2.7.7 and 3.4.1, always with the same result.

Regards,

Andrea D.
SoftSolutions! Srl
IT Support

**Comment by Vagus79** [comment]
I have this problem when my script was named psutil.py
Just rename your file if you have the same issue.
