### ISSUE TITLE
Test failures / errors

### ISSUE THREAD

**Issue by Arfrever** [giampaolo/psutil#538]
psutil 2.1.2 and trunk have test failures / errors.
I use Linux 3.16.3.

Result with Python 2.7 (similar with 2.6):
```
$ PYTHONPATH="build/lib.linux-x86_64-2.7" python2.7 test/test_psutil.py
...
======================================================================
ERROR: test_swapmem_free (_linux.LinuxSpecificTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/psutil/test/test_psutil.py", line 401, in wrapper
    return fun(*args, **kwargs)
  File "/tmp/psutil/test/_linux.py", line 120, in test_swapmem_free
    free = int(lines[2].split()[3]) * 1024
IndexError: list index out of range

======================================================================
ERROR: test_swapmem_total (_linux.LinuxSpecificTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/psutil/test/_linux.py", line 107, in test_swapmem_total
    total = int(lines[2].split()[1]) * 1024
IndexError: list index out of range

======================================================================
ERROR: test_swapmem_used (_linux.LinuxSpecificTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/psutil/test/test_psutil.py", line 401, in wrapper
    return fun(*args, **kwargs)
  File "/tmp/psutil/test/_linux.py", line 113, in test_swapmem_used
    used = int(lines[2].split()[2]) * 1024
IndexError: list index out of range

======================================================================
FAIL: test_vmem_buffers (_linux.LinuxSpecificTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/psutil/test/test_psutil.py", line 401, in wrapper
    return fun(*args, **kwargs)
  File "/tmp/psutil/test/_linux.py", line 96, in test_vmem_buffers
    delta=TOLERANCE)
AssertionError: 776048640 != 99074048L within 512000 delta

======================================================================
FAIL: test_vmem_cached (_linux.LinuxSpecificTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/psutil/test/test_psutil.py", line 401, in wrapper
    return fun(*args, **kwargs)
  File "/tmp/psutil/test/_linux.py", line 103, in test_vmem_cached
    delta=TOLERANCE)
AssertionError: 896303104 != 472481792 within 512000 delta

======================================================================
FAIL: test_vmem_used (_linux.LinuxSpecificTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/psutil/test/test_psutil.py", line 401, in wrapper
    return fun(*args, **kwargs)
  File "/tmp/psutil/test/_linux.py", line 82, in test_vmem_used
    delta=TOLERANCE)
AssertionError: 771649536 != 1547698176L within 512000 delta

----------------------------------------------------------------------
Ran 132 tests in 9.293s

FAILED (failures=3, errors=3, skipped=1)
```

Result with Python 3.4 (the same with 3.2, 3.3):
```
$ PYTHONPATH="build/lib.linux-x86_64-3.4" python3.4 test/test_psutil.py
...
======================================================================
ERROR: test_swapmem_free (_linux.LinuxSpecificTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/psutil/test/test_psutil.py", line 401, in wrapper
    return fun(*args, **kwargs)
  File "/tmp/psutil/test/_linux.py", line 120, in test_swapmem_free
    free = int(lines[2].split()[3]) * 1024
IndexError: list index out of range

======================================================================
ERROR: test_swapmem_total (_linux.LinuxSpecificTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/psutil/test/_linux.py", line 107, in test_swapmem_total
    total = int(lines[2].split()[1]) * 1024
IndexError: list index out of range

======================================================================
ERROR: test_swapmem_used (_linux.LinuxSpecificTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/psutil/test/test_psutil.py", line 401, in wrapper
    return fun(*args, **kwargs)
  File "/tmp/psutil/test/_linux.py", line 113, in test_swapmem_used
    used = int(lines[2].split()[2]) * 1024
IndexError: list index out of range

======================================================================
ERROR: test_vmem_buffers (_linux.LinuxSpecificTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/psutil/test/test_psutil.py", line 404, in wrapper
    raise
RuntimeError: No active exception to reraise

======================================================================
ERROR: test_vmem_cached (_linux.LinuxSpecificTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/psutil/test/test_psutil.py", line 404, in wrapper
    raise
RuntimeError: No active exception to reraise

======================================================================
ERROR: test_vmem_used (_linux.LinuxSpecificTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/psutil/test/test_psutil.py", line 404, in wrapper
    raise
RuntimeError: No active exception to reraise

----------------------------------------------------------------------
Ran 132 tests in 10.721s

FAILED (errors=6, skipped=1)
```

**Comment by giampaolo** [comment]
Looking back at this, it seems it happens because for some reason the output of your "free" command is different than mine. Here's mine:

                 total       used       free     shared    buffers     cached
    Mem:      10124380    9130136     994244     709672     566908    3441912
    -/+ buffers/cache:    5121316    5003064
    Swap:      2943996          0    2943996

Here's my free version:

    ~/svn/psutil {master}$ free -V
    free from procps-ng 3.3.9

My OS is Ubuntu 14.04.

**Comment by Arfrever** [comment]
```
# free -V
free from procps-ng 3.3.10
```
Maybe format of output was changed in newer version.

**Comment by jelly** [comment]
procps-ng  3.3.10 indeed changed the output format and removed the -/+ buffers/cache line. I'll be looking into a fix for this issue.

**Comment by giampaolo** [comment]
Now that I merged that PR can we close this issue?

**Comment by jelly** [comment]
There are still two failing tests left, I'll have to look into them further.

**Comment by giampaolo** [comment]
I should have fixed all of these failures deriving from bad parsing of `free` cmdline utility. Can somebody please check if they are ok now?

**Comment by jelly** [comment]
I still have these left

```
======================================================================
FAIL: test_memory_maps (test_linux.TestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jelle/projects/psutil/psutil/tests/test_linux.py", line 711, in test_memory_maps
    self.assertEqual(int(rss) * 1024, this.rss)
AssertionError: 0 != 4096

======================================================================
FAIL: test_cached (test_linux.TestSystemVirtualMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jelle/projects/psutil/psutil/tests/__init__.py", line 492, in wrapper
    raise exc
AssertionError: 2087776256 != 1787822080 within 512000 delta

======================================================================
FAIL: test_used (test_linux.TestSystemVirtualMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jelle/projects/psutil/psutil/tests/__init__.py", line 492, in wrapper
    raise exc
AssertionError: 2048389120 != 4409942016 within 512000 delta

----------------------------------------------------------------------
Ran 336 tests in 5.292s
```

**Comment by giampaolo** [comment]
I see from the code that's not the latest GIT version. Can you try this?
```
git clone https://github.com/giampaolo/psutil.git
cd psutil
make test
```

**Comment by jelly** [comment]
You are right, just two left. I guess this because of vmstat?

```
======================================================================
FAIL: test_cached (test_linux.TestSystemVirtualMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jelle/projects/psutil/psutil/tests/__init__.py", line 492, in wrapper
    raise exc
AssertionError: 3202662400 != 2871132160 within 512000 delta

======================================================================
FAIL: test_used (test_linux.TestSystemVirtualMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jelle/projects/psutil/psutil/tests/__init__.py", line 492, in wrapper
    raise exc
AssertionError: 1858871296 != 5340176384 within 512000 delta

----------------------------------------------------------------------
Ran 336 tests in 5.286s
```

**Comment by giampaolo** [comment]
Can you put this into a script and run it?

```
import psutil, subprocess
print "psutil vmem used %s" % psutil.virtual_memory().used
print "psutil vmem cached %s" % psutil.virtual_memory().cached
print subprocess.check_output('free')
print subprocess.check_output(['cat', '/proc/meminfo'])
print subprocess.check_output('vmstat')
```

**Comment by jelly** [comment]
```
In [4]: print "psutil vmem used %s" % psutil.virtual_memory().used
psutil vmem used 5409505280

In [5]: print "psutil vmem cached %s" % psutil.virtual_memory().cached
psutil vmem cached 2979266560

In [6]: print subprocess.check_output('free')
              total        used        free      shared  buff/cache   available
Mem:        8112372     1750140     2830072      102952     3532160     6171444
Swap:       8388604           0     8388604


In [7]: print subprocess.check_output(['cat', '/proc/meminfo'])
MemTotal:        8112372 kB
MemFree:         2830748 kB
MemAvailable:    6172120 kB
Buffers:          281984 kB
Cached:          2909408 kB
SwapCached:            0 kB
Active:          3051632 kB
Inactive:        1711312 kB
Active(anon):    1605656 kB
Inactive(anon):    68860 kB
Active(file):    1445976 kB
Inactive(file):  1642452 kB
Unevictable:          16 kB
Mlocked:              16 kB
SwapTotal:       8388604 kB
SwapFree:        8388604 kB
Dirty:               592 kB
Writeback:             0 kB
AnonPages:       1571360 kB
Mapped:           401072 kB
Shmem:            102952 kB
Slab:             340768 kB
SReclaimable:     295352 kB
SUnreclaim:        45416 kB
KernelStack:        9344 kB
PageTables:        36552 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    12444788 kB
Committed_AS:    5747176 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:    354304 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      417760 kB
DirectMap2M:     7903232 kB


In [8]: print subprocess.check_output('vmstat')
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 1  1      0 2829984 281992 3250168    0    0    42    49   84  396  3  1 96  0  0
```

**Comment by giampaolo** [comment]
No it has to be run "fast" (in a script) in order to avoid memory variations as much as possible.

**Comment by jelly** [comment]
psutil vmem used 5062635520
psutil vmem cached 2942230528
              total        used        free      shared  buff/cache   available
Mem:        8112372     1447768     3168272       61988     3496332     6515204
Swap:       8388604           0     8388604

MemTotal:        8112372 kB
MemFree:         3168252 kB
MemAvailable:    6515184 kB
Buffers:          282720 kB
Cached:          2873272 kB
SwapCached:            0 kB
Active:          2770696 kB
Inactive:        1667928 kB
Active(anon):    1316840 kB
Inactive(anon):    27768 kB
Active(file):    1453856 kB
Inactive(file):  1640160 kB
Unevictable:          16 kB
Mlocked:              16 kB
SwapTotal:       8388604 kB
SwapFree:        8388604 kB
Dirty:              2080 kB
Writeback:             0 kB
AnonPages:       1282644 kB
Mapped:           345532 kB
Shmem:             61988 kB
Slab:             340340 kB
SReclaimable:     295324 kB
SUnreclaim:        45016 kB
KernelStack:        8832 kB
PageTables:        32368 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    12444788 kB
Committed_AS:    4963740 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:    309248 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      417760 kB
DirectMap2M:     7903232 kB

procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 0  0      0 3168196 282720 3213612    0    0    41    48   86  403  3  1 96  0  0

**Comment by giampaolo** [comment]
Fixed in https://github.com/giampaolo/psutil/issues/887
