### ISSUE TITLE
FreeBSD: cpu_affinity() segfaults

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#586]
> user@freebsd9~/psutil$ python3 -c "import psutil; psutil.Process().cpu_affinity(list(range(10000, 11000)))"
    Segmentation fault: 11 (core dumped)

This only happens with Python 3. With Python 2 we get ValueError (as supposed to).

**Comment by giampaolo** [comment]
Update: it also happens on Python 2 from time to time so there's definitively something wrong with the current implementation.
Also, another problem, in case of invalid CPU we may get NSP (instead of ValueError):

    user@freebsd9~/psutil$ python -c "import psutil; psutil.Process().cpu_affinity([199])"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "psutil/__init__.py", line 697, in cpu_affinity
        self._proc.cpu_affinity_set(cpus)
      File "psutil/_psbsd.py", line 229, in wrapper
        raise NoSuchProcess(self.pid, self._name)
    psutil.NoSuchProcess: process no longer exists (pid=43037)
