### ISSUE TITLE
Process.cpu_affinity() should accept a set() (or other iterables)

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#589]
~/svn/psutil {master}$ python -c "import psutil; psutil.Process().cpu_affinity(set([0]))"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "psutil/__init__.py", line 702, in cpu_affinity
        self._proc.cpu_affinity_set(cpus)
      File "psutil/_pslinux.py", line 649, in wrapper
        return fun(self, *args, **kwargs)
      File "psutil/_pslinux.py", line 961, in cpu_affinity_set
        cext.proc_cpu_affinity_set(self.pid, cpus)
    TypeError: sequence argument expected, got set

This is kind of related to #525. Since in #525 we're going to return a set it is better for cpu_affinity() (set) to also accept a set or any other iterable.

**Comment by giampaolo** [comment]
Fixed in 4320a329c9957fb9b0a172afcfcac3cc26a749e8.
