### ISSUE TITLE
Get thread names when using Process.threads()

### ISSUE THREAD

**Issue by bleedinge** [giampaolo/psutil#613]
Since that information is already in the /proc filesystem stat file, it would be great if the tuple returned by threads() could contain the thread name (2nd parameter in the stat file) next to the pid, utime and stime.

**Comment by giampaolo** [comment]
Yes, this is something I've been wanting to do for a while. It's likely we will not able to retrieve `name` an all platforms but since it's an important data I think it's worth it to return it anyway on those platforms supporting it.

**Comment by giampaolo** [comment]
Windows doesn't have thread names: http://stackoverflow.com/questions/9366722/how-to-get-the-name-of-a-win32-thread

**Comment by giampaolo** [comment]
Patch for OSX available at:
https://code.google.com/p/plcrashreporter/issues/detail?id=65
Sample code:
https://github.com/janmojzis/pstree/blob/master/proc_kvm.c

**Comment by fthiery** [comment]
Sorry to "necrobump" this, but are there any reasons why these commits have not been merged on master ?

**Comment by giampaolo** [comment]
There are no "commits", just some research I did back then. I ended up forgetting about this because I don't consider it too important but any PR is welcome. ;)

**Comment by fthiery** [comment]
Well, there's a branch :) I could start from that point, do you remember what was left ? Some testing maybe ? Or does this not merge anymore ?

**Comment by giampaolo** [comment]
Oh! I totally forgot there was a branch, sorry. It seems back then I added the implementation for Linux, FreeBSD and OpenBSD. In order to revamp this issue we should 1) rebase from the current master and 2) add the OSX implementation, then it would be reasonably good to go.

**Comment by fthiery** [comment]
Did my best: https://github.com/giampaolo/psutil/pull/1135

The tests work (although one of them fails -- i'm not sure it is related though):
```
FAILED (failures=3, errors=14, skipped=148)
Test failed: <unittest.runner.TextTestResult run=506 errors=14 failures=3>
error: Test failed: <unittest.runner.TextTestResult run=506 errors=14 failures=3>
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/fthiery/src/ubicast/mediacoder/psutil/psutil/tests/__init__.py", line 199, in _cleanup_procs
    reap_children(recursive=True)
  File "/home/fthiery/src/ubicast/mediacoder/psutil/psutil/tests/__init__.py", line 441, in reap_children
    children = set(psutil.Process().children(recursive=True))
  File "/home/fthiery/src/ubicast/mediacoder/psutil/psutil/__init__.py", line 392, in __init__
    self._init(pid)
  File "/home/fthiery/src/ubicast/mediacoder/psutil/psutil/__init__.py", line 414, in _init
    self._proc = _psplatform.Process(pid)
  File "/home/fthiery/src/ubicast/mediacoder/psutil/psutil/_pslinux.py", line 1392, in __init__
    self._procfs_path = get_procfs_path()
  File "/home/fthiery/src/ubicast/mediacoder/psutil/psutil/_pslinux.py", line 217, in get_procfs_path
    return sys.modules['psutil'].PROCFS_PATH
KeyError: 'psutil'
```

Is OSX really supposed to support naming threads ?

Btw i tested it manually against my use case and it worked.

**Comment by fthiery** [comment]
I confirm the same test crashes on master

**Comment by giampaolo** [comment]
Just FYI I won't have time to look into this any time soon, sorry.

**Comment by mfoglio** [comment]
Hello, any update on this? I tried to retrieve thread names using:
`
threading._active.get(id)
`
but it seems like the `id` returned for each thread by `Process.threads()` is not the correct id
