### ISSUE TITLE
Sphinx / Latex build error

### ISSUE THREAD

**Issue by gvanem** [giampaolo/psutil#631]
I have no problem building the HTML or manpage docs, but in generating Latex using Sphinx v1.3b, I get this error:
```
F:\...thon27\Lib\site-packages\psutil-3.0\docs> sphinx-build -v -b latex -d _build/doctrees   . _build/latex
Running Sphinx v1.3b2
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index
Didn't find Process.uids in psutil
Didn't find Process.gids in psutil
Didn't find Process.terminal in psutil
Didn't find Process.rlimit in psutil
Didn't find Process.num_fds in psutil
Didn't find STATUS_WAKE_KILL in psutil
Didn't find CONN_IDLE in psutil
Didn't find CONN_BOUND in psutil
Didn't find IOPRIO_CLASS_NONE in psutil
Didn't find IOPRIO_CLASS_RT in psutil
Didn't find IOPRIO_CLASS_BE in psutil
Didn't find IOPRIO_CLASS_IDLE in psutil
Didn't find RLIMIT_INFINITY in psutil
Didn't find RLIMIT_AS in psutil
Didn't find RLIMIT_CORE in psutil
Didn't find RLIMIT_CPU in psutil
Didn't find RLIMIT_DATA in psutil
Didn't find RLIMIT_FSIZE in psutil
Didn't find RLIMIT_LOCKS in psutil
Didn't find RLIMIT_MEMLOCK in psutil
Didn't find RLIMIT_MSGQUEUE in psutil
Didn't find RLIMIT_NICE in psutil
Didn't find RLIMIT_NOFILE in psutil
Didn't find RLIMIT_NPROC in psutil
Didn't find RLIMIT_RSS in psutil
Didn't find RLIMIT_RTPRIO in psutil
Didn't find RLIMIT_RTTIME in psutil
Didn't find RLIMIT_RTPRIO in psutil
Didn't find RLIMIT_SIGPENDING in psutil
Didn't find RLIMIT_STACK in psutil

looking for now-outdated files... none found
pickling environment... done
checking consistency... done

Traceback (most recent call last):
  File "F:\ProgramFiler\Python27\lib\site-packages\sphinx-1.3b2-py2.7.egg\sphinx\cmdline.py", line 246, in main
    app.build(opts.force_all, filenames)
  File "F:\ProgramFiler\Python27\lib\site-packages\sphinx-1.3b2-py2.7.egg\sphinx\application.py", line 257, in build
    self.builder.build_update()
  File "F:\ProgramFiler\Python27\lib\site-packages\sphinx-1.3b2-py2.7.egg\sphinx\builders\__init__.py", line 232, in build_update
    self.build(['__all__'], to_build)
  File "F:\ProgramFiler\Python27\lib\site-packages\sphinx-1.3b2-py2.7.egg\sphinx\builders\__init__.py", line 308, in build
    self.write(docnames, list(updated_docnames), method)
  File "F:\ProgramFiler\Python27\lib\site-packages\sphinx-1.3b2-py2.7.egg\sphinx\builders\latex.py", line 89, in write
    docname, targetname, title, author, docclass = entry[:5]
ValueError: need more than 4 values to unpack

Exception occurred:
  File "F:\ProgramFiler\Python27\lib\site-packages\sphinx-1.3b2-py2.7.egg\sphinx\builders\latex.py", line 89, in write
    docname, targetname, title, author, docclass = entry[:5]
ValueError: need more than 4 values to unpack
The full traceback has been saved in c:\temp\sphinx-err-qp342z.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time. A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. 
Thanks!
```

Looking at latex.py, I fail to see how:
```
 for entry in self.document_data:
     docname, targetname, title, author, docclass = entry[:5]
```
is supposed to be set.

I'm using Python 2.7.9.

**Comment by giampaolo** [comment]
Mmm that looks like a sphinx bug. You probably better report this in sphinx bug tracker.
