### ISSUE TITLE
Installing psutil via setup.py fails

### ISSUE THREAD

**Issue by harshadyeola** [giampaolo/psutil#678]
I am facing issues installing psutil via `setup.py`

```
Searching for psutil
Reading https://pypi.python.org/simple/psutil/
Best match: psutil 3.2.1
Downloading https://pypi.python.org/packages/source/p/psutil/psutil-3.2.1.tar.gz#md5=a308816e735021fd4bf6aa561725c1aa
Processing psutil-3.2.1.tar.gz
Writing /tmp/easy_install-la6ibf43/psutil-3.2.1/setup.cfg
Running psutil-3.2.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-la6ibf43/psutil-3.2.1/egg-dist-tmp-0k93e4ei
Traceback (most recent call last):
  File "setup.py", line 98, in <module>
    namespace_packages=[],
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 96, in do_egg_install
    cmd.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 381, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 597, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 648, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 694, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 620, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 858, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 870, in obtain
    return installer(requirement)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 646, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1025, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 50, in run_setup
    lambda: execfile(
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 100, in run
    return func()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 52, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "/usr/lib/python3/dist-packages/setuptools/compat.py", line 78, in execfile
    exec(compile(source, fn, 'exec'), globs, locs)
  File "setup.py", line 162, in <module>
  File "setup.py", line 156, in get_ethtool_macro
  File "/usr/lib/python3.4/distutils/ccompiler.py", line 566, in compile
    depends, extra_postargs)
  File "/usr/lib/python3.4/distutils/ccompiler.py", line 348, in _setup_compile
    self.mkpath(os.path.dirname(obj))
  File "/usr/lib/python3.4/distutils/ccompiler.py", line 915, in mkpath
    mkpath(name, mode, dry_run=self.dry_run)
  File "/usr/lib/python3.4/distutils/dir_util.py", line 66, in mkpath
    log.info("creating %s", head)
  File "/usr/lib/python3.4/distutils/log.py", line 44, in info
    self._log(INFO, msg, args)
  File "/usr/lib/python3.4/distutils/log.py", line 30, in _log
    if stream.errors == 'strict':
AttributeError: 'DummyFile' object has no attribute 'errors'
root@vagrant-ubuntu-trusty-64:~/easyengine# ee -v
Traceback (most recent call last):
  File "/usr/local/bin/ee", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: psutil
```

**Comment by giampaolo** [comment]
Can you try https://github.com/giampaolo/psutil/commit/af403501e1cad8d89e8dec98ed87c118b7c31620 and tell me if it works?

**Comment by giampaolo** [comment]
Up?
