### ISSUE TITLE
[Windows] psutil.disk_usage() can't handle unicode paths

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#763]
https://ci.appveyor.com/project/giampaolo/psutil/build/473/job/fk8t97nk4bt7i9a0

```
======================================================================
ERROR: test_disk_usage (test_process.TestUnicode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\psutil\psutil\tests\test_process.py", line 1894, in test_disk_usage
    psutil.disk_usage(self.uexe)
  File "c:\projects\psutil\psutil\__init__.py", line 1765, in disk_usage
    return _psplatform.disk_usage(path)
  File "c:\projects\psutil\psutil\_pswindows.py", line 164, in disk_usage
    total, free = cext.disk_usage(path)
WindowsError: [Error 267] The directory name is invalid
```

**Comment by giampaolo** [comment]
shutil.disk_usage() on python 3 has the same problem: http://bugs.python.org/issue26330

**Comment by giampaolo** [comment]
It turns out there's no real issue here as per further discussion in http://bugs.python.org/issue26330. Closing.
