### ISSUE TITLE
RFC - fix problem with the correct pid type on big-endian 64-bit machines

### ISSUE THREAD

**Issue by wxwright** [giampaolo/psutil#776]
The get_cpu_affinity() returns error for process no longer exists when running on a System Z or PPC64 machine (big endian 64bit).   Here's a sample test:

```
[root@ltczhyp6 ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.1 (Maipo)
[root@ltczhyp6 ~]# rpm -qa|grep python-psutil
python-psutil-2.2.0-2.fc23.s390x
[root@ltczhyp6 ~]# python
Python 2.7.5 (default, Feb 11 2014, 07:45:13)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-13)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> p = psutil.Process(4734)
>>> p.get_cpu_affinity()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/psutil/_common.py", line 142, in inner
    return getattr(self, replacement)(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/psutil/__init__.py", line 698, in cpu_affinity
    return self._proc.cpu_affinity_get()
  File "/usr/lib64/python2.7/site-packages/psutil/_pslinux.py", line 653, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=4734)
>>>
```

The root cause is the wrong pid type that is passed to PyArg_ParseTuple in psutil_proc_cpu_affinity_get call, and here's the proposed fix:

```
--- _psutil_linux.c.orig	2016-02-23 16:49:25.593971637 -0500
+++ _psutil_linux.c	2016-02-23 16:49:46.357971751 -0500
@@ -275,7 +275,7 @@ psutil_proc_cpu_affinity_get(PyObject *s
     cpu_set_t *mask = NULL;
     PyObject *py_list = NULL;
 
-    if (!PyArg_ParseTuple(args, "i", &pid))
+    if (!PyArg_ParseTuple(args, "l", &pid))
         return NULL;
     ncpus = NCPUS_START;
     while (1) {
```

**Comment by giampaolo** [comment]
Fixed. Thanks.
