### ISSUE TITLE
psutil 4.0.0 - structure size mismatch

### ISSUE THREAD

**Issue by php-freak** [giampaolo/psutil#876]
Hello,

I am forced to use psutil 4.0.0 cause this is the only version we have compiled for Solaris and getting a new version by our administrators approved would take months :-( 

I already added the fixed which were related to this issue: https://github.com/giampaolo/psutil/issues/857 but today I got a new error:

```
Traceback (most recent call last):
  File "main.py", line 92, in <module>
	for proc in psutil.process_iter():
  File "psutil/__init__.py", line 1332, in process_iter
	yield add(pid)
  File "psutil/__init__.py", line 1314, in add
	proc = Process(pid)
  File "psutil/__init__.py", line 363, in __init__
	self._init(pid)
  File "psutil/__init__.py", line 389, in _init
	self.create_time()
  File "psutil/__init__.py", line 650, in create_time
	self._create_time = self._proc.create_time()
  File "psutil/_pssunos.py", line 261, in wrapper
	return fun(self, *args, **kwargs)
  File "psutil/_pssunos.py", line 313, in create_time
	return cext.proc_basic_info(self.pid, self._procfs_path)[3]
RuntimeError: structure size mismatch
```

Has anybody an idea whats this about?

**Comment by giampaolo** [comment]
This was fixed in #857. What you can do is use the latest GIT version, as there's no official release yet.
