### ISSUE TITLE
test_memory_leaks tests failure in Fedora rawhide

### ISSUE THREAD

**Issue by nirik** [giampaolo/psutil#946]
Greetings. 

I am seeing test failures with 5.0.0 and 5.0.1 and Fedora rawhide: 

From the build.log:

```
test_memory_leaks.TestTerminatedProcessLeaks.test_rlimit_get ... ok
test_memory_leaks.TestTerminatedProcessLeaks.test_rlimit_set ... ok
test_memory_leaks.TestTerminatedProcessLeaks.test_status ... ok
test_memory_leaks.TestTerminatedProcessLeaks.test_terminal ... ok
test_memory_leaks.TestTerminatedProcessLeaks.test_threads ... ok
test_memory_leaks.TestTerminatedProcessLeaks.test_uids ... ok
test_memory_leaks.TestTerminatedProcessLeaks.test_username ... skipped 'worthless on POSIX'
======================================================================
FAIL: test_memory_leaks.TestProcessObjectLeaks.test_cpu_affinity_set
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/psutil-release-5.0.1/psutil/tests/test_memory_leaks.py", line 303, in test_cpu_affinity_set
    self.execute_w_exc(ValueError, self.proc.cpu_affinity, [-1])
  File "/builddir/build/BUILD/psutil-release-5.0.1/psutil/tests/test_memory_leaks.py", line 155, in execute_w_exc
    self.execute(call)
  File "/builddir/build/BUILD/psutil-release-5.0.1/psutil/tests/test_memory_leaks.py", line 145, in execute
    ncalls
AssertionError: +64.00K after 1000 calls, +124.00K after another 19780 calls
======================================================================
FAIL: test_memory_leaks.TestTerminatedProcessLeaks.test_cpu_affinity_set
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/psutil-release-5.0.1/psutil/tests/test_memory_leaks.py", line 303, in test_cpu_affinity_set
    self.execute_w_exc(ValueError, self.proc.cpu_affinity, [-1])
  File "/builddir/build/BUILD/psutil-release-5.0.1/psutil/tests/test_memory_leaks.py", line 155, in execute_w_exc
    self.execute(call)
  File "/builddir/build/BUILD/psutil-release-5.0.1/psutil/tests/test_memory_leaks.py", line 145, in execute
    ncalls
AssertionError: +16.00K after 1000 calls, +8.00K after another 18849 calls
----------------------------------------------------------------------
Ran 83 tests in 28.718s
FAILED (failures=2, skipped=9)
```

The full build is at https://koji.fedoraproject.org/koji/taskinfo?taskID=17095971

happy to gather more info.

**Comment by giampaolo** [comment]
Uhm... that looks like a false positive. I would say just ignore it.
What's more interesting is the fact that there's a continuos integration service for Fedora. =)
Is there anyway I can be able to use it?

**Comment by nirik** [comment]
Well, it's not really a CI, it's just running the tests as part of the official build. 
If the tests fail, the build fails. :) 

So, yeah, I could disable those tests, but would be nice to figure out why they are showing this false positive and fix them.

**Comment by giampaolo** [comment]
I'm not sure how to make the memory leaks test more reliable.  In general, it was not designed to be 100% bullet proof.

**Comment by giampaolo** [comment]
Closing out as invalid (false positive)
