### ISSUE TITLE
psutil got UnicodeDecodeError

### ISSUE THREAD

**Issue by zhenghan008** [giampaolo/psutil#993]
Hi.I met a problem.
```
import psutil
for each_process in psutil.pids():
    p = psutil.Process(each_process)
    print(p.as_dict()['name'])`
```

Error:

```
`fdlauncher.exe
SearchIndexer.exe
fdhost.exe
conhost.exe
svchost.exe
WUDFHost.exe
wmpnetwk.exe
QQProtect.exe
Traceback (most recent call last):
  File "E:/Server_Info/test.py", line 8, in <module>
    print(p.as_dict()['name'])
  File "D:\python35\lib\site-packages\psutil\__init__.py", line 563, in as_dict
    ret = meth()
  File "D:\python35\lib\site-packages\psutil\__init__.py", line 1178, in memory_maps
    for tupl in it:
  File "D:\python35\lib\site-packages\psutil\_pswindows.py", line 746, in memory_maps
    raw = cext.proc_memory_maps(self.pid)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 34: invalid continuation byte
```

My operating environment is win7 , python 3.5, psutil 5.2.

**Comment by giampaolo** [comment]
I should have a fix for this. Could you check whether you get this error also on Python 2.7?

**Comment by zhenghan008** [comment]
@giampaolo ok!I got it. thank you!
