### ISSUE TITLE
Windows process support

### ISSUE THREAD

**Issue by benstroud** [giampaolo/psutil#994]
Part of the attractiveness of SWF is the ability to deploy workflows anywhere. Support for Windows would be helpful. I encountered the following when attempting to deploy a simpleflow workflow on a Windows system:

`signal.SIGCHLD` is not currently supported on Windows.

`psutil` dependency is not currently supported on Cygwin.

**Comment by SethMichaelLarson** [comment]
Could you provide some more information, perhaps a minimal repoducible case where you encountered this error? It would help investigate this issue a lot. :)

**Comment by SethMichaelLarson** [comment]
Looks like #82 may be related? Has anything been done with this issue? cc: @embray

**Comment by benstroud** [comment]
https://github.com/botify-labs/simpleflow/blob/master/simpleflow/process/supervisor.py

Using the standard 2.7 Python installer on Windows Server 2012: The supervisor module (used by `simpleflow decider.start` and `simpleflow worker.start` command line invocations) fails to rely on `signal.SIGCHLD` as it is not supported on Windows. This limitation prevents the simpleflow command-line long polling from starting.

Using Cygwin with 2.7 Python on Windows Server 2012 (where I believe SGCHLD should be implemented): Here the `psutil` dependency fails to work as documented here: https://github.com/giampaolo/psutil/issues/82.

Personally I'm more interested in the standard Windows Python installation working more so than Cygwin. I turned to Cygwin as a potential workaround.

I'm now looking at initiating the long polling of simpleflow workers/activities and workflows/deciders outside of the simple.process.supervisor process management. It seems the SIGCHLD signal is used in multiprocess coordination to ensure that --nb-processes number of subprocesses remain active.

**Comment by benstroud** [comment]
```
(venv) D:\Users\ben.stroud\smartmatch>simpleflow decider.start --nb-processes 1 --domain smartmatch-canada-dev --task-list smartmatch.workflow.canada
smartmatch.activity.canada_consumer_match.CanadaConsumerMatchWorkflow

2017-03-20T14:05:02 ←[92mINFO←[0m [process=MainProcess, pid=25992]: starting <bound method DeciderPoller.start of DeciderPoller(smartmatch-canada-dev,
 smartmatch.workflow.canada, smartmatch.workflow.canada_consumer_match)>
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\Users\ben.stroud\smartmatch\venv\Scripts\simpleflow.exe\__main__.py", line 9, in <module>
  File "d:\users\ben.stroud\smartmatch\venv\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "d:\users\ben.stroud\smartmatch\venv\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "d:\users\ben.stroud\smartmatch\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\users\ben.stroud\smartmatch\venv\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\users\ben.stroud\smartmatch\venv\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "d:\users\ben.stroud\smartmatch\venv\lib\site-packages\simpleflow\command.py", line 380, in start_decider
    nb_processes,
  File "d:\users\ben.stroud\smartmatch\venv\lib\site-packages\simpleflow\swf\process\decider\command.py", line 42, in start
    decider.start()
  File "d:\users\ben.stroud\smartmatch\venv\lib\site-packages\simpleflow\process\named_mixin.py", line 22, in wrapped
    return method(self, *args, **kwargs)
  File "d:\users\ben.stroud\smartmatch\venv\lib\site-packages\simpleflow\process\supervisor.py", line 90, in start
    self.target()
  File "d:\users\ben.stroud\smartmatch\venv\lib\site-packages\simpleflow\process\supervisor.py", line 113, in target
    self.bind_signal_handlers()
  File "d:\users\ben.stroud\smartmatch\venv\lib\site-packages\simpleflow\process\supervisor.py", line 187, in bind_signal_handlers
    signal.signal(signal.SIGCHLD, _handle_sigchld)
AttributeError: 'module' object has no attribute 'SIGCHLD'
```

**Comment by embray** [comment]
I'm actually nearly done the Cygwin port of psutil.  Been working for it off and on over the last several months.  The only hold up right now is I'm trying to get the tests to pass on AppVeyor.  Stay tuned...

**Comment by embray** [comment]
The above traceback doesn't look like it's to do with psutil?

**Comment by benstroud** [comment]
Doh. I've made a big mistake here and opened the issue for psutil instead of simpleflow. I had both projects open in GitHub and landed on the wrong tab. My apologies. I'll close and refile. Thanks for the info on Cygwin/psutil.

**Comment by SethMichaelLarson** [comment]
Thanks for chiming in @embray.

**Comment by giampaolo** [comment]
I suppose `SIGCHLD` cannot be supported on Windows natively. Note: psutil already makes an effort by supporting `CTRL_C_EVENT` and `CTRL_BREAK_EVENT` (via `send_signal`).
